// Code generated by ggen; DO NOT EDIT.

package thirdparty2

import (
	"math"
	"strconv"
	"strings"
	"unsafe"

	"github.com/sirkostya009/ggen/decode"
	"github.com/sirkostya009/ggen/decode/validation"
	"github.com/sirkostya009/ggen/encode"
	"github.com/sirkostya009/ggen/scan"
)

func (result External2) DecodeFrom(data []byte) (External2, int, error) {
	i := 0
	var err error
	_ = err
	seenKey := false
	seenValue := false
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, scan.ErrBadObject
	}
	i++
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		if !seenKey {
			return result, i, &validation.RequiredError{Field: "key"}
		}
		return result, i + 1, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, scan.ErrExpectString
		}
		{
			ke := i + 1
			for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
				ke++
			}
			if ke >= len(data) {
				return result, i, scan.ErrUnterminated
			}
			if data[ke] < 0x20 {
				return result, i, scan.ErrBadString
			}
			if data[ke] == '"' {
				key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				key, i, err = scan.String(data, i)
				if err != nil {
					return result, i, err
				}
			}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, scan.ErrBadObject
		}
		i++
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch len(key) {
		case 3:
			if key == "key" {
				if seenKey {
					return result, i, &validation.DuplicateKeyError{Field: "key"}
				}
				seenKey = true
				if i >= len(data) || data[i] != '"' {
					return result, i, scan.ErrExpectString
				}
				{
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, scan.ErrUnterminated
					}
					if data[ke] < 0x20 {
						return result, i, scan.ErrBadString
					}
					if data[ke] == '"' {
						result.Key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.Key, i, err = scan.String(data, i)
						if err != nil {
							return result, i, err
						}
					}
				}
				if len(result.Key) < 1 {
					return result, i, &validation.MinLenError{Field: "key", Limit: 1, Got: len(result.Key)}
				}
			} else {
				return result, i, &validation.UnknownKeyError{Field: key}
			}
		case 5:
			if key == "value" {
				if seenValue {
					return result, i, &validation.DuplicateKeyError{Field: "value"}
				}
				seenValue = true
				{
					neg := false
					if i < len(data) && data[i] == '-' {
						neg = true
						i++
					}
					if i >= len(data) || data[i] < '0' || data[i] > '9' {
						return result, i, scan.ErrBadNumber
					}
					limit := uint64(math.MaxInt64)
					if neg {
						limit = scan.SignedNeg
					}
					var u uint64
					for i < len(data) && data[i] >= '0' && data[i] <= '9' {
						d := uint64(data[i] - '0')
						if u > limit/10 || (u == limit/10 && d > limit%10) {
							return result, i, scan.ErrNumberOverflow
						}
						u = u*10 + d
						i++
					}
					if i < len(data) {
						c := data[i]
						if c == '.' || c == 'e' || c == 'E' {
							return result, i, scan.ErrBadNumber
						}
					}
					var n int64
					if neg {
						if u == scan.SignedNeg {
							n = math.MinInt64
						} else {
							n = -int64(u)
						}
					} else {
						n = int64(u)
					}
					result.Value = int(n)
				}
				if result.Value < 0 {
					return result, i, &validation.GTEError{Field: "value", Limit: 0, Value: result.Value}
				}
			} else {
				return result, i, &validation.UnknownKeyError{Field: key}
			}
		default:
			return result, i, &validation.UnknownKeyError{Field: key}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, scan.ErrBadObject
		}
		if data[i] == ',' {
			i++
			for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			if !seenKey {
				return result, i, &validation.RequiredError{Field: "key"}
			}
			return result, i + 1, nil
		}
		return result, i, scan.ErrBadObject
	}
}

func (result External2) DecodeStreamFrom(s *scan.Stream) (External2, error) {
	seenKey := false
	seenValue := false
	err := s.ObjectOpen()
	if err != nil {
		return result, err
	}
	err = s.SkipSpace()
	if err != nil {
		return result, err
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, err
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		if !seenKey {
			return result, &validation.RequiredError{Field: "key"}
		}
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, err
		}
		switch len(key) {
		case 3:
			if key == "key" {
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenKey {
					return result, &validation.DuplicateKeyError{Field: "key"}
				}
				seenKey = true
				result.Key, err = s.String()
				if err != nil {
					return result, err
				}
				if len(result.Key) < 1 {
					return result, &validation.MinLenError{Field: "key", Limit: 1, Got: len(result.Key)}
				}
			} else {
				return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
			}
		case 5:
			if key == "value" {
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenValue {
					return result, &validation.DuplicateKeyError{Field: "value"}
				}
				seenValue = true
				var iv int64
				iv, err = s.Int64()
				if err != nil {
					return result, err
				}
				result.Value = int(iv)
				if result.Value < 0 {
					return result, &validation.GTEError{Field: "value", Limit: 0, Value: result.Value}
				}
			} else {
				return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
			}
		default:
			return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
		}
		err = s.SkipSpace()
		if err != nil {
			return result, err
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, err
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, err
			}
			continue
		}
		if c == '}' {
			if !seenKey {
				return result, &validation.RequiredError{Field: "key"}
			}
			s.Pos++
			return result, nil
		}
		return result, scan.ErrBadObject
	}
}

func (s External2) JSONSize() int {
	size := 39
	size += len(s.Key) * 2
	return size
}

func (s External2) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"key\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Key)
	dst = append(dst, ",\"value\":"...)
	dst = strconv.AppendInt(dst, int64(s.Value), 10)
	return append(dst, '}'), nil
}

func (s External2) MarshalJSON() ([]byte, error) {
	return encode.Marshal(s)
}

func (s *External2) UnmarshalJSON(data []byte) error {
	v, err := decode.Unmarshal[External2](data)
	if err != nil {
		return err
	}
	*s = v
	return nil
}
