// Code generated by ggen; DO NOT EDIT.

package integrationtests

import (
	"math"
	"strconv"
	"strings"
	"unsafe"

	"github.com/sirkostya009/ggen/decode"
	"github.com/sirkostya009/ggen/encode"
	"github.com/sirkostya009/ggen/scan"
	"github.com/sirkostya009/ggen/validation"
)

// Tries to fit >2 elements in 80 bytes, then 512 bytes - never goes above that.
const ggenCap_CustomBothStruct_Tags_string = (min((80/max(int(unsafe.Sizeof(*new(string))), 1)), 2)/2)*(80/max(int(unsafe.Sizeof(*new(string))), 1)) + (1-(min((80/max(int(unsafe.Sizeof(*new(string))), 1)), 2)/2))*max(((8*int(unsafe.Sizeof(uintptr(0)))*int(unsafe.Sizeof(uintptr(0))))/max(int(unsafe.Sizeof(*new(string))), 1)), 1)

var ggenOneof_custom_0 = []string{"admin", "user", "guest"}

func (recv MultiErrStruct) DecodeFrom(data []byte) (result MultiErrStruct, i int, err error) {
	result = recv
	var errs validation.Errors
	seenAge := false
	seenName := false
	seenRole := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenName {
			errs = append(errs, &validation.RequiredError{Pos: i, Path: []string{"name"}})
		}
		if len(errs) > 0 {
			return result, i, errs
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i, true)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "age":
			if seenAge {
				errs = append(errs, &validation.DuplicateKeyError{Pos: i, Path: []string{"age"}})
				i, err = scan.SkipValue(data, i)
				if err != nil {
					return result, i, decode.NewParseErr("age", i, err)
				}
			} else {
				seenAge = true
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, decode.NewParseErr("age", i, scan.ErrBadNumber)
				}
				if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
					return result, i, decode.NewParseErr("age", i, scan.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = scan.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, decode.NewParseErr("age", i, scan.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, decode.NewParseErr("age", i, scan.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == scan.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				result.Age = int(n)
				if result.Age < 0 {
					errs = append(errs, &validation.GTEError{Pos: i, Path: []string{"age"}, Limit: 0, Value: result.Age})
				}
				if result.Age > 100 {
					errs = append(errs, &validation.LTEError{Pos: i, Path: []string{"age"}, Limit: 100, Value: result.Age})
				}
			}
		case "name":
			if seenName {
				errs = append(errs, &validation.DuplicateKeyError{Pos: i, Path: []string{"name"}})
				i, err = scan.SkipValue(data, i)
				if err != nil {
					return result, i, decode.NewParseErr("name", i, err)
				}
			} else {
				seenName = true
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("name", i, scan.ErrExpectString)
				}
				ke := i + 1
				kew := ke + 32
				if kew > len(data) {
					kew = len(data)
				}
				for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
				if ke < len(data) && data[ke] == '"' {
					result.Name = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
					i = ke + 1
				} else {
					result.Name, i, err = scan.String(data, i, true)
					if err != nil {
						return result, i, decode.NewParseErr("name", i, err)
					}
				}
				if len(result.Name) < 1 {
					errs = append(errs, &validation.MinLenError{Pos: i, Path: []string{"name"}, Limit: 1, Got: len(result.Name)})
				}
				if len(result.Name) > 5 {
					errs = append(errs, &validation.MaxLenError{Pos: i, Path: []string{"name"}, Limit: 5, Got: len(result.Name)})
				}
			}
		case "role":
			if seenRole {
				errs = append(errs, &validation.DuplicateKeyError{Pos: i, Path: []string{"role"}})
				i, err = scan.SkipValue(data, i)
				if err != nil {
					return result, i, decode.NewParseErr("role", i, err)
				}
			} else {
				seenRole = true
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("role", i, scan.ErrExpectString)
				}
				ke := i + 1
				kew := ke + 32
				if kew > len(data) {
					kew = len(data)
				}
				for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
				if ke < len(data) && data[ke] == '"' {
					result.Role = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
					i = ke + 1
				} else {
					result.Role, i, err = scan.String(data, i, true)
					if err != nil {
						return result, i, decode.NewParseErr("role", i, err)
					}
				}
				switch result.Role {
				case "admin", "user", "guest":
				default:
					errs = append(errs, &validation.OneOfError{Pos: i, Path: []string{"role"}, Allowed: ggenOneof_custom_0, Value: result.Role})
				}
			}
		default:
			errs = append(errs, &validation.UnknownKeyError{Pos: i, Path: []string{key}})
			i, err = scan.SkipValue(data, i)
			if err != nil {
				return result, i, decode.NewParseErr(key, i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenName {
				errs = append(errs, &validation.RequiredError{Pos: i, Path: []string{"name"}})
			}
			if len(errs) > 0 {
				return result, i, errs
			}
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv MultiErrStruct) DecodeFromStream(s *scan.Stream) (result MultiErrStruct, err error) {
	result = recv
	var errs validation.Errors
	seenAge := false
	seenName := false
	seenRole := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Offset(), scan.NotEOF(err, scan.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenName {
			errs = append(errs, &validation.RequiredError{Pos: s.Offset(), Path: []string{"name"}})
		}
		if len(errs) > 0 {
			return result, errs
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, decode.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "age":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("age", s.Offset(), err)
			}
			if seenAge {
				errs = append(errs, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"age"}})
				err = s.SkipValue()
				if err != nil {
					return result, decode.NewParseErr("age", s.Offset(), err)
				}
			} else {
				seenAge = true
				var iv int64
				iv, err = s.Int64()
				if err != nil {
					return result, decode.NewParseErr("age", s.Offset(), err)
				}
				result.Age = int(iv)
				if result.Age < 0 {
					errs = append(errs, &validation.GTEError{Pos: s.Offset(), Path: []string{"age"}, Limit: 0, Value: result.Age})
				}
				if result.Age > 100 {
					errs = append(errs, &validation.LTEError{Pos: s.Offset(), Path: []string{"age"}, Limit: 100, Value: result.Age})
				}

			}
		case "name":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("name", s.Offset(), err)
			}
			if seenName {
				errs = append(errs, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"name"}})
				err = s.SkipValue()
				if err != nil {
					return result, decode.NewParseErr("name", s.Offset(), err)
				}
			} else {
				seenName = true
				result.Name, err = s.String(true)
				if err != nil {
					return result, decode.NewParseErr("name", s.Offset(), err)
				}
				if len(result.Name) < 1 {
					errs = append(errs, &validation.MinLenError{Pos: s.Offset(), Path: []string{"name"}, Limit: 1, Got: len(result.Name)})
				}
				if len(result.Name) > 5 {
					errs = append(errs, &validation.MaxLenError{Pos: s.Offset(), Path: []string{"name"}, Limit: 5, Got: len(result.Name)})
				}

			}
		case "role":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("role", s.Offset(), err)
			}
			if seenRole {
				errs = append(errs, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"role"}})
				err = s.SkipValue()
				if err != nil {
					return result, decode.NewParseErr("role", s.Offset(), err)
				}
			} else {
				seenRole = true
				result.Role, err = s.String(true)
				if err != nil {
					return result, decode.NewParseErr("role", s.Offset(), err)
				}
				switch result.Role {
				case "admin", "user", "guest":
				default:
					errs = append(errs, &validation.OneOfError{Pos: s.Offset(), Path: []string{"role"}, Allowed: ggenOneof_custom_0, Value: result.Role})
				}

			}
		default:
			errs = append(errs, &validation.UnknownKeyError{Pos: s.Offset(), Path: []string{strings.Clone(key)}})
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr(strings.Clone(key), s.Offset(), err)
			}
			err = s.SkipValue()
			if err != nil {
				return result, decode.NewParseErr(strings.Clone(key), s.Offset(), err)
			}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Offset(), scan.NotEOF(err, scan.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenName {
				errs = append(errs, &validation.RequiredError{Pos: s.Offset(), Path: []string{"name"}})
			}
			if len(errs) > 0 {
				return result, errs
			}
			return result, nil
		}
		return result, decode.NewParseErr("", s.Offset(), scan.ErrBadObject)
	}
}

func (s MultiErrStruct) JSONSize() int {
	size := 48
	size += len(s.Name) * 2
	size += len(s.Role) * 2
	return size
}

func (s MultiErrStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"age\":"...)
	dst = strconv.AppendInt(dst, int64(s.Age), 10)
	dst = append(dst, ",\"name\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Name)
	dst = append(dst, ",\"role\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Role)
	return append(dst, '}'), nil
}

func (recv CustomBothStruct) DecodeFrom(data []byte) (result CustomBothStruct, i int, err error) {
	result = recv
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	seenTags := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i, true)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "tags":
			if seenTags {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"tags"}}
			}
			seenTags = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				i += 4
				result.Tags = nil
				break
			}
			if i >= len(data) || data[i] != '[' {
				return result, i, decode.NewParseErr("tags", i, scan.ErrBadArray)
			}
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			if i < len(data) && data[i] == ']' {
				if result.Tags == nil {
					result.Tags = []string{}
				}
			} else {
				if result.Tags == nil {
					result.Tags = make([]string, 0, ggenCap_CustomBothStruct_Tags_string)
				}
			}
			if i < len(data) && data[i] != ']' {
				for {
					result.Tags = append(result.Tags, "")
					if i >= len(data) || data[i] != '"' {
						return result, i, decode.NewParseErr("tags", i, scan.ErrExpectString)
					}
					ke := i + 1
					kew := ke + 32
					if kew > len(data) {
						kew = len(data)
					}
					for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
						ke++
					}
					if ke < len(data) && data[ke] == '"' {
						result.Tags[len(result.Tags)-1] = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.Tags[len(result.Tags)-1], i, err = scan.String(data, i, true)
						if err != nil {
							return result, i, decode.NewParseErr("tags", i, err)
						}
					}
					result.Tags[len(result.Tags)-1] = TrimSpace(result.Tags[len(result.Tags)-1])
					if err := NotBlank(result.Tags[len(result.Tags)-1]); err != nil {
						return result, i, &validation.CustomError{Pos: i, Path: []string{"tags[]"}, Name: "NotBlank", Value: result.Tags[len(result.Tags)-1], Cause: err}
					}
					for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i < len(data) && data[i] == ',' {
						i++
						for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i >= len(data) || data[i] == ']' {
							return result, i, decode.NewParseErr("tags", i, scan.ErrBadArray)
						}
						continue
					}
					break
				}
			}
			if i >= len(data) || data[i] != ']' {
				return result, i, decode.NewParseErr("tags", i, scan.ErrBadArray)
			}
			i++
		default:
			return result, i, &validation.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv CustomBothStruct) DecodeFromStream(s *scan.Stream) (result CustomBothStruct, err error) {
	result = recv
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	seenTags := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Offset(), scan.NotEOF(err, scan.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, decode.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "tags":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Offset(), err)
			}
			if seenTags {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"tags"}}
			}
			seenTags = true
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Offset(), err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("tags", s.Offset(), err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("tags", s.Offset(), err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("tags", s.Offset(), scan.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.Tags = nil
				break
			}
			err = s.ArrayOpen()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Offset(), err)
			}
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Offset(), err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("tags", s.Offset(), err)
				}
			}
			if s.Bytes()[s.Pos] == ']' {
				if result.Tags == nil {
					result.Tags = []string{}
				}
			} else {
				if result.Tags == nil {
					result.Tags = make([]string, 0, ggenCap_CustomBothStruct_Tags_string)
				}
			}
			for s.Bytes()[s.Pos] != ']' {
				result.Tags = append(result.Tags, "")
				result.Tags[len(result.Tags)-1], err = s.String(true)
				if err != nil {
					return result, decode.NewParseErr("tags", s.Offset(), err)
				}
				result.Tags[len(result.Tags)-1] = TrimSpace(result.Tags[len(result.Tags)-1])
				if err := NotBlank(result.Tags[len(result.Tags)-1]); err != nil {
					return result, &validation.CustomError{Pos: s.Offset(), Path: []string{"tags[]"}, Name: "NotBlank", Value: result.Tags[len(result.Tags)-1], Cause: err}
				}
				err = s.SkipSpace()
				if err != nil {
					return result, decode.NewParseErr("tags", s.Offset(), err)
				}
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, decode.NewParseErr("tags", s.Offset(), err)
					}
				}
				if s.Bytes()[s.Pos] == ',' {
					s.Pos++
					err = s.SkipSpace()
					if err != nil {
						return result, decode.NewParseErr("tags", s.Offset(), err)
					}
					if s.Pos >= len(s.Bytes()) || s.Bytes()[s.Pos] == ']' {
						return result, decode.NewParseErr("tags", s.Offset(), scan.ErrBadArray)
					}
					continue
				}
				break
			}
			if s.Bytes()[s.Pos] != ']' {
				return result, decode.NewParseErr("tags", s.Offset(), scan.ErrBadArray)
			}
			s.Pos++
		default:
			return result, &validation.UnknownKeyError{Pos: s.Offset(), Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Offset(), scan.NotEOF(err, scan.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Offset(), scan.ErrBadObject)
	}
}

func (s CustomBothStruct) JSONSize() int {
	size := 13
	if n := len(s.Tags); n > 0 {
		size += n - 1
	}
	for i0 := range s.Tags {
		size += len(s.Tags[i0])*2 + 2
	}
	return size
}

func (s CustomBothStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"tags\":"...)
	if s.Tags == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		if len(s.Tags) > 0 {
			dst = append(dst, '"')
			dst = encode.AppendStringNoHTML(dst, s.Tags[0])
			for _, v0 := range s.Tags[1:] {
				dst = append(dst, ",\""...)
				dst = encode.AppendStringNoHTML(dst, v0)
			}
		}
		dst = append(dst, ']')
	}
	return append(dst, '}'), nil
}
