// Code generated by ggen; DO NOT EDIT.

package integrationtests

import (
	"math"
	"strconv"
	"strings"
	"unsafe"

	"github.com/sirkostya009/ggen/decode/validation"
	"github.com/sirkostya009/ggen/encode"
	"github.com/sirkostya009/ggen/scan"
)

var ggenOneof0 = []string{"admin", "user", "guest"}

func (result MultiErrStruct) DecodeFrom(data []byte) (MultiErrStruct, int, error) {
	i := 0
	var err error
	_ = err
	var errs validation.Errors
	seenAge := false
	seenName := false
	seenRole := false
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, scan.ErrBadObject
	}
	i++
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		if !seenName {
			errs = append(errs, &validation.RequiredError{Field: "name"})
		}
		if len(errs) > 0 {
			return result, i, errs
		}
		return result, i + 1, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, scan.ErrExpectString
		}
		{
			ke := i + 1
			for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
				ke++
			}
			if ke >= len(data) {
				return result, i, scan.ErrUnterminated
			}
			if data[ke] < 0x20 {
				return result, i, scan.ErrBadString
			}
			if data[ke] == '"' {
				key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				key, i, err = scan.String(data, i)
				if err != nil {
					return result, i, err
				}
			}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, scan.ErrBadObject
		}
		i++
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch len(key) {
		case 3:
			if key == "age" {
				if seenAge {
					errs = append(errs, &validation.DuplicateKeyError{Field: "age"})
					i, err = scan.SkipValue(data, i)
					if err != nil {
						return result, i, err
					}
				} else {
					seenAge = true
					{
						neg := false
						if i < len(data) && data[i] == '-' {
							neg = true
							i++
						}
						if i >= len(data) || data[i] < '0' || data[i] > '9' {
							return result, i, scan.ErrBadNumber
						}
						limit := uint64(math.MaxInt64)
						if neg {
							limit = scan.SignedNeg
						}
						var u uint64
						for i < len(data) && data[i] >= '0' && data[i] <= '9' {
							d := uint64(data[i] - '0')
							if u > limit/10 || (u == limit/10 && d > limit%10) {
								return result, i, scan.ErrNumberOverflow
							}
							u = u*10 + d
							i++
						}
						if i < len(data) {
							c := data[i]
							if c == '.' || c == 'e' || c == 'E' {
								return result, i, scan.ErrBadNumber
							}
						}
						var n int64
						if neg {
							if u == scan.SignedNeg {
								n = math.MinInt64
							} else {
								n = -int64(u)
							}
						} else {
							n = int64(u)
						}
						result.Age = int(n)
					}
					if result.Age < 0 {
						errs = append(errs, &validation.GTEError{Field: "age", Limit: 0, Value: result.Age})
					}
					if result.Age > 100 {
						errs = append(errs, &validation.LTEError{Field: "age", Limit: 100, Value: result.Age})
					}
				}
			} else {
				errs = append(errs, &validation.UnknownKeyError{Field: key})
				i, err = scan.SkipValue(data, i)
				if err != nil {
					return result, i, err
				}
			}
		case 4:
			switch key {
			case "name":
				if seenName {
					errs = append(errs, &validation.DuplicateKeyError{Field: "name"})
					i, err = scan.SkipValue(data, i)
					if err != nil {
						return result, i, err
					}
				} else {
					seenName = true
					if i >= len(data) || data[i] != '"' {
						return result, i, scan.ErrExpectString
					}
					{
						ke := i + 1
						for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
							ke++
						}
						if ke >= len(data) {
							return result, i, scan.ErrUnterminated
						}
						if data[ke] < 0x20 {
							return result, i, scan.ErrBadString
						}
						if data[ke] == '"' {
							result.Name = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
							i = ke + 1
						} else {
							result.Name, i, err = scan.String(data, i)
							if err != nil {
								return result, i, err
							}
						}
					}
					if len(result.Name) < 1 {
						errs = append(errs, &validation.MinLenError{Field: "name", Limit: 1, Got: len(result.Name)})
					}
					if len(result.Name) > 5 {
						errs = append(errs, &validation.MaxLenError{Field: "name", Limit: 5, Got: len(result.Name)})
					}
				}
			case "role":
				if seenRole {
					errs = append(errs, &validation.DuplicateKeyError{Field: "role"})
					i, err = scan.SkipValue(data, i)
					if err != nil {
						return result, i, err
					}
				} else {
					seenRole = true
					if i >= len(data) || data[i] != '"' {
						return result, i, scan.ErrExpectString
					}
					{
						ke := i + 1
						for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
							ke++
						}
						if ke >= len(data) {
							return result, i, scan.ErrUnterminated
						}
						if data[ke] < 0x20 {
							return result, i, scan.ErrBadString
						}
						if data[ke] == '"' {
							result.Role = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
							i = ke + 1
						} else {
							result.Role, i, err = scan.String(data, i)
							if err != nil {
								return result, i, err
							}
						}
					}
					switch result.Role {
					case "admin", "user", "guest":
					default:
						errs = append(errs, &validation.OneOfError{Field: "role", Allowed: ggenOneof0, Value: result.Role})
					}
				}
			default:
				errs = append(errs, &validation.UnknownKeyError{Field: key})
				i, err = scan.SkipValue(data, i)
				if err != nil {
					return result, i, err
				}
			}
		default:
			errs = append(errs, &validation.UnknownKeyError{Field: key})
			i, err = scan.SkipValue(data, i)
			if err != nil {
				return result, i, err
			}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, scan.ErrBadObject
		}
		if data[i] == ',' {
			i++
			for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			if !seenName {
				errs = append(errs, &validation.RequiredError{Field: "name"})
			}
			if len(errs) > 0 {
				return result, i, errs
			}
			return result, i + 1, nil
		}
		return result, i, scan.ErrBadObject
	}
}

func (result MultiErrStruct) DecodeFromStream(s *scan.Stream) (MultiErrStruct, error) {
	var errs validation.Errors
	seenAge := false
	seenName := false
	seenRole := false
	err := s.ObjectOpen()
	if err != nil {
		return result, err
	}
	err = s.SkipSpace()
	if err != nil {
		return result, err
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, err
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		if !seenName {
			errs = append(errs, &validation.RequiredError{Field: "name"})
		}
		if len(errs) > 0 {
			return result, errs
		}
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, err
		}
		switch len(key) {
		case 3:
			if key == "age" {
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenAge {
					errs = append(errs, &validation.DuplicateKeyError{Field: "age"})
					err = s.SkipValue()
					if err != nil {
						return result, err
					}
				} else {
					seenAge = true
					var iv int64
					iv, err = s.Int64()
					if err != nil {
						return result, err
					}
					result.Age = int(iv)
					if result.Age < 0 {
						errs = append(errs, &validation.GTEError{Field: "age", Limit: 0, Value: result.Age})
					}
					if result.Age > 100 {
						errs = append(errs, &validation.LTEError{Field: "age", Limit: 100, Value: result.Age})
					}

				}
			} else {
				errs = append(errs, &validation.UnknownKeyError{Field: strings.Clone(key)})
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				err = s.SkipValue()
				if err != nil {
					return result, err
				}
			}
		case 4:
			switch key {
			case "name":
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenName {
					errs = append(errs, &validation.DuplicateKeyError{Field: "name"})
					err = s.SkipValue()
					if err != nil {
						return result, err
					}
				} else {
					seenName = true
					result.Name, err = s.String()
					if err != nil {
						return result, err
					}
					if len(result.Name) < 1 {
						errs = append(errs, &validation.MinLenError{Field: "name", Limit: 1, Got: len(result.Name)})
					}
					if len(result.Name) > 5 {
						errs = append(errs, &validation.MaxLenError{Field: "name", Limit: 5, Got: len(result.Name)})
					}

				}
			case "role":
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenRole {
					errs = append(errs, &validation.DuplicateKeyError{Field: "role"})
					err = s.SkipValue()
					if err != nil {
						return result, err
					}
				} else {
					seenRole = true
					result.Role, err = s.String()
					if err != nil {
						return result, err
					}
					switch result.Role {
					case "admin", "user", "guest":
					default:
						errs = append(errs, &validation.OneOfError{Field: "role", Allowed: ggenOneof0, Value: result.Role})
					}

				}
			default:
				errs = append(errs, &validation.UnknownKeyError{Field: strings.Clone(key)})
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				err = s.SkipValue()
				if err != nil {
					return result, err
				}
			}
		default:
			errs = append(errs, &validation.UnknownKeyError{Field: strings.Clone(key)})
			err = s.ConsumeColon()
			if err != nil {
				return result, err
			}
			err = s.SkipValue()
			if err != nil {
				return result, err
			}
		}
		err = s.SkipSpace()
		if err != nil {
			return result, err
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, err
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, err
			}
			continue
		}
		if c == '}' {
			if !seenName {
				errs = append(errs, &validation.RequiredError{Field: "name"})
			}
			if len(errs) > 0 {
				return result, errs
			}
			s.Pos++
			return result, nil
		}
		return result, scan.ErrBadObject
	}
}

func (s MultiErrStruct) JSONSize() int {
	size := 48
	size += len(s.Name) * 2
	size += len(s.Role) * 2
	return size
}

func (s MultiErrStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"age\":"...)
	dst = strconv.AppendInt(dst, int64(s.Age), 10)
	dst = append(dst, ",\"name\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Name)
	dst = append(dst, ",\"role\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Role)
	return append(dst, '}'), nil
}

func (result CustomBothStruct) DecodeFrom(data []byte) (CustomBothStruct, int, error) {
	i := 0
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	var err error
	_ = err
	seenTags := false
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, scan.ErrBadObject
	}
	i++
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		return result, i + 1, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, scan.ErrExpectString
		}
		{
			ke := i + 1
			for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
				ke++
			}
			if ke >= len(data) {
				return result, i, scan.ErrUnterminated
			}
			if data[ke] < 0x20 {
				return result, i, scan.ErrBadString
			}
			if data[ke] == '"' {
				key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				key, i, err = scan.String(data, i)
				if err != nil {
					return result, i, err
				}
			}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, scan.ErrBadObject
		}
		i++
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch len(key) {
		case 4:
			if key == "tags" {
				if seenTags {
					return result, i, &validation.DuplicateKeyError{Field: "tags"}
				}
				seenTags = true
				{
					for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
						i += 4
						result.Tags = nil
					} else {
						if i >= len(data) || data[i] != '[' {
							return result, i, scan.ErrBadArray
						}
						i++
						for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i < len(data) && data[i] == ']' {
							if result.Tags == nil {
								result.Tags = []string{}
							}
						} else {
							if result.Tags == nil {
								result.Tags = make([]string, 0, 4)
							}
						}
						for i < len(data) && data[i] != ']' {
							result.Tags = append(result.Tags, "")
							if i >= len(data) || data[i] != '"' {
								return result, i, scan.ErrExpectString
							}
							{
								ke := i + 1
								for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
									ke++
								}
								if ke >= len(data) {
									return result, i, scan.ErrUnterminated
								}
								if data[ke] < 0x20 {
									return result, i, scan.ErrBadString
								}
								if data[ke] == '"' {
									result.Tags[len(result.Tags)-1] = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
									i = ke + 1
								} else {
									result.Tags[len(result.Tags)-1], i, err = scan.String(data, i)
									if err != nil {
										return result, i, err
									}
								}
							}
							result.Tags[len(result.Tags)-1] = TrimSpace(result.Tags[len(result.Tags)-1])
							if err := NotBlank(result.Tags[len(result.Tags)-1]); err != nil {
								return result, i, &validation.CustomError{Field: "tags[]", Name: "@NotBlank", Cause: err}
							}
							for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
								i++
							}
							if i < len(data) && data[i] == ',' {
								i++
								for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
									i++
								}
								continue
							}
							break
						}
						if i >= len(data) || data[i] != ']' {
							return result, i, scan.ErrBadArray
						}
						i++
					}
				}
			} else {
				return result, i, &validation.UnknownKeyError{Field: key}
			}
		default:
			return result, i, &validation.UnknownKeyError{Field: key}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, scan.ErrBadObject
		}
		if data[i] == ',' {
			i++
			for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			return result, i + 1, nil
		}
		return result, i, scan.ErrBadObject
	}
}

func (result CustomBothStruct) DecodeFromStream(s *scan.Stream) (CustomBothStruct, error) {
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	seenTags := false
	err := s.ObjectOpen()
	if err != nil {
		return result, err
	}
	err = s.SkipSpace()
	if err != nil {
		return result, err
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, err
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, err
		}
		switch len(key) {
		case 4:
			if key == "tags" {
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenTags {
					return result, &validation.DuplicateKeyError{Field: "tags"}
				}
				seenTags = true
				{
					err = s.SkipSpace()
					if err != nil {
						return result, err
					}
					if s.Pos >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, err
						}
					}
					if s.Bytes()[s.Pos] == 'n' {
						for ki := 1; ki < 4; ki++ {
							if s.Pos+ki >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos+ki] != "null"[ki] {
								return result, scan.ErrBadLiteral
							}
						}
						s.Pos += 4
						result.Tags = nil
					} else {
						err = s.ArrayOpen()
						if err != nil {
							return result, err
						}
						err = s.SkipSpace()
						if err != nil {
							return result, err
						}
						if s.Pos >= len(s.Bytes()) {
							if err = s.ReadMore(0); err != nil {
								return result, err
							}
						}
						if s.Bytes()[s.Pos] == ']' {
							if result.Tags == nil {
								result.Tags = []string{}
							}
						} else {
							if result.Tags == nil {
								result.Tags = make([]string, 0, 4)
							}
						}
						for s.Bytes()[s.Pos] != ']' {
							result.Tags = append(result.Tags, "")
							result.Tags[len(result.Tags)-1], err = s.String()
							if err != nil {
								return result, err
							}
							result.Tags[len(result.Tags)-1] = TrimSpace(result.Tags[len(result.Tags)-1])
							if err := NotBlank(result.Tags[len(result.Tags)-1]); err != nil {
								return result, &validation.CustomError{Field: "tags[]", Name: "@NotBlank", Cause: err}
							}
							err = s.SkipSpace()
							if err != nil {
								return result, err
							}
							if s.Pos >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos] == ',' {
								s.Pos++
								err = s.SkipSpace()
								if err != nil {
									return result, err
								}
								continue
							}
							break
						}
						if s.Bytes()[s.Pos] != ']' {
							return result, scan.ErrBadArray
						}
						s.Pos++
					}
				}
			} else {
				return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
			}
		default:
			return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
		}
		err = s.SkipSpace()
		if err != nil {
			return result, err
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, err
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, err
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, scan.ErrBadObject
	}
}

func (s CustomBothStruct) JSONSize() int {
	size := 13
	if n := len(s.Tags); n > 0 {
		size += n - 1
	}
	for i0 := range s.Tags {
		size += len(s.Tags[i0])*2 + 2
	}
	return size
}

func (s CustomBothStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"tags\":"...)
	if s.Tags == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		if len(s.Tags) > 0 {
			dst = append(dst, '"')
			dst = encode.AppendStringNoHTML(dst, s.Tags[0])
			for _, v0 := range s.Tags[1:] {
				dst = append(dst, ",\""...)
				dst = encode.AppendStringNoHTML(dst, v0)
			}
		}
		dst = append(dst, ']')
	}
	return append(dst, '}'), nil
}
