// Code generated by ggen; DO NOT EDIT.

//go:build goexperiment.jsonv2

package integrationtests

import (
	"math"
	"strconv"
	"strings"
	"unsafe"

	"github.com/sirkostya009/ggen/decode"
	"github.com/sirkostya009/ggen/encode"
	"github.com/sirkostya009/ggen/scan"
	"github.com/sirkostya009/ggen/validation"
)

func (recv AllowDupsStruct) DecodeFrom(data []byte) (result AllowDupsStruct, i int, err error) {
	result = recv
	seenN := false
	seenName := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenName {
			return result, i, &validation.RequiredError{Pos: i, Path: []string{"name"}}
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "n":
			if seenN {
				i, err = scan.SkipValue(data, i)
				if err != nil {
					return result, i, decode.NewParseErr("n", i, err)
				}
			} else {
				seenN = true
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, decode.NewParseErr("n", i, scan.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = scan.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, decode.NewParseErr("n", i, scan.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, decode.NewParseErr("n", i, scan.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == scan.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				result.N = int(n)
				if result.N < 0 {
					return result, i, &validation.GTEError{Pos: i, Path: []string{"n"}, Limit: 0, Value: result.N}
				}
				if result.N > 100 {
					return result, i, &validation.LTEError{Pos: i, Path: []string{"n"}, Limit: 100, Value: result.N}
				}
			}
		case "name":
			if seenName {
				i, err = scan.SkipValue(data, i)
				if err != nil {
					return result, i, decode.NewParseErr("name", i, err)
				}
			} else {
				seenName = true
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("name", i, scan.ErrExpectString)
				}
				ke := i + 1
				for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
					ke++
				}
				if ke >= len(data) {
					return result, i, decode.NewParseErr("name", i, scan.ErrUnterminated)
				}
				if data[ke] < 0x20 {
					return result, i, decode.NewParseErr("name", i, scan.ErrBadString)
				}
				if data[ke] == '"' {
					result.Name = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
					i = ke + 1
				} else {
					result.Name, i, err = scan.String(data, i)
					if err != nil {
						return result, i, decode.NewParseErr("name", i, err)
					}
				}
				if len(result.Name) < 1 {
					return result, i, &validation.MinLenError{Pos: i, Path: []string{"name"}, Limit: 1, Got: len(result.Name)}
				}
				if len(result.Name) > 20 {
					return result, i, &validation.MaxLenError{Pos: i, Path: []string{"name"}, Limit: 20, Got: len(result.Name)}
				}
			}
		default:
			return result, i, &validation.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenName {
				return result, i, &validation.RequiredError{Pos: i, Path: []string{"name"}}
			}
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv AllowDupsStruct) DecodeFromStream(s *scan.Stream) (result AllowDupsStruct, err error) {
	result = recv
	seenN := false
	seenName := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenName {
			return result, &validation.RequiredError{Pos: s.Offset(), Path: []string{"name"}}
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "n":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("n", s.Pos, err)
			}
			if seenN {
				err = s.SkipValue()
				if err != nil {
					return result, decode.NewParseErr("n", s.Pos, err)
				}
			} else {
				seenN = true
				var iv int64
				iv, err = s.Int64()
				if err != nil {
					return result, decode.NewParseErr("n", s.Pos, err)
				}
				result.N = int(iv)
				if result.N < 0 {
					return result, &validation.GTEError{Pos: s.Offset(), Path: []string{"n"}, Limit: 0, Value: result.N}
				}
				if result.N > 100 {
					return result, &validation.LTEError{Pos: s.Offset(), Path: []string{"n"}, Limit: 100, Value: result.N}
				}

			}
		case "name":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("name", s.Pos, err)
			}
			if seenName {
				err = s.SkipValue()
				if err != nil {
					return result, decode.NewParseErr("name", s.Pos, err)
				}
			} else {
				seenName = true
				result.Name, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("name", s.Pos, err)
				}
				if len(result.Name) < 1 {
					return result, &validation.MinLenError{Pos: s.Offset(), Path: []string{"name"}, Limit: 1, Got: len(result.Name)}
				}
				if len(result.Name) > 20 {
					return result, &validation.MaxLenError{Pos: s.Offset(), Path: []string{"name"}, Limit: 20, Got: len(result.Name)}
				}

			}
		default:
			return result, &validation.UnknownKeyError{Pos: s.Offset(), Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenName {
				return result, &validation.RequiredError{Pos: s.Offset(), Path: []string{"name"}}
			}
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s AllowDupsStruct) JSONSize() int {
	size := 36
	size += len(s.Name) * 2
	return size
}

func (s AllowDupsStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"n\":"...)
	dst = strconv.AppendInt(dst, int64(s.N), 10)
	dst = append(dst, ",\"name\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Name)
	return append(dst, '}'), nil
}
