// Code generated by ggen; DO NOT EDIT.

package integrationtests

import (
	"bytes"
	"math"
	"strconv"
	"strings"
	"unicode/utf8"
	"unsafe"

	"github.com/sirkostya009/ggen/decode"
	"github.com/sirkostya009/ggen/decode/validation"
	"github.com/sirkostya009/ggen/encode"
	"github.com/sirkostya009/ggen/scan"
)

func (recv DiveStruct) DecodeFrom(data []byte) (result DiveStruct, i int, err error) {
	result = recv
	if result.Scores != nil {
		result.Scores = result.Scores[:0]
	}
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	seenCount := false
	seenScores := false
	seenTags := false
	seenTitle := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "count":
			if seenCount {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"count"}}
			}
			seenCount = true
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, decode.NewParseErr("count", i, scan.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = scan.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, decode.NewParseErr("count", i, scan.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, decode.NewParseErr("count", i, scan.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == scan.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			result.Count = int(n)
			if err := EvenOnly(result.Count); err != nil {
				return result, i, &validation.CustomError{Pos: i, Path: []string{"count"}, Name: "EvenOnly", Value: result.Count, Cause: err}
			}
		case "scores":
			if seenScores {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"scores"}}
			}
			seenScores = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				i += 4
				result.Scores = nil
				break
			}
			if i >= len(data) || data[i] != '[' {
				return result, i, scan.ErrBadArray
			}
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			if i < len(data) && data[i] == ']' {
				if result.Scores == nil {
					result.Scores = []int{}
				}
			} else {
				if result.Scores == nil {
					cnt0 := 1
					if e := bytes.IndexByte(data[i:], ']'); e >= 0 {
						cnt0 = bytes.Count(data[i:i+e], []byte{','}) + 1
					}
					result.Scores = make([]int, 0, cnt0)
				}
			}
			if i < len(data) && data[i] != ']' {
				for {
					result.Scores = append(result.Scores, 0)
					neg := false
					if i < len(data) && data[i] == '-' {
						neg = true
						i++
					}
					if i >= len(data) || data[i] < '0' || data[i] > '9' {
						return result, i, decode.NewParseErr("scores", i, scan.ErrBadNumber)
					}
					limit := uint64(math.MaxInt64)
					if neg {
						limit = scan.SignedNeg
					}
					var u uint64
					de := i + 18
					if de > len(data) {
						de = len(data)
					}
					for i < de && data[i] >= '0' && data[i] <= '9' {
						u = u*10 + uint64(data[i]-'0')
						i++
					}
					for i < len(data) && data[i] >= '0' && data[i] <= '9' {
						d := uint64(data[i] - '0')
						if u > limit/10 || (u == limit/10 && d > limit%10) {
							return result, i, decode.NewParseErr("scores", i, scan.ErrNumberOverflow)
						}
						u = u*10 + d
						i++
					}
					if i < len(data) {
						c := data[i]
						if c == '.' || c == 'e' || c == 'E' {
							return result, i, decode.NewParseErr("scores", i, scan.ErrBadNumber)
						}
					}
					var n int64
					if neg {
						if u == scan.SignedNeg {
							n = math.MinInt64
						} else {
							n = -int64(u)
						}
					} else {
						n = int64(u)
					}
					result.Scores[len(result.Scores)-1] = int(n)
					if result.Scores[len(result.Scores)-1] < 0 {
						return result, i, &validation.GTEError{Pos: i, Path: []string{"scores[]"}, Limit: 0, Value: result.Scores[len(result.Scores)-1]}
					}
					if result.Scores[len(result.Scores)-1] > 100 {
						return result, i, &validation.LTEError{Pos: i, Path: []string{"scores[]"}, Limit: 100, Value: result.Scores[len(result.Scores)-1]}
					}
					for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i < len(data) && data[i] == ',' {
						i++
						for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i >= len(data) || data[i] == ']' {
							return result, i, scan.ErrBadArray
						}
						continue
					}
					break
				}
			}
			if i >= len(data) || data[i] != ']' {
				return result, i, scan.ErrBadArray
			}
			i++
		case "tags":
			if seenTags {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"tags"}}
			}
			seenTags = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				i += 4
				result.Tags = nil
			} else {
				if i >= len(data) || data[i] != '[' {
					return result, i, scan.ErrBadArray
				}
				i++
				for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
					i++
				}
				if i < len(data) && data[i] == ']' {
					if result.Tags == nil {
						result.Tags = []string{}
					}
				} else {
					if result.Tags == nil {
						result.Tags = make([]string, 0, 1)
					}
				}
				if i < len(data) && data[i] != ']' {
					for {
						result.Tags = append(result.Tags, "")
						if i >= len(data) || data[i] != '"' {
							return result, i, decode.NewParseErr("tags", i, scan.ErrExpectString)
						}
						ke := i + 1
						for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
							ke++
						}
						if ke >= len(data) {
							return result, i, decode.NewParseErr("tags", i, scan.ErrUnterminated)
						}
						if data[ke] < 0x20 {
							return result, i, decode.NewParseErr("tags", i, scan.ErrBadString)
						}
						if data[ke] == '"' {
							result.Tags[len(result.Tags)-1] = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
							i = ke + 1
						} else {
							result.Tags[len(result.Tags)-1], i, err = scan.String(data, i)
							if err != nil {
								return result, i, decode.NewParseErr("tags", i, err)
							}
						}
						if len(result.Tags[len(result.Tags)-1]) < 2 {
							return result, i, &validation.MinRunesError{Pos: i, Path: []string{"tags[]"}, Limit: 2, Got: utf8.RuneCountInString(result.Tags[len(result.Tags)-1])}
						} else if len(result.Tags[len(result.Tags)-1]) < 5 {
							if rc := utf8.RuneCountInString(result.Tags[len(result.Tags)-1]); rc < 2 {
								return result, i, &validation.MinRunesError{Pos: i, Path: []string{"tags[]"}, Limit: 2, Got: rc}
							}
						}
						if len(result.Tags[len(result.Tags)-1]) > 40 {
							return result, i, &validation.MaxRunesError{Pos: i, Path: []string{"tags[]"}, Limit: 10, Got: utf8.RuneCountInString(result.Tags[len(result.Tags)-1])}
						} else if len(result.Tags[len(result.Tags)-1]) > 10 {
							if rc := utf8.RuneCountInString(result.Tags[len(result.Tags)-1]); rc > 10 {
								return result, i, &validation.MaxRunesError{Pos: i, Path: []string{"tags[]"}, Limit: 10, Got: rc}
							}
						}
						for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i < len(data) && data[i] == ',' {
							i++
							for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
								i++
							}
							if i >= len(data) || data[i] == ']' {
								return result, i, scan.ErrBadArray
							}
							continue
						}
						break
					}
				}
				if i >= len(data) || data[i] != ']' {
					return result, i, scan.ErrBadArray
				}
				i++
			}
			if len(result.Tags) < 1 {
				return result, i, &validation.MinLenError{Pos: i, Path: []string{"tags"}, Limit: 1, Got: len(result.Tags)}
			}
			if len(result.Tags) > 3 {
				return result, i, &validation.MaxLenError{Pos: i, Path: []string{"tags"}, Limit: 3, Got: len(result.Tags)}
			}
		case "title":
			if seenTitle {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"title"}}
			}
			seenTitle = true
			if i >= len(data) || data[i] != '"' {
				return result, i, decode.NewParseErr("title", i, scan.ErrExpectString)
			}
			ke := i + 1
			for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
				ke++
			}
			if ke >= len(data) {
				return result, i, decode.NewParseErr("title", i, scan.ErrUnterminated)
			}
			if data[ke] < 0x20 {
				return result, i, decode.NewParseErr("title", i, scan.ErrBadString)
			}
			if data[ke] == '"' {
				result.Title = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Title, i, err = scan.String(data, i)
				if err != nil {
					return result, i, decode.NewParseErr("title", i, err)
				}
			}
			if len(result.Title) < 1 {
				return result, i, &validation.MinRunesError{Pos: i, Path: []string{"title"}, Limit: 1, Got: utf8.RuneCountInString(result.Title)}
			}
			if len(result.Title) > 20 {
				return result, i, &validation.MaxRunesError{Pos: i, Path: []string{"title"}, Limit: 5, Got: utf8.RuneCountInString(result.Title)}
			} else if len(result.Title) > 5 {
				if rc := utf8.RuneCountInString(result.Title); rc > 5 {
					return result, i, &validation.MaxRunesError{Pos: i, Path: []string{"title"}, Limit: 5, Got: rc}
				}
			}
		default:
			return result, i, &validation.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv DiveStruct) DecodeFromStream(s *scan.Stream) (result DiveStruct, err error) {
	result = recv
	if result.Scores != nil {
		result.Scores = result.Scores[:0]
	}
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	seenCount := false
	seenScores := false
	seenTags := false
	seenTitle := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "count":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("count", s.Pos, err)
			}
			if seenCount {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"count"}}
			}
			seenCount = true
			var iv int64
			iv, err = s.Int64()
			if err != nil {
				return result, decode.NewParseErr("count", s.Pos, err)
			}
			result.Count = int(iv)
			if err := EvenOnly(result.Count); err != nil {
				return result, &validation.CustomError{Pos: s.Offset(), Path: []string{"count"}, Name: "EvenOnly", Value: result.Count, Cause: err}
			}
		case "scores":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("scores", s.Pos, err)
			}
			if seenScores {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"scores"}}
			}
			seenScores = true
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("scores", s.Pos, err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("scores", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("scores", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("scores", s.Pos, scan.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.Scores = nil
				break
			}
			err = s.ArrayOpen()
			if err != nil {
				return result, decode.NewParseErr("scores", s.Pos, err)
			}
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("scores", s.Pos, err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("scores", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == ']' {
				if result.Scores == nil {
					result.Scores = []int{}
				}
			} else {
				if result.Scores == nil {
					result.Scores = make([]int, 0, 4)
				}
			}
			for s.Bytes()[s.Pos] != ']' {
				result.Scores = append(result.Scores, 0)
				var iv int64
				iv, err = s.Int64()
				if err != nil {
					return result, decode.NewParseErr("scores", s.Pos, err)
				}
				result.Scores[len(result.Scores)-1] = int(iv)
				if result.Scores[len(result.Scores)-1] < 0 {
					return result, &validation.GTEError{Pos: s.Offset(), Path: []string{"scores[]"}, Limit: 0, Value: result.Scores[len(result.Scores)-1]}
				}
				if result.Scores[len(result.Scores)-1] > 100 {
					return result, &validation.LTEError{Pos: s.Offset(), Path: []string{"scores[]"}, Limit: 100, Value: result.Scores[len(result.Scores)-1]}
				}
				err = s.SkipSpace()
				if err != nil {
					return result, decode.NewParseErr("scores", s.Pos, err)
				}
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, decode.NewParseErr("scores", s.Pos, err)
					}
				}
				if s.Bytes()[s.Pos] == ',' {
					s.Pos++
					err = s.SkipSpace()
					if err != nil {
						return result, decode.NewParseErr("scores", s.Pos, err)
					}
					if s.Pos >= len(s.Bytes()) || s.Bytes()[s.Pos] == ']' {
						return result, decode.NewParseErr("scores", s.Pos, scan.ErrBadArray)
					}
					continue
				}
				break
			}
			if s.Bytes()[s.Pos] != ']' {
				return result, decode.NewParseErr("scores", s.Pos, scan.ErrBadArray)
			}
			s.Pos++
		case "tags":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Pos, err)
			}
			if seenTags {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"tags"}}
			}
			seenTags = true
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Pos, err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("tags", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("tags", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("tags", s.Pos, scan.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.Tags = nil
			} else {
				err = s.ArrayOpen()
				if err != nil {
					return result, decode.NewParseErr("tags", s.Pos, err)
				}
				err = s.SkipSpace()
				if err != nil {
					return result, decode.NewParseErr("tags", s.Pos, err)
				}
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, decode.NewParseErr("tags", s.Pos, err)
					}
				}
				if s.Bytes()[s.Pos] == ']' {
					if result.Tags == nil {
						result.Tags = []string{}
					}
				} else {
					if result.Tags == nil {
						result.Tags = make([]string, 0, 1)
					}
				}
				for s.Bytes()[s.Pos] != ']' {
					result.Tags = append(result.Tags, "")
					result.Tags[len(result.Tags)-1], err = s.String()
					if err != nil {
						return result, decode.NewParseErr("tags", s.Pos, err)
					}
					if len(result.Tags[len(result.Tags)-1]) < 2 {
						return result, &validation.MinRunesError{Pos: s.Offset(), Path: []string{"tags[]"}, Limit: 2, Got: utf8.RuneCountInString(result.Tags[len(result.Tags)-1])}
					} else if len(result.Tags[len(result.Tags)-1]) < 5 {
						if rc := utf8.RuneCountInString(result.Tags[len(result.Tags)-1]); rc < 2 {
							return result, &validation.MinRunesError{Pos: s.Offset(), Path: []string{"tags[]"}, Limit: 2, Got: rc}
						}
					}
					if len(result.Tags[len(result.Tags)-1]) > 40 {
						return result, &validation.MaxRunesError{Pos: s.Offset(), Path: []string{"tags[]"}, Limit: 10, Got: utf8.RuneCountInString(result.Tags[len(result.Tags)-1])}
					} else if len(result.Tags[len(result.Tags)-1]) > 10 {
						if rc := utf8.RuneCountInString(result.Tags[len(result.Tags)-1]); rc > 10 {
							return result, &validation.MaxRunesError{Pos: s.Offset(), Path: []string{"tags[]"}, Limit: 10, Got: rc}
						}
					}
					err = s.SkipSpace()
					if err != nil {
						return result, decode.NewParseErr("tags", s.Pos, err)
					}
					if s.Pos >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("tags", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos] == ',' {
						s.Pos++
						err = s.SkipSpace()
						if err != nil {
							return result, decode.NewParseErr("tags", s.Pos, err)
						}
						if s.Pos >= len(s.Bytes()) || s.Bytes()[s.Pos] == ']' {
							return result, decode.NewParseErr("tags", s.Pos, scan.ErrBadArray)
						}
						continue
					}
					break
				}
				if s.Bytes()[s.Pos] != ']' {
					return result, decode.NewParseErr("tags", s.Pos, scan.ErrBadArray)
				}
				s.Pos++
			}
			if len(result.Tags) < 1 {
				return result, &validation.MinLenError{Pos: s.Offset(), Path: []string{"tags"}, Limit: 1, Got: len(result.Tags)}
			}
			if len(result.Tags) > 3 {
				return result, &validation.MaxLenError{Pos: s.Offset(), Path: []string{"tags"}, Limit: 3, Got: len(result.Tags)}
			}
		case "title":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("title", s.Pos, err)
			}
			if seenTitle {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"title"}}
			}
			seenTitle = true
			result.Title, err = s.String()
			if err != nil {
				return result, decode.NewParseErr("title", s.Pos, err)
			}
			if len(result.Title) < 1 {
				return result, &validation.MinRunesError{Pos: s.Offset(), Path: []string{"title"}, Limit: 1, Got: utf8.RuneCountInString(result.Title)}
			}
			if len(result.Title) > 20 {
				return result, &validation.MaxRunesError{Pos: s.Offset(), Path: []string{"title"}, Limit: 5, Got: utf8.RuneCountInString(result.Title)}
			} else if len(result.Title) > 5 {
				if rc := utf8.RuneCountInString(result.Title); rc > 5 {
					return result, &validation.MaxRunesError{Pos: s.Offset(), Path: []string{"title"}, Limit: 5, Got: rc}
				}
			}
		default:
			return result, &validation.UnknownKeyError{Pos: s.Offset(), Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s DiveStruct) JSONSize() int {
	size := 67
	if n := len(s.Scores); n > 0 {
		size += n - 1
	}
	size += len(s.Scores) * 20
	if n := len(s.Tags); n > 0 {
		size += n - 1
	}
	for i0 := range s.Tags {
		size += len(s.Tags[i0])*2 + 2
	}
	size += len(s.Title) * 2
	return size
}

func (s DiveStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"count\":"...)
	dst = strconv.AppendInt(dst, int64(s.Count), 10)
	dst = append(dst, ",\"scores\":"...)
	if s.Scores == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		if len(s.Scores) > 0 {
			dst = strconv.AppendInt(dst, int64(s.Scores[0]), 10)
			for _, v0 := range s.Scores[1:] {
				dst = append(dst, ',')
				dst = strconv.AppendInt(dst, int64(v0), 10)
			}
		}
		dst = append(dst, ']')
	}
	dst = append(dst, ",\"tags\":"...)
	if s.Tags == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		if len(s.Tags) > 0 {
			dst = append(dst, '"')
			dst = encode.AppendStringNoHTML(dst, s.Tags[0])
			for _, v0 := range s.Tags[1:] {
				dst = append(dst, ",\""...)
				dst = encode.AppendStringNoHTML(dst, v0)
			}
		}
		dst = append(dst, ']')
	}
	dst = append(dst, ",\"title\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Title)
	return append(dst, '}'), nil
}

func (recv CustomDiveStruct) DecodeFrom(data []byte) (result CustomDiveStruct, i int, err error) {
	result = recv
	if result.Lookup != nil {
		clear(result.Lookup)
	}
	if result.Mixed != nil {
		clear(result.Mixed)
	}
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	if result.Trim != nil {
		result.Trim = result.Trim[:0]
	}
	seenLookup := false
	seenMixed := false
	seenPtr := false
	seenTags := false
	seenTrim := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "lookup":
			if seenLookup {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"lookup"}}
			}
			seenLookup = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				i += 4
				result.Lookup = nil
				break
			}
			if i >= len(data) || data[i] != '{' {
				return result, i, decode.NewParseErr("lookup", i, scan.ErrBadObject)
			}
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			if i < len(data) && data[i] == '}' {
				if result.Lookup == nil {
					result.Lookup = map[string]int{}
				}
			} else {
				if result.Lookup == nil {
					result.Lookup = make(map[string]int)
				}
			}
			if i < len(data) && data[i] != '}' {
				for {
					var mk string
					if i >= len(data) || data[i] != '"' {
						return result, i, decode.NewParseErr("lookup", i, scan.ErrExpectString)
					}
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("lookup", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("lookup", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						mk = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						mk, i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("lookup", i, err)
						}
					}
					if err := KeyShape(mk); err != nil {
						return result, i, &validation.CustomError{Pos: i, Path: []string{"lookup.key"}, Name: "KeyShape", Value: mk, Cause: err}
					}
					for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i >= len(data) || data[i] != ':' {
						return result, i, decode.NewParseErr("lookup", i, scan.ErrBadObject)
					}
					i++
					for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					neg := false
					if i < len(data) && data[i] == '-' {
						neg = true
						i++
					}
					if i >= len(data) || data[i] < '0' || data[i] > '9' {
						return result, i, decode.NewParseErr("lookup", i, scan.ErrBadNumber)
					}
					limit := uint64(math.MaxInt64)
					if neg {
						limit = scan.SignedNeg
					}
					var u uint64
					de := i + 18
					if de > len(data) {
						de = len(data)
					}
					for i < de && data[i] >= '0' && data[i] <= '9' {
						u = u*10 + uint64(data[i]-'0')
						i++
					}
					for i < len(data) && data[i] >= '0' && data[i] <= '9' {
						d := uint64(data[i] - '0')
						if u > limit/10 || (u == limit/10 && d > limit%10) {
							return result, i, decode.NewParseErr("lookup", i, scan.ErrNumberOverflow)
						}
						u = u*10 + d
						i++
					}
					if i < len(data) {
						c := data[i]
						if c == '.' || c == 'e' || c == 'E' {
							return result, i, decode.NewParseErr("lookup", i, scan.ErrBadNumber)
						}
					}
					var n int64
					if neg {
						if u == scan.SignedNeg {
							n = math.MinInt64
						} else {
							n = -int64(u)
						}
					} else {
						n = int64(u)
					}
					result.Lookup[mk] = int(n)
					for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i < len(data) && data[i] == ',' {
						i++
						for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i >= len(data) || data[i] == '}' {
							return result, i, scan.ErrBadObject
						}
						continue
					}
					break
				}
			}
			if i >= len(data) || data[i] != '}' {
				return result, i, decode.NewParseErr("lookup", i, scan.ErrBadObject)
			}
			i++
		case "mixed":
			if seenMixed {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"mixed"}}
			}
			seenMixed = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				i += 4
				result.Mixed = nil
				break
			}
			if i >= len(data) || data[i] != '{' {
				return result, i, decode.NewParseErr("mixed", i, scan.ErrBadObject)
			}
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			if i < len(data) && data[i] == '}' {
				if result.Mixed == nil {
					result.Mixed = map[string]int{}
				}
			} else {
				if result.Mixed == nil {
					result.Mixed = make(map[string]int)
				}
			}
			if i < len(data) && data[i] != '}' {
				for {
					var mk string
					if i >= len(data) || data[i] != '"' {
						return result, i, decode.NewParseErr("mixed", i, scan.ErrExpectString)
					}
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("mixed", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("mixed", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						mk = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						mk, i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("mixed", i, err)
						}
					}
					mk = LowerKey(mk)
					for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i >= len(data) || data[i] != ':' {
						return result, i, decode.NewParseErr("mixed", i, scan.ErrBadObject)
					}
					i++
					for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					neg := false
					if i < len(data) && data[i] == '-' {
						neg = true
						i++
					}
					if i >= len(data) || data[i] < '0' || data[i] > '9' {
						return result, i, decode.NewParseErr("mixed", i, scan.ErrBadNumber)
					}
					limit := uint64(math.MaxInt64)
					if neg {
						limit = scan.SignedNeg
					}
					var u uint64
					de := i + 18
					if de > len(data) {
						de = len(data)
					}
					for i < de && data[i] >= '0' && data[i] <= '9' {
						u = u*10 + uint64(data[i]-'0')
						i++
					}
					for i < len(data) && data[i] >= '0' && data[i] <= '9' {
						d := uint64(data[i] - '0')
						if u > limit/10 || (u == limit/10 && d > limit%10) {
							return result, i, decode.NewParseErr("mixed", i, scan.ErrNumberOverflow)
						}
						u = u*10 + d
						i++
					}
					if i < len(data) {
						c := data[i]
						if c == '.' || c == 'e' || c == 'E' {
							return result, i, decode.NewParseErr("mixed", i, scan.ErrBadNumber)
						}
					}
					var n int64
					if neg {
						if u == scan.SignedNeg {
							n = math.MinInt64
						} else {
							n = -int64(u)
						}
					} else {
						n = int64(u)
					}
					result.Mixed[mk] = int(n)
					for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i < len(data) && data[i] == ',' {
						i++
						for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i >= len(data) || data[i] == '}' {
							return result, i, scan.ErrBadObject
						}
						continue
					}
					break
				}
			}
			if i >= len(data) || data[i] != '}' {
				return result, i, decode.NewParseErr("mixed", i, scan.ErrBadObject)
			}
			i++
		case "ptr":
			if seenPtr {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"ptr"}}
			}
			seenPtr = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				i += 4
				result.Ptr = nil
			} else {
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, decode.NewParseErr("ptr", i, scan.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = scan.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, decode.NewParseErr("ptr", i, scan.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, decode.NewParseErr("ptr", i, scan.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == scan.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				if result.Ptr == nil {
					result.Ptr = new(int(n))
				} else {
					(*result.Ptr) = int(n)
				}
			}
			if err := PointerCheck(result.Ptr); err != nil {
				return result, i, &validation.CustomError{Pos: i, Path: []string{"ptr"}, Name: "PointerCheck", Value: result.Ptr, Cause: err}
			}
		case "tags":
			if seenTags {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"tags"}}
			}
			seenTags = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				i += 4
				result.Tags = nil
				break
			}
			if i >= len(data) || data[i] != '[' {
				return result, i, scan.ErrBadArray
			}
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			if i < len(data) && data[i] == ']' {
				if result.Tags == nil {
					result.Tags = []string{}
				}
			} else {
				if result.Tags == nil {
					result.Tags = make([]string, 0, 4)
				}
			}
			if i < len(data) && data[i] != ']' {
				for {
					result.Tags = append(result.Tags, "")
					if i >= len(data) || data[i] != '"' {
						return result, i, decode.NewParseErr("tags", i, scan.ErrExpectString)
					}
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("tags", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("tags", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						result.Tags[len(result.Tags)-1] = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.Tags[len(result.Tags)-1], i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("tags", i, err)
						}
					}
					if err := NotBlank(result.Tags[len(result.Tags)-1]); err != nil {
						return result, i, &validation.CustomError{Pos: i, Path: []string{"tags[]"}, Name: "NotBlank", Value: result.Tags[len(result.Tags)-1], Cause: err}
					}
					for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i < len(data) && data[i] == ',' {
						i++
						for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i >= len(data) || data[i] == ']' {
							return result, i, scan.ErrBadArray
						}
						continue
					}
					break
				}
			}
			if i >= len(data) || data[i] != ']' {
				return result, i, scan.ErrBadArray
			}
			i++
		case "trim":
			if seenTrim {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"trim"}}
			}
			seenTrim = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				i += 4
				result.Trim = nil
				break
			}
			if i >= len(data) || data[i] != '[' {
				return result, i, scan.ErrBadArray
			}
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			if i < len(data) && data[i] == ']' {
				if result.Trim == nil {
					result.Trim = []string{}
				}
			} else {
				if result.Trim == nil {
					result.Trim = make([]string, 0, 4)
				}
			}
			if i < len(data) && data[i] != ']' {
				for {
					result.Trim = append(result.Trim, "")
					if i >= len(data) || data[i] != '"' {
						return result, i, decode.NewParseErr("trim", i, scan.ErrExpectString)
					}
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("trim", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("trim", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						result.Trim[len(result.Trim)-1] = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.Trim[len(result.Trim)-1], i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("trim", i, err)
						}
					}
					result.Trim[len(result.Trim)-1] = TrimSpace(result.Trim[len(result.Trim)-1])
					for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i < len(data) && data[i] == ',' {
						i++
						for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i >= len(data) || data[i] == ']' {
							return result, i, scan.ErrBadArray
						}
						continue
					}
					break
				}
			}
			if i >= len(data) || data[i] != ']' {
				return result, i, scan.ErrBadArray
			}
			i++
		default:
			return result, i, &validation.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv CustomDiveStruct) DecodeFromStream(s *scan.Stream) (result CustomDiveStruct, err error) {
	result = recv
	if result.Lookup != nil {
		clear(result.Lookup)
	}
	if result.Mixed != nil {
		clear(result.Mixed)
	}
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	if result.Trim != nil {
		result.Trim = result.Trim[:0]
	}
	seenLookup := false
	seenMixed := false
	seenPtr := false
	seenTags := false
	seenTrim := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "lookup":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("lookup", s.Pos, err)
			}
			if seenLookup {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"lookup"}}
			}
			seenLookup = true
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("lookup", s.Pos, err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("lookup", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("lookup", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("lookup", s.Pos, scan.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.Lookup = nil
				break
			}
			err = s.ObjectOpen()
			if err != nil {
				return result, decode.NewParseErr("lookup", s.Pos, err)
			}
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("lookup", s.Pos, err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("lookup", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == '}' {
				if result.Lookup == nil {
					result.Lookup = map[string]int{}
				}
			} else {
				if result.Lookup == nil {
					result.Lookup = make(map[string]int)
				}
			}
			for s.Bytes()[s.Pos] != '}' {
				var mk string
				mk, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("lookup", s.Pos, err)
				}
				if err := KeyShape(mk); err != nil {
					return result, &validation.CustomError{Pos: s.Offset(), Path: []string{"lookup.key"}, Name: "KeyShape", Value: mk, Cause: err}
				}
				err = s.SkipSpace()
				if err != nil {
					return result, decode.NewParseErr("lookup", s.Pos, err)
				}
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, decode.NewParseErr("lookup", s.Pos, err)
					}
				}
				if s.Bytes()[s.Pos] != ':' {
					return result, decode.NewParseErr("lookup", s.Pos, scan.ErrBadObject)
				}
				s.Pos++
				err = s.SkipSpace()
				if err != nil {
					return result, decode.NewParseErr("lookup", s.Pos, err)
				}
				var iv int64
				iv, err = s.Int64()
				if err != nil {
					return result, decode.NewParseErr("lookup", s.Pos, err)
				}
				result.Lookup[mk] = int(iv)
				err = s.SkipSpace()
				if err != nil {
					return result, decode.NewParseErr("lookup", s.Pos, err)
				}
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, decode.NewParseErr("lookup", s.Pos, err)
					}
				}
				if s.Bytes()[s.Pos] == ',' {
					s.Pos++
					err = s.SkipSpace()
					if err != nil {
						return result, decode.NewParseErr("lookup", s.Pos, err)
					}
					if s.Pos >= len(s.Bytes()) || s.Bytes()[s.Pos] == '}' {
						return result, decode.NewParseErr("lookup", s.Pos, scan.ErrBadObject)
					}
					continue
				}
				break
			}
			if s.Bytes()[s.Pos] != '}' {
				return result, decode.NewParseErr("lookup", s.Pos, scan.ErrBadObject)
			}
			s.Pos++
		case "mixed":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("mixed", s.Pos, err)
			}
			if seenMixed {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"mixed"}}
			}
			seenMixed = true
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("mixed", s.Pos, err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("mixed", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("mixed", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("mixed", s.Pos, scan.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.Mixed = nil
				break
			}
			err = s.ObjectOpen()
			if err != nil {
				return result, decode.NewParseErr("mixed", s.Pos, err)
			}
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("mixed", s.Pos, err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("mixed", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == '}' {
				if result.Mixed == nil {
					result.Mixed = map[string]int{}
				}
			} else {
				if result.Mixed == nil {
					result.Mixed = make(map[string]int)
				}
			}
			for s.Bytes()[s.Pos] != '}' {
				var mk string
				mk, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("mixed", s.Pos, err)
				}
				mk = LowerKey(mk)
				err = s.SkipSpace()
				if err != nil {
					return result, decode.NewParseErr("mixed", s.Pos, err)
				}
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, decode.NewParseErr("mixed", s.Pos, err)
					}
				}
				if s.Bytes()[s.Pos] != ':' {
					return result, decode.NewParseErr("mixed", s.Pos, scan.ErrBadObject)
				}
				s.Pos++
				err = s.SkipSpace()
				if err != nil {
					return result, decode.NewParseErr("mixed", s.Pos, err)
				}
				var iv int64
				iv, err = s.Int64()
				if err != nil {
					return result, decode.NewParseErr("mixed", s.Pos, err)
				}
				result.Mixed[mk] = int(iv)
				err = s.SkipSpace()
				if err != nil {
					return result, decode.NewParseErr("mixed", s.Pos, err)
				}
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, decode.NewParseErr("mixed", s.Pos, err)
					}
				}
				if s.Bytes()[s.Pos] == ',' {
					s.Pos++
					err = s.SkipSpace()
					if err != nil {
						return result, decode.NewParseErr("mixed", s.Pos, err)
					}
					if s.Pos >= len(s.Bytes()) || s.Bytes()[s.Pos] == '}' {
						return result, decode.NewParseErr("mixed", s.Pos, scan.ErrBadObject)
					}
					continue
				}
				break
			}
			if s.Bytes()[s.Pos] != '}' {
				return result, decode.NewParseErr("mixed", s.Pos, scan.ErrBadObject)
			}
			s.Pos++
		case "ptr":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("ptr", s.Pos, err)
			}
			if seenPtr {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"ptr"}}
			}
			seenPtr = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("ptr", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("ptr", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("ptr", s.Pos, scan.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.Ptr = nil
			} else {
				var v int64
				v, err = s.Int64()
				if err != nil {
					return result, decode.NewParseErr("ptr", s.Pos, err)
				}
				if result.Ptr == nil {
					result.Ptr = new(int(v))
				} else {
					(*result.Ptr) = int(v)
				}
			}
			if err := PointerCheck(result.Ptr); err != nil {
				return result, &validation.CustomError{Pos: s.Offset(), Path: []string{"ptr"}, Name: "PointerCheck", Value: result.Ptr, Cause: err}
			}
		case "tags":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Pos, err)
			}
			if seenTags {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"tags"}}
			}
			seenTags = true
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Pos, err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("tags", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("tags", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("tags", s.Pos, scan.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.Tags = nil
				break
			}
			err = s.ArrayOpen()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Pos, err)
			}
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Pos, err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("tags", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == ']' {
				if result.Tags == nil {
					result.Tags = []string{}
				}
			} else {
				if result.Tags == nil {
					result.Tags = make([]string, 0, 4)
				}
			}
			for s.Bytes()[s.Pos] != ']' {
				result.Tags = append(result.Tags, "")
				result.Tags[len(result.Tags)-1], err = s.String()
				if err != nil {
					return result, decode.NewParseErr("tags", s.Pos, err)
				}
				if err := NotBlank(result.Tags[len(result.Tags)-1]); err != nil {
					return result, &validation.CustomError{Pos: s.Offset(), Path: []string{"tags[]"}, Name: "NotBlank", Value: result.Tags[len(result.Tags)-1], Cause: err}
				}
				err = s.SkipSpace()
				if err != nil {
					return result, decode.NewParseErr("tags", s.Pos, err)
				}
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, decode.NewParseErr("tags", s.Pos, err)
					}
				}
				if s.Bytes()[s.Pos] == ',' {
					s.Pos++
					err = s.SkipSpace()
					if err != nil {
						return result, decode.NewParseErr("tags", s.Pos, err)
					}
					if s.Pos >= len(s.Bytes()) || s.Bytes()[s.Pos] == ']' {
						return result, decode.NewParseErr("tags", s.Pos, scan.ErrBadArray)
					}
					continue
				}
				break
			}
			if s.Bytes()[s.Pos] != ']' {
				return result, decode.NewParseErr("tags", s.Pos, scan.ErrBadArray)
			}
			s.Pos++
		case "trim":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("trim", s.Pos, err)
			}
			if seenTrim {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"trim"}}
			}
			seenTrim = true
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("trim", s.Pos, err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("trim", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("trim", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("trim", s.Pos, scan.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.Trim = nil
				break
			}
			err = s.ArrayOpen()
			if err != nil {
				return result, decode.NewParseErr("trim", s.Pos, err)
			}
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("trim", s.Pos, err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("trim", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == ']' {
				if result.Trim == nil {
					result.Trim = []string{}
				}
			} else {
				if result.Trim == nil {
					result.Trim = make([]string, 0, 4)
				}
			}
			for s.Bytes()[s.Pos] != ']' {
				result.Trim = append(result.Trim, "")
				result.Trim[len(result.Trim)-1], err = s.String()
				if err != nil {
					return result, decode.NewParseErr("trim", s.Pos, err)
				}
				result.Trim[len(result.Trim)-1] = TrimSpace(result.Trim[len(result.Trim)-1])
				err = s.SkipSpace()
				if err != nil {
					return result, decode.NewParseErr("trim", s.Pos, err)
				}
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, decode.NewParseErr("trim", s.Pos, err)
					}
				}
				if s.Bytes()[s.Pos] == ',' {
					s.Pos++
					err = s.SkipSpace()
					if err != nil {
						return result, decode.NewParseErr("trim", s.Pos, err)
					}
					if s.Pos >= len(s.Bytes()) || s.Bytes()[s.Pos] == ']' {
						return result, decode.NewParseErr("trim", s.Pos, scan.ErrBadArray)
					}
					continue
				}
				break
			}
			if s.Bytes()[s.Pos] != ']' {
				return result, decode.NewParseErr("trim", s.Pos, scan.ErrBadArray)
			}
			s.Pos++
		default:
			return result, &validation.UnknownKeyError{Pos: s.Offset(), Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s CustomDiveStruct) JSONSize() int {
	size := 59
	size += len(s.Lookup) * 24
	for k := range s.Lookup {
		size += len(k) * 2
	}
	size += len(s.Mixed) * 24
	for k := range s.Mixed {
		size += len(k) * 2
	}
	if s.Ptr == nil {
		size += 4
	} else {
		size += 20
	}
	if n := len(s.Tags); n > 0 {
		size += n - 1
	}
	for i0 := range s.Tags {
		size += len(s.Tags[i0])*2 + 2
	}
	if n := len(s.Trim); n > 0 {
		size += n - 1
	}
	for i0 := range s.Trim {
		size += len(s.Trim[i0])*2 + 2
	}
	return size
}

func (s CustomDiveStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"lookup\":"...)
	if s.Lookup == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '{')
		firstLookup := true
		for k, v := range s.Lookup {
			if firstLookup {
				firstLookup = false
				dst = append(dst, '"')
			} else {
				dst = append(dst, ",\""...)
			}
			dst = encode.AppendStringNoHTML(dst, k)
			dst = append(dst, ':')
			dst = strconv.AppendInt(dst, int64(v), 10)
		}
		dst = append(dst, '}')
	}
	dst = append(dst, ",\"mixed\":"...)
	if s.Mixed == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '{')
		firstMixed := true
		for k, v := range s.Mixed {
			if firstMixed {
				firstMixed = false
				dst = append(dst, '"')
			} else {
				dst = append(dst, ",\""...)
			}
			dst = encode.AppendStringNoHTML(dst, k)
			dst = append(dst, ':')
			dst = strconv.AppendInt(dst, int64(v), 10)
		}
		dst = append(dst, '}')
	}
	dst = append(dst, ",\"ptr\":"...)
	if s.Ptr == nil {
		dst = append(dst, "null"...)
	} else {
		dst = strconv.AppendInt(dst, int64((*s.Ptr)), 10)
	}
	dst = append(dst, ",\"tags\":"...)
	if s.Tags == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		if len(s.Tags) > 0 {
			dst = append(dst, '"')
			dst = encode.AppendStringNoHTML(dst, s.Tags[0])
			for _, v0 := range s.Tags[1:] {
				dst = append(dst, ",\""...)
				dst = encode.AppendStringNoHTML(dst, v0)
			}
		}
		dst = append(dst, ']')
	}
	dst = append(dst, ",\"trim\":"...)
	if s.Trim == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		if len(s.Trim) > 0 {
			dst = append(dst, '"')
			dst = encode.AppendStringNoHTML(dst, s.Trim[0])
			for _, v0 := range s.Trim[1:] {
				dst = append(dst, ",\""...)
				dst = encode.AppendStringNoHTML(dst, v0)
			}
		}
		dst = append(dst, ']')
	}
	return append(dst, '}'), nil
}
