// Code generated by ggen; DO NOT EDIT.

package integrationtests

import (
	"math"
	"strconv"
	"strings"
	"unicode/utf8"
	"unsafe"

	"github.com/sirkostya009/ggen/decode/validation"
	"github.com/sirkostya009/ggen/encode"
	"github.com/sirkostya009/ggen/scan"
)

func (result DiveStruct) DecodeFrom(data []byte) (DiveStruct, int, error) {
	i := 0
	if result.Scores != nil {
		result.Scores = result.Scores[:0]
	}
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	var err error
	_ = err
	seenCount := false
	seenScores := false
	seenTags := false
	seenTitle := false
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, scan.ErrBadObject
	}
	i++
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		return result, i + 1, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, scan.ErrExpectString
		}
		{
			ke := i + 1
			for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
				ke++
			}
			if ke >= len(data) {
				return result, i, scan.ErrUnterminated
			}
			if data[ke] < 0x20 {
				return result, i, scan.ErrBadString
			}
			if data[ke] == '"' {
				key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				key, i, err = scan.String(data, i)
				if err != nil {
					return result, i, err
				}
			}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, scan.ErrBadObject
		}
		i++
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch len(key) {
		case 4:
			if key == "tags" {
				if seenTags {
					return result, i, &validation.DuplicateKeyError{Field: "tags"}
				}
				seenTags = true
				{
					for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
						i += 4
						result.Tags = nil
					} else {
						if i >= len(data) || data[i] != '[' {
							return result, i, scan.ErrBadArray
						}
						i++
						for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i < len(data) && data[i] == ']' {
							if result.Tags == nil {
								result.Tags = []string{}
							}
						} else {
							if result.Tags == nil {
								result.Tags = make([]string, 0, 1)
							}
						}
						for i < len(data) && data[i] != ']' {
							result.Tags = append(result.Tags, "")
							if i >= len(data) || data[i] != '"' {
								return result, i, scan.ErrExpectString
							}
							{
								ke := i + 1
								for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
									ke++
								}
								if ke >= len(data) {
									return result, i, scan.ErrUnterminated
								}
								if data[ke] < 0x20 {
									return result, i, scan.ErrBadString
								}
								if data[ke] == '"' {
									result.Tags[len(result.Tags)-1] = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
									i = ke + 1
								} else {
									result.Tags[len(result.Tags)-1], i, err = scan.String(data, i)
									if err != nil {
										return result, i, err
									}
								}
							}
							if utf8.RuneCountInString(result.Tags[len(result.Tags)-1]) < 2 {
								return result, i, &validation.MinRunesError{Field: "tags[]", Limit: 2, Got: utf8.RuneCountInString(result.Tags[len(result.Tags)-1])}
							}
							if utf8.RuneCountInString(result.Tags[len(result.Tags)-1]) > 10 {
								return result, i, &validation.MaxRunesError{Field: "tags[]", Limit: 10, Got: utf8.RuneCountInString(result.Tags[len(result.Tags)-1])}
							}
							for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
								i++
							}
							if i < len(data) && data[i] == ',' {
								i++
								for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
									i++
								}
								continue
							}
							break
						}
						if i >= len(data) || data[i] != ']' {
							return result, i, scan.ErrBadArray
						}
						i++
					}
				}
				if len(result.Tags) < 1 {
					return result, i, &validation.MinLenError{Field: "tags", Limit: 1, Got: len(result.Tags)}
				}
				if len(result.Tags) > 3 {
					return result, i, &validation.MaxLenError{Field: "tags", Limit: 3, Got: len(result.Tags)}
				}
			} else {
				return result, i, &validation.UnknownKeyError{Field: key}
			}
		case 5:
			switch key {
			case "count":
				if seenCount {
					return result, i, &validation.DuplicateKeyError{Field: "count"}
				}
				seenCount = true
				{
					neg := false
					if i < len(data) && data[i] == '-' {
						neg = true
						i++
					}
					if i >= len(data) || data[i] < '0' || data[i] > '9' {
						return result, i, scan.ErrBadNumber
					}
					limit := uint64(math.MaxInt64)
					if neg {
						limit = scan.SignedNeg
					}
					var u uint64
					for i < len(data) && data[i] >= '0' && data[i] <= '9' {
						d := uint64(data[i] - '0')
						if u > limit/10 || (u == limit/10 && d > limit%10) {
							return result, i, scan.ErrNumberOverflow
						}
						u = u*10 + d
						i++
					}
					if i < len(data) {
						c := data[i]
						if c == '.' || c == 'e' || c == 'E' {
							return result, i, scan.ErrBadNumber
						}
					}
					var n int64
					if neg {
						if u == scan.SignedNeg {
							n = math.MinInt64
						} else {
							n = -int64(u)
						}
					} else {
						n = int64(u)
					}
					result.Count = int(n)
				}
				if err := EvenOnly(result.Count); err != nil {
					return result, i, &validation.CustomError{Field: "count", Name: "@EvenOnly", Cause: err}
				}
			case "title":
				if seenTitle {
					return result, i, &validation.DuplicateKeyError{Field: "title"}
				}
				seenTitle = true
				if i >= len(data) || data[i] != '"' {
					return result, i, scan.ErrExpectString
				}
				{
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, scan.ErrUnterminated
					}
					if data[ke] < 0x20 {
						return result, i, scan.ErrBadString
					}
					if data[ke] == '"' {
						result.Title = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.Title, i, err = scan.String(data, i)
						if err != nil {
							return result, i, err
						}
					}
				}
				if utf8.RuneCountInString(result.Title) < 1 {
					return result, i, &validation.MinRunesError{Field: "title", Limit: 1, Got: utf8.RuneCountInString(result.Title)}
				}
				if utf8.RuneCountInString(result.Title) > 5 {
					return result, i, &validation.MaxRunesError{Field: "title", Limit: 5, Got: utf8.RuneCountInString(result.Title)}
				}
			default:
				return result, i, &validation.UnknownKeyError{Field: key}
			}
		case 6:
			if key == "scores" {
				if seenScores {
					return result, i, &validation.DuplicateKeyError{Field: "scores"}
				}
				seenScores = true
				{
					for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
						i += 4
						result.Scores = nil
					} else {
						if i >= len(data) || data[i] != '[' {
							return result, i, scan.ErrBadArray
						}
						i++
						for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i < len(data) && data[i] == ']' {
							if result.Scores == nil {
								result.Scores = []int{}
							}
						} else {
							if result.Scores == nil {
								result.Scores = make([]int, 0, 4)
							}
						}
						for i < len(data) && data[i] != ']' {
							result.Scores = append(result.Scores, 0)
							{
								neg := false
								if i < len(data) && data[i] == '-' {
									neg = true
									i++
								}
								if i >= len(data) || data[i] < '0' || data[i] > '9' {
									return result, i, scan.ErrBadNumber
								}
								limit := uint64(math.MaxInt64)
								if neg {
									limit = scan.SignedNeg
								}
								var u uint64
								for i < len(data) && data[i] >= '0' && data[i] <= '9' {
									d := uint64(data[i] - '0')
									if u > limit/10 || (u == limit/10 && d > limit%10) {
										return result, i, scan.ErrNumberOverflow
									}
									u = u*10 + d
									i++
								}
								if i < len(data) {
									c := data[i]
									if c == '.' || c == 'e' || c == 'E' {
										return result, i, scan.ErrBadNumber
									}
								}
								var n int64
								if neg {
									if u == scan.SignedNeg {
										n = math.MinInt64
									} else {
										n = -int64(u)
									}
								} else {
									n = int64(u)
								}
								result.Scores[len(result.Scores)-1] = int(n)
							}
							if result.Scores[len(result.Scores)-1] < 0 {
								return result, i, &validation.GTEError{Field: "scores[]", Limit: 0, Value: result.Scores[len(result.Scores)-1]}
							}
							if result.Scores[len(result.Scores)-1] > 100 {
								return result, i, &validation.LTEError{Field: "scores[]", Limit: 100, Value: result.Scores[len(result.Scores)-1]}
							}
							for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
								i++
							}
							if i < len(data) && data[i] == ',' {
								i++
								for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
									i++
								}
								continue
							}
							break
						}
						if i >= len(data) || data[i] != ']' {
							return result, i, scan.ErrBadArray
						}
						i++
					}
				}
			} else {
				return result, i, &validation.UnknownKeyError{Field: key}
			}
		default:
			return result, i, &validation.UnknownKeyError{Field: key}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, scan.ErrBadObject
		}
		if data[i] == ',' {
			i++
			for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			return result, i + 1, nil
		}
		return result, i, scan.ErrBadObject
	}
}

func (result DiveStruct) DecodeStreamFrom(s *scan.Stream) (DiveStruct, error) {
	if result.Scores != nil {
		result.Scores = result.Scores[:0]
	}
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	seenCount := false
	seenScores := false
	seenTags := false
	seenTitle := false
	err := s.ObjectOpen()
	if err != nil {
		return result, err
	}
	err = s.SkipSpace()
	if err != nil {
		return result, err
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, err
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, err
		}
		switch len(key) {
		case 4:
			if key == "tags" {
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenTags {
					return result, &validation.DuplicateKeyError{Field: "tags"}
				}
				seenTags = true
				{
					err = s.SkipSpace()
					if err != nil {
						return result, err
					}
					if s.Pos >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, err
						}
					}
					if s.Bytes()[s.Pos] == 'n' {
						for ki := 1; ki < 4; ki++ {
							if s.Pos+ki >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos+ki] != "null"[ki] {
								return result, scan.ErrBadLiteral
							}
						}
						s.Pos += 4
						result.Tags = nil
					} else {
						err = s.ArrayOpen()
						if err != nil {
							return result, err
						}
						err = s.SkipSpace()
						if err != nil {
							return result, err
						}
						if s.Pos >= len(s.Bytes()) {
							if err = s.ReadMore(0); err != nil {
								return result, err
							}
						}
						if s.Bytes()[s.Pos] == ']' {
							if result.Tags == nil {
								result.Tags = []string{}
							}
						} else {
							if result.Tags == nil {
								result.Tags = make([]string, 0, 1)
							}
						}
						for s.Bytes()[s.Pos] != ']' {
							result.Tags = append(result.Tags, "")
							result.Tags[len(result.Tags)-1], err = s.String()
							if err != nil {
								return result, err
							}
							if utf8.RuneCountInString(result.Tags[len(result.Tags)-1]) < 2 {
								return result, &validation.MinRunesError{Field: "tags[]", Limit: 2, Got: utf8.RuneCountInString(result.Tags[len(result.Tags)-1])}
							}
							if utf8.RuneCountInString(result.Tags[len(result.Tags)-1]) > 10 {
								return result, &validation.MaxRunesError{Field: "tags[]", Limit: 10, Got: utf8.RuneCountInString(result.Tags[len(result.Tags)-1])}
							}
							err = s.SkipSpace()
							if err != nil {
								return result, err
							}
							if s.Pos >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos] == ',' {
								s.Pos++
								err = s.SkipSpace()
								if err != nil {
									return result, err
								}
								continue
							}
							break
						}
						if s.Bytes()[s.Pos] != ']' {
							return result, scan.ErrBadArray
						}
						s.Pos++
					}
				}
				if len(result.Tags) < 1 {
					return result, &validation.MinLenError{Field: "tags", Limit: 1, Got: len(result.Tags)}
				}
				if len(result.Tags) > 3 {
					return result, &validation.MaxLenError{Field: "tags", Limit: 3, Got: len(result.Tags)}
				}
			} else {
				return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
			}
		case 5:
			switch key {
			case "count":
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenCount {
					return result, &validation.DuplicateKeyError{Field: "count"}
				}
				seenCount = true
				var iv int64
				iv, err = s.Int64()
				if err != nil {
					return result, err
				}
				result.Count = int(iv)
				if err := EvenOnly(result.Count); err != nil {
					return result, &validation.CustomError{Field: "count", Name: "@EvenOnly", Cause: err}
				}
			case "title":
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenTitle {
					return result, &validation.DuplicateKeyError{Field: "title"}
				}
				seenTitle = true
				result.Title, err = s.String()
				if err != nil {
					return result, err
				}
				if utf8.RuneCountInString(result.Title) < 1 {
					return result, &validation.MinRunesError{Field: "title", Limit: 1, Got: utf8.RuneCountInString(result.Title)}
				}
				if utf8.RuneCountInString(result.Title) > 5 {
					return result, &validation.MaxRunesError{Field: "title", Limit: 5, Got: utf8.RuneCountInString(result.Title)}
				}
			default:
				return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
			}
		case 6:
			if key == "scores" {
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenScores {
					return result, &validation.DuplicateKeyError{Field: "scores"}
				}
				seenScores = true
				{
					err = s.SkipSpace()
					if err != nil {
						return result, err
					}
					if s.Pos >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, err
						}
					}
					if s.Bytes()[s.Pos] == 'n' {
						for ki := 1; ki < 4; ki++ {
							if s.Pos+ki >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos+ki] != "null"[ki] {
								return result, scan.ErrBadLiteral
							}
						}
						s.Pos += 4
						result.Scores = nil
					} else {
						err = s.ArrayOpen()
						if err != nil {
							return result, err
						}
						err = s.SkipSpace()
						if err != nil {
							return result, err
						}
						if s.Pos >= len(s.Bytes()) {
							if err = s.ReadMore(0); err != nil {
								return result, err
							}
						}
						if s.Bytes()[s.Pos] == ']' {
							if result.Scores == nil {
								result.Scores = []int{}
							}
						} else {
							if result.Scores == nil {
								result.Scores = make([]int, 0, 4)
							}
						}
						for s.Bytes()[s.Pos] != ']' {
							result.Scores = append(result.Scores, 0)
							var iv int64
							iv, err = s.Int64()
							if err != nil {
								return result, err
							}
							result.Scores[len(result.Scores)-1] = int(iv)
							if result.Scores[len(result.Scores)-1] < 0 {
								return result, &validation.GTEError{Field: "scores[]", Limit: 0, Value: result.Scores[len(result.Scores)-1]}
							}
							if result.Scores[len(result.Scores)-1] > 100 {
								return result, &validation.LTEError{Field: "scores[]", Limit: 100, Value: result.Scores[len(result.Scores)-1]}
							}
							err = s.SkipSpace()
							if err != nil {
								return result, err
							}
							if s.Pos >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos] == ',' {
								s.Pos++
								err = s.SkipSpace()
								if err != nil {
									return result, err
								}
								continue
							}
							break
						}
						if s.Bytes()[s.Pos] != ']' {
							return result, scan.ErrBadArray
						}
						s.Pos++
					}
				}
			} else {
				return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
			}
		default:
			return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
		}
		err = s.SkipSpace()
		if err != nil {
			return result, err
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, err
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, err
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, scan.ErrBadObject
	}
}

func (s DiveStruct) JSONSize() int {
	size := 63
	if n := len(s.Scores); n > 0 {
		size += n - 1
	}
	size += len(s.Scores) * 20
	if n := len(s.Tags); n > 0 {
		size += n - 1
	}
	for i0 := range s.Tags {
		size += len(s.Tags[i0])*2 + 2
	}
	size += len(s.Title) * 2
	return size
}

func (s DiveStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"count\":"...)
	dst = strconv.AppendInt(dst, int64(s.Count), 10)
	dst = append(dst, ",\"scores\":"...)
	if s.Scores == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		if len(s.Scores) > 0 {
			dst = strconv.AppendInt(dst, int64(s.Scores[0]), 10)
			for _, v0 := range s.Scores[1:] {
				dst = append(dst, ',')
				dst = strconv.AppendInt(dst, int64(v0), 10)
			}
		}
		dst = append(dst, ']')
	}
	dst = append(dst, ",\"tags\":"...)
	if s.Tags == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		if len(s.Tags) > 0 {
			dst = append(dst, '"')
			dst = encode.AppendStringNoHTML(dst, s.Tags[0])
			for _, v0 := range s.Tags[1:] {
				dst = append(dst, ",\""...)
				dst = encode.AppendStringNoHTML(dst, v0)
			}
		}
		dst = append(dst, ']')
	}
	dst = append(dst, ",\"title\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Title)
	return append(dst, '}'), nil
}

func (result CustomDiveStruct) DecodeFrom(data []byte) (CustomDiveStruct, int, error) {
	i := 0
	if result.Lookup != nil {
		clear(result.Lookup)
	}
	if result.Mixed != nil {
		clear(result.Mixed)
	}
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	if result.Trim != nil {
		result.Trim = result.Trim[:0]
	}
	var err error
	_ = err
	seenLookup := false
	seenMixed := false
	seenPtr := false
	seenTags := false
	seenTrim := false
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, scan.ErrBadObject
	}
	i++
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		return result, i + 1, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, scan.ErrExpectString
		}
		{
			ke := i + 1
			for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
				ke++
			}
			if ke >= len(data) {
				return result, i, scan.ErrUnterminated
			}
			if data[ke] < 0x20 {
				return result, i, scan.ErrBadString
			}
			if data[ke] == '"' {
				key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				key, i, err = scan.String(data, i)
				if err != nil {
					return result, i, err
				}
			}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, scan.ErrBadObject
		}
		i++
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch len(key) {
		case 3:
			if key == "ptr" {
				if seenPtr {
					return result, i, &validation.DuplicateKeyError{Field: "ptr"}
				}
				seenPtr = true
				if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
					i = 4 + i
					result.Ptr = nil
				} else {
					var v int
					{
						neg := false
						if i < len(data) && data[i] == '-' {
							neg = true
							i++
						}
						if i >= len(data) || data[i] < '0' || data[i] > '9' {
							return result, i, scan.ErrBadNumber
						}
						limit := uint64(math.MaxInt64)
						if neg {
							limit = scan.SignedNeg
						}
						var u uint64
						for i < len(data) && data[i] >= '0' && data[i] <= '9' {
							d := uint64(data[i] - '0')
							if u > limit/10 || (u == limit/10 && d > limit%10) {
								return result, i, scan.ErrNumberOverflow
							}
							u = u*10 + d
							i++
						}
						if i < len(data) {
							c := data[i]
							if c == '.' || c == 'e' || c == 'E' {
								return result, i, scan.ErrBadNumber
							}
						}
						var n int64
						if neg {
							if u == scan.SignedNeg {
								n = math.MinInt64
							} else {
								n = -int64(u)
							}
						} else {
							n = int64(u)
						}
						v = int(n)
					}
					result.Ptr = &v
				}
				if err := PointerCheck(result.Ptr); err != nil {
					return result, i, &validation.CustomError{Field: "ptr", Name: "@PointerCheck", Cause: err}
				}
			} else {
				return result, i, &validation.UnknownKeyError{Field: key}
			}
		case 4:
			switch key {
			case "tags":
				if seenTags {
					return result, i, &validation.DuplicateKeyError{Field: "tags"}
				}
				seenTags = true
				{
					for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
						i += 4
						result.Tags = nil
					} else {
						if i >= len(data) || data[i] != '[' {
							return result, i, scan.ErrBadArray
						}
						i++
						for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i < len(data) && data[i] == ']' {
							if result.Tags == nil {
								result.Tags = []string{}
							}
						} else {
							if result.Tags == nil {
								result.Tags = make([]string, 0, 4)
							}
						}
						for i < len(data) && data[i] != ']' {
							result.Tags = append(result.Tags, "")
							if i >= len(data) || data[i] != '"' {
								return result, i, scan.ErrExpectString
							}
							{
								ke := i + 1
								for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
									ke++
								}
								if ke >= len(data) {
									return result, i, scan.ErrUnterminated
								}
								if data[ke] < 0x20 {
									return result, i, scan.ErrBadString
								}
								if data[ke] == '"' {
									result.Tags[len(result.Tags)-1] = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
									i = ke + 1
								} else {
									result.Tags[len(result.Tags)-1], i, err = scan.String(data, i)
									if err != nil {
										return result, i, err
									}
								}
							}
							if err := NotBlank(result.Tags[len(result.Tags)-1]); err != nil {
								return result, i, &validation.CustomError{Field: "tags[]", Name: "@NotBlank", Cause: err}
							}
							for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
								i++
							}
							if i < len(data) && data[i] == ',' {
								i++
								for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
									i++
								}
								continue
							}
							break
						}
						if i >= len(data) || data[i] != ']' {
							return result, i, scan.ErrBadArray
						}
						i++
					}
				}
			case "trim":
				if seenTrim {
					return result, i, &validation.DuplicateKeyError{Field: "trim"}
				}
				seenTrim = true
				{
					for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
						i += 4
						result.Trim = nil
					} else {
						if i >= len(data) || data[i] != '[' {
							return result, i, scan.ErrBadArray
						}
						i++
						for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i < len(data) && data[i] == ']' {
							if result.Trim == nil {
								result.Trim = []string{}
							}
						} else {
							if result.Trim == nil {
								result.Trim = make([]string, 0, 4)
							}
						}
						for i < len(data) && data[i] != ']' {
							result.Trim = append(result.Trim, "")
							if i >= len(data) || data[i] != '"' {
								return result, i, scan.ErrExpectString
							}
							{
								ke := i + 1
								for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
									ke++
								}
								if ke >= len(data) {
									return result, i, scan.ErrUnterminated
								}
								if data[ke] < 0x20 {
									return result, i, scan.ErrBadString
								}
								if data[ke] == '"' {
									result.Trim[len(result.Trim)-1] = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
									i = ke + 1
								} else {
									result.Trim[len(result.Trim)-1], i, err = scan.String(data, i)
									if err != nil {
										return result, i, err
									}
								}
							}
							result.Trim[len(result.Trim)-1] = TrimSpace(result.Trim[len(result.Trim)-1])
							for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
								i++
							}
							if i < len(data) && data[i] == ',' {
								i++
								for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
									i++
								}
								continue
							}
							break
						}
						if i >= len(data) || data[i] != ']' {
							return result, i, scan.ErrBadArray
						}
						i++
					}
				}
			default:
				return result, i, &validation.UnknownKeyError{Field: key}
			}
		case 5:
			if key == "mixed" {
				if seenMixed {
					return result, i, &validation.DuplicateKeyError{Field: "mixed"}
				}
				seenMixed = true
				{
					for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
						i += 4
						result.Mixed = nil
					} else {
						if i >= len(data) || data[i] != '{' {
							return result, i, scan.ErrBadObject
						}
						i++
						for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i < len(data) && data[i] == '}' {
							if result.Mixed == nil {
								result.Mixed = map[string]int{}
							}
						} else {
							if result.Mixed == nil {
								result.Mixed = make(map[string]int)
							}
						}
						for i < len(data) && data[i] != '}' {
							var mk string
							if i >= len(data) || data[i] != '"' {
								return result, i, scan.ErrExpectString
							}
							{
								ke := i + 1
								for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
									ke++
								}
								if ke >= len(data) {
									return result, i, scan.ErrUnterminated
								}
								if data[ke] < 0x20 {
									return result, i, scan.ErrBadString
								}
								if data[ke] == '"' {
									mk = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
									i = ke + 1
								} else {
									mk, i, err = scan.String(data, i)
									if err != nil {
										return result, i, err
									}
								}
							}
							mk = LowerKey(mk)
							for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
								i++
							}
							if i >= len(data) || data[i] != ':' {
								return result, i, scan.ErrBadObject
							}
							i++
							for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
								i++
							}
							var mn int64
							{
								neg := false
								if i < len(data) && data[i] == '-' {
									neg = true
									i++
								}
								if i >= len(data) || data[i] < '0' || data[i] > '9' {
									return result, i, scan.ErrBadNumber
								}
								limit := uint64(math.MaxInt64)
								if neg {
									limit = scan.SignedNeg
								}
								var u uint64
								for i < len(data) && data[i] >= '0' && data[i] <= '9' {
									d := uint64(data[i] - '0')
									if u > limit/10 || (u == limit/10 && d > limit%10) {
										return result, i, scan.ErrNumberOverflow
									}
									u = u*10 + d
									i++
								}
								if i < len(data) {
									c := data[i]
									if c == '.' || c == 'e' || c == 'E' {
										return result, i, scan.ErrBadNumber
									}
								}
								var n int64
								if neg {
									if u == scan.SignedNeg {
										n = math.MinInt64
									} else {
										n = -int64(u)
									}
								} else {
									n = int64(u)
								}
								mn = n
							}
							result.Mixed[mk] = int(mn)
							for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
								i++
							}
							if i < len(data) && data[i] == ',' {
								i++
								for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
									i++
								}
								continue
							}
							break
						}
						if i >= len(data) || data[i] != '}' {
							return result, i, scan.ErrBadObject
						}
						i++
					}
				}
			} else {
				return result, i, &validation.UnknownKeyError{Field: key}
			}
		case 6:
			if key == "lookup" {
				if seenLookup {
					return result, i, &validation.DuplicateKeyError{Field: "lookup"}
				}
				seenLookup = true
				{
					for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
						i += 4
						result.Lookup = nil
					} else {
						if i >= len(data) || data[i] != '{' {
							return result, i, scan.ErrBadObject
						}
						i++
						for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i < len(data) && data[i] == '}' {
							if result.Lookup == nil {
								result.Lookup = map[string]int{}
							}
						} else {
							if result.Lookup == nil {
								result.Lookup = make(map[string]int)
							}
						}
						for i < len(data) && data[i] != '}' {
							var mk string
							if i >= len(data) || data[i] != '"' {
								return result, i, scan.ErrExpectString
							}
							{
								ke := i + 1
								for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
									ke++
								}
								if ke >= len(data) {
									return result, i, scan.ErrUnterminated
								}
								if data[ke] < 0x20 {
									return result, i, scan.ErrBadString
								}
								if data[ke] == '"' {
									mk = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
									i = ke + 1
								} else {
									mk, i, err = scan.String(data, i)
									if err != nil {
										return result, i, err
									}
								}
							}
							if err := KeyShape(mk); err != nil {
								return result, i, &validation.CustomError{Field: "lookup.key", Name: "@KeyShape", Cause: err}
							}
							for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
								i++
							}
							if i >= len(data) || data[i] != ':' {
								return result, i, scan.ErrBadObject
							}
							i++
							for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
								i++
							}
							var mn int64
							{
								neg := false
								if i < len(data) && data[i] == '-' {
									neg = true
									i++
								}
								if i >= len(data) || data[i] < '0' || data[i] > '9' {
									return result, i, scan.ErrBadNumber
								}
								limit := uint64(math.MaxInt64)
								if neg {
									limit = scan.SignedNeg
								}
								var u uint64
								for i < len(data) && data[i] >= '0' && data[i] <= '9' {
									d := uint64(data[i] - '0')
									if u > limit/10 || (u == limit/10 && d > limit%10) {
										return result, i, scan.ErrNumberOverflow
									}
									u = u*10 + d
									i++
								}
								if i < len(data) {
									c := data[i]
									if c == '.' || c == 'e' || c == 'E' {
										return result, i, scan.ErrBadNumber
									}
								}
								var n int64
								if neg {
									if u == scan.SignedNeg {
										n = math.MinInt64
									} else {
										n = -int64(u)
									}
								} else {
									n = int64(u)
								}
								mn = n
							}
							result.Lookup[mk] = int(mn)
							for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
								i++
							}
							if i < len(data) && data[i] == ',' {
								i++
								for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
									i++
								}
								continue
							}
							break
						}
						if i >= len(data) || data[i] != '}' {
							return result, i, scan.ErrBadObject
						}
						i++
					}
				}
			} else {
				return result, i, &validation.UnknownKeyError{Field: key}
			}
		default:
			return result, i, &validation.UnknownKeyError{Field: key}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, scan.ErrBadObject
		}
		if data[i] == ',' {
			i++
			for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			return result, i + 1, nil
		}
		return result, i, scan.ErrBadObject
	}
}

func (result CustomDiveStruct) DecodeStreamFrom(s *scan.Stream) (CustomDiveStruct, error) {
	if result.Lookup != nil {
		clear(result.Lookup)
	}
	if result.Mixed != nil {
		clear(result.Mixed)
	}
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	if result.Trim != nil {
		result.Trim = result.Trim[:0]
	}
	seenLookup := false
	seenMixed := false
	seenPtr := false
	seenTags := false
	seenTrim := false
	err := s.ObjectOpen()
	if err != nil {
		return result, err
	}
	err = s.SkipSpace()
	if err != nil {
		return result, err
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, err
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, err
		}
		switch len(key) {
		case 3:
			if key == "ptr" {
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenPtr {
					return result, &validation.DuplicateKeyError{Field: "ptr"}
				}
				seenPtr = true
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, err
					}
				}
				if s.Bytes()[s.Pos] == 'n' {
					for ki := 1; ki < 4; ki++ {
						if s.Pos+ki >= len(s.Bytes()) {
							if err = s.ReadMore(0); err != nil {
								return result, err
							}
						}
						if s.Bytes()[s.Pos+ki] != "null"[ki] {
							return result, scan.ErrBadLiteral
						}
					}
					s.Pos += 4
					result.Ptr = nil
				} else {
					var v int
					var iv int64
					iv, err = s.Int64()
					if err != nil {
						return result, err
					}
					v = int(iv)

					result.Ptr = &v
				}
				if err := PointerCheck(result.Ptr); err != nil {
					return result, &validation.CustomError{Field: "ptr", Name: "@PointerCheck", Cause: err}
				}
			} else {
				return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
			}
		case 4:
			switch key {
			case "tags":
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenTags {
					return result, &validation.DuplicateKeyError{Field: "tags"}
				}
				seenTags = true
				{
					err = s.SkipSpace()
					if err != nil {
						return result, err
					}
					if s.Pos >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, err
						}
					}
					if s.Bytes()[s.Pos] == 'n' {
						for ki := 1; ki < 4; ki++ {
							if s.Pos+ki >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos+ki] != "null"[ki] {
								return result, scan.ErrBadLiteral
							}
						}
						s.Pos += 4
						result.Tags = nil
					} else {
						err = s.ArrayOpen()
						if err != nil {
							return result, err
						}
						err = s.SkipSpace()
						if err != nil {
							return result, err
						}
						if s.Pos >= len(s.Bytes()) {
							if err = s.ReadMore(0); err != nil {
								return result, err
							}
						}
						if s.Bytes()[s.Pos] == ']' {
							if result.Tags == nil {
								result.Tags = []string{}
							}
						} else {
							if result.Tags == nil {
								result.Tags = make([]string, 0, 4)
							}
						}
						for s.Bytes()[s.Pos] != ']' {
							result.Tags = append(result.Tags, "")
							result.Tags[len(result.Tags)-1], err = s.String()
							if err != nil {
								return result, err
							}
							if err := NotBlank(result.Tags[len(result.Tags)-1]); err != nil {
								return result, &validation.CustomError{Field: "tags[]", Name: "@NotBlank", Cause: err}
							}
							err = s.SkipSpace()
							if err != nil {
								return result, err
							}
							if s.Pos >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos] == ',' {
								s.Pos++
								err = s.SkipSpace()
								if err != nil {
									return result, err
								}
								continue
							}
							break
						}
						if s.Bytes()[s.Pos] != ']' {
							return result, scan.ErrBadArray
						}
						s.Pos++
					}
				}
			case "trim":
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenTrim {
					return result, &validation.DuplicateKeyError{Field: "trim"}
				}
				seenTrim = true
				{
					err = s.SkipSpace()
					if err != nil {
						return result, err
					}
					if s.Pos >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, err
						}
					}
					if s.Bytes()[s.Pos] == 'n' {
						for ki := 1; ki < 4; ki++ {
							if s.Pos+ki >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos+ki] != "null"[ki] {
								return result, scan.ErrBadLiteral
							}
						}
						s.Pos += 4
						result.Trim = nil
					} else {
						err = s.ArrayOpen()
						if err != nil {
							return result, err
						}
						err = s.SkipSpace()
						if err != nil {
							return result, err
						}
						if s.Pos >= len(s.Bytes()) {
							if err = s.ReadMore(0); err != nil {
								return result, err
							}
						}
						if s.Bytes()[s.Pos] == ']' {
							if result.Trim == nil {
								result.Trim = []string{}
							}
						} else {
							if result.Trim == nil {
								result.Trim = make([]string, 0, 4)
							}
						}
						for s.Bytes()[s.Pos] != ']' {
							result.Trim = append(result.Trim, "")
							result.Trim[len(result.Trim)-1], err = s.String()
							if err != nil {
								return result, err
							}
							result.Trim[len(result.Trim)-1] = TrimSpace(result.Trim[len(result.Trim)-1])
							err = s.SkipSpace()
							if err != nil {
								return result, err
							}
							if s.Pos >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos] == ',' {
								s.Pos++
								err = s.SkipSpace()
								if err != nil {
									return result, err
								}
								continue
							}
							break
						}
						if s.Bytes()[s.Pos] != ']' {
							return result, scan.ErrBadArray
						}
						s.Pos++
					}
				}
			default:
				return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
			}
		case 5:
			if key == "mixed" {
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenMixed {
					return result, &validation.DuplicateKeyError{Field: "mixed"}
				}
				seenMixed = true
				{
					err = s.SkipSpace()
					if err != nil {
						return result, err
					}
					if s.Pos >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, err
						}
					}
					if s.Bytes()[s.Pos] == 'n' {
						for ki := 1; ki < 4; ki++ {
							if s.Pos+ki >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos+ki] != "null"[ki] {
								return result, scan.ErrBadLiteral
							}
						}
						s.Pos += 4
						result.Mixed = nil
					} else {
						err = s.ObjectOpen()
						if err != nil {
							return result, err
						}
						err = s.SkipSpace()
						if err != nil {
							return result, err
						}
						if s.Pos >= len(s.Bytes()) {
							if err = s.ReadMore(0); err != nil {
								return result, err
							}
						}
						if s.Bytes()[s.Pos] == '}' {
							if result.Mixed == nil {
								result.Mixed = map[string]int{}
							}
						} else {
							if result.Mixed == nil {
								result.Mixed = make(map[string]int)
							}
						}
						for s.Bytes()[s.Pos] != '}' {
							var mk string
							mk, err = s.String()
							if err != nil {
								return result, err
							}
							mk = LowerKey(mk)
							err = s.SkipSpace()
							if err != nil {
								return result, err
							}
							if s.Pos >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos] != ':' {
								return result, scan.ErrBadObject
							}
							s.Pos++
							err = s.SkipSpace()
							if err != nil {
								return result, err
							}
							var mn int64
							mn, err = s.Int64()
							if err != nil {
								return result, err
							}
							result.Mixed[mk] = int(mn)
							err = s.SkipSpace()
							if err != nil {
								return result, err
							}
							if s.Pos >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos] == ',' {
								s.Pos++
								err = s.SkipSpace()
								if err != nil {
									return result, err
								}
								continue
							}
							break
						}
						if s.Bytes()[s.Pos] != '}' {
							return result, scan.ErrBadObject
						}
						s.Pos++
					}
				}
			} else {
				return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
			}
		case 6:
			if key == "lookup" {
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenLookup {
					return result, &validation.DuplicateKeyError{Field: "lookup"}
				}
				seenLookup = true
				{
					err = s.SkipSpace()
					if err != nil {
						return result, err
					}
					if s.Pos >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, err
						}
					}
					if s.Bytes()[s.Pos] == 'n' {
						for ki := 1; ki < 4; ki++ {
							if s.Pos+ki >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos+ki] != "null"[ki] {
								return result, scan.ErrBadLiteral
							}
						}
						s.Pos += 4
						result.Lookup = nil
					} else {
						err = s.ObjectOpen()
						if err != nil {
							return result, err
						}
						err = s.SkipSpace()
						if err != nil {
							return result, err
						}
						if s.Pos >= len(s.Bytes()) {
							if err = s.ReadMore(0); err != nil {
								return result, err
							}
						}
						if s.Bytes()[s.Pos] == '}' {
							if result.Lookup == nil {
								result.Lookup = map[string]int{}
							}
						} else {
							if result.Lookup == nil {
								result.Lookup = make(map[string]int)
							}
						}
						for s.Bytes()[s.Pos] != '}' {
							var mk string
							mk, err = s.String()
							if err != nil {
								return result, err
							}
							if err := KeyShape(mk); err != nil {
								return result, &validation.CustomError{Field: "lookup.key", Name: "@KeyShape", Cause: err}
							}
							err = s.SkipSpace()
							if err != nil {
								return result, err
							}
							if s.Pos >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos] != ':' {
								return result, scan.ErrBadObject
							}
							s.Pos++
							err = s.SkipSpace()
							if err != nil {
								return result, err
							}
							var mn int64
							mn, err = s.Int64()
							if err != nil {
								return result, err
							}
							result.Lookup[mk] = int(mn)
							err = s.SkipSpace()
							if err != nil {
								return result, err
							}
							if s.Pos >= len(s.Bytes()) {
								if err = s.ReadMore(0); err != nil {
									return result, err
								}
							}
							if s.Bytes()[s.Pos] == ',' {
								s.Pos++
								err = s.SkipSpace()
								if err != nil {
									return result, err
								}
								continue
							}
							break
						}
						if s.Bytes()[s.Pos] != '}' {
							return result, scan.ErrBadObject
						}
						s.Pos++
					}
				}
			} else {
				return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
			}
		default:
			return result, &validation.UnknownKeyError{Field: strings.Clone(key)}
		}
		err = s.SkipSpace()
		if err != nil {
			return result, err
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, err
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, err
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, scan.ErrBadObject
	}
}

func (s CustomDiveStruct) JSONSize() int {
	size := 51
	size += len(s.Lookup) * 24
	for k := range s.Lookup {
		size += len(k) * 2
	}
	size += len(s.Mixed) * 24
	for k := range s.Mixed {
		size += len(k) * 2
	}
	if s.Ptr == nil {
		size += 4
	} else {
		size += 20
	}
	if n := len(s.Tags); n > 0 {
		size += n - 1
	}
	for i0 := range s.Tags {
		size += len(s.Tags[i0])*2 + 2
	}
	if n := len(s.Trim); n > 0 {
		size += n - 1
	}
	for i0 := range s.Trim {
		size += len(s.Trim[i0])*2 + 2
	}
	return size
}

func (s CustomDiveStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"lookup\":"...)
	if s.Lookup == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '{')
		{
			first := true
			for k, v := range s.Lookup {
				if first {
					first = false
					dst = append(dst, '"')
				} else {
					dst = append(dst, ",\""...)
				}
				dst = encode.AppendStringNoHTML(dst, k)
				dst = append(dst, ':')
				dst = strconv.AppendInt(dst, int64(v), 10)
			}
		}
		dst = append(dst, '}')
	}
	dst = append(dst, ",\"mixed\":"...)
	if s.Mixed == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '{')
		{
			first := true
			for k, v := range s.Mixed {
				if first {
					first = false
					dst = append(dst, '"')
				} else {
					dst = append(dst, ",\""...)
				}
				dst = encode.AppendStringNoHTML(dst, k)
				dst = append(dst, ':')
				dst = strconv.AppendInt(dst, int64(v), 10)
			}
		}
		dst = append(dst, '}')
	}
	dst = append(dst, ",\"ptr\":"...)
	if s.Ptr == nil {
		dst = append(dst, "null"...)
	} else {
		dst = strconv.AppendInt(dst, int64((*s.Ptr)), 10)
	}
	dst = append(dst, ",\"tags\":"...)
	if s.Tags == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		if len(s.Tags) > 0 {
			dst = append(dst, '"')
			dst = encode.AppendStringNoHTML(dst, s.Tags[0])
			for _, v0 := range s.Tags[1:] {
				dst = append(dst, ",\""...)
				dst = encode.AppendStringNoHTML(dst, v0)
			}
		}
		dst = append(dst, ']')
	}
	dst = append(dst, ",\"trim\":"...)
	if s.Trim == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		if len(s.Trim) > 0 {
			dst = append(dst, '"')
			dst = encode.AppendStringNoHTML(dst, s.Trim[0])
			for _, v0 := range s.Trim[1:] {
				dst = append(dst, ",\""...)
				dst = encode.AppendStringNoHTML(dst, v0)
			}
		}
		dst = append(dst, ']')
	}
	return append(dst, '}'), nil
}
