// Code generated by ggen; DO NOT EDIT.

package integrationtests

import (
	"encoding/json"
	"strings"
	"unsafe"

	"github.com/sirkostya009/ggen"
)

func (recv EmbedStruct) DecodeFrom(data []byte) (result EmbedStruct, i int, err error) {
	result = recv
	if result.Extra != nil {
		clear(result.Extra)
	}
	seenName := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenName {
			result.Name = ""
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "name":
			if seenName {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"name"}}
			}
			seenName = true
			if i >= len(data) || data[i] != '"' {
				return result, i, ggen.NewParseErr("name", i, ggen.ErrExpectString)
			}
			ke := i + 1
			kew := ke + 32
			if kew > len(data) {
				kew = len(data)
			}
			for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
				ke++
			}
			if ke < len(data) && data[ke] == '"' {
				result.Name = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Name, i, err = ggen.String(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("name", i, err)
				}
			}
		default:
			if result.Extra == nil {
				result.Extra = make(map[string]any)
			}
			result.Extra[key], i, err = ggen.Any(data, i)
			if err != nil {
				return result, i, ggen.NewParseErr(key, i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenName {
				result.Name = ""
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv EmbedStruct) DecodeFromStream(s *ggen.Stream) (result EmbedStruct, err error) {
	result = recv
	if result.Extra != nil {
		clear(result.Extra)
	}
	seenName := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenName {
			result.Name = ""
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "name":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("name", s.Offset(), err)
			}
			if seenName {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"name"}}
			}
			seenName = true
			result.Name, err = s.String(true)
			if err != nil {
				return result, ggen.NewParseErr("name", s.Offset(), err)
			}
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			if result.Extra == nil {
				result.Extra = make(map[string]any)
			}
			result.Extra[ownKey], err = s.Any()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenName {
				result.Name = ""
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s EmbedStruct) JSONSize() int {
	size := 11
	size += len(s.Name) * 2
	size += len(s.Extra) * 68
	for k := range s.Extra {
		size += len(k) * 2
	}
	return size
}

func (s EmbedStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	start := len(dst)
	if len(dst) > start {
		dst = append(dst, ',')
	}
	dst = append(dst, "\"name\":\""...)
	dst = ggen.AppendStringNoHTML(dst, s.Name)
	for k, v := range s.Extra {
		if len(dst) > start {
			dst = append(dst, ',')
		}
		dst = append(dst, '"')
		dst = ggen.AppendStringNoHTML(dst, k)
		dst = append(dst, ':')
		if dst, err = ggen.AppendAny(dst, v); err != nil {
			return dst, err
		}
	}
	return append(dst, '}'), nil
}

func (recv EmbedStringsStruct) DecodeFrom(data []byte) (result EmbedStringsStruct, i int, err error) {
	result = recv
	if result.Extra != nil {
		clear(result.Extra)
	}
	seenName := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenName {
			result.Name = ""
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "name":
			if seenName {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"name"}}
			}
			seenName = true
			if i >= len(data) || data[i] != '"' {
				return result, i, ggen.NewParseErr("name", i, ggen.ErrExpectString)
			}
			ke := i + 1
			kew := ke + 32
			if kew > len(data) {
				kew = len(data)
			}
			for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
				ke++
			}
			if ke < len(data) && data[ke] == '"' {
				result.Name = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Name, i, err = ggen.String(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("name", i, err)
				}
			}
		default:
			if result.Extra == nil {
				result.Extra = make(map[string]string)
			}
			result.Extra[key], i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr(key, i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenName {
				result.Name = ""
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv EmbedStringsStruct) DecodeFromStream(s *ggen.Stream) (result EmbedStringsStruct, err error) {
	result = recv
	if result.Extra != nil {
		clear(result.Extra)
	}
	seenName := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenName {
			result.Name = ""
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "name":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("name", s.Offset(), err)
			}
			if seenName {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"name"}}
			}
			seenName = true
			result.Name, err = s.String(true)
			if err != nil {
				return result, ggen.NewParseErr("name", s.Offset(), err)
			}
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			if result.Extra == nil {
				result.Extra = make(map[string]string)
			}
			result.Extra[ownKey], err = s.String(true)
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenName {
				result.Name = ""
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s EmbedStringsStruct) JSONSize() int {
	size := 11
	size += len(s.Name) * 2
	size += len(s.Extra) * 4
	for k, v := range s.Extra {
		size += len(k) * 2
		size += 2
		size += len(v) * 2
	}
	return size
}

func (s EmbedStringsStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	start := len(dst)
	if len(dst) > start {
		dst = append(dst, ',')
	}
	dst = append(dst, "\"name\":\""...)
	dst = ggen.AppendStringNoHTML(dst, s.Name)
	for k, v := range s.Extra {
		if len(dst) > start {
			dst = append(dst, ',')
		}
		dst = append(dst, '"')
		dst = ggen.AppendStringNoHTML(dst, k)
		dst = append(dst, ":\""...)
		dst = ggen.AppendStringNoHTML(dst, v)
	}
	return append(dst, '}'), nil
}

func (recv EmbedStructsStruct) DecodeFrom(data []byte) (result EmbedStructsStruct, i int, err error) {
	result = recv
	if result.Extra != nil {
		clear(result.Extra)
	}
	seenName := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenName {
			result.Name = ""
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "name":
			if seenName {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"name"}}
			}
			seenName = true
			if i >= len(data) || data[i] != '"' {
				return result, i, ggen.NewParseErr("name", i, ggen.ErrExpectString)
			}
			ke := i + 1
			kew := ke + 32
			if kew > len(data) {
				kew = len(data)
			}
			for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
				ke++
			}
			if ke < len(data) && data[ke] == '"' {
				result.Name = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Name, i, err = ggen.String(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("name", i, err)
				}
			}
		default:
			if result.Extra == nil {
				result.Extra = make(map[string]EmbedStruct)
			}
			var entry EmbedStruct
			var entryConsumed int
			entry, entryConsumed, err = entry.DecodeFrom(data[i:])
			i += entryConsumed
			if err != nil {
				return result, i, ggen.NewParseErrShift(key, i, entryConsumed, err)
			}
			result.Extra[key] = entry
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenName {
				result.Name = ""
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv EmbedStructsStruct) DecodeFromStream(s *ggen.Stream) (result EmbedStructsStruct, err error) {
	result = recv
	if result.Extra != nil {
		clear(result.Extra)
	}
	seenName := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenName {
			result.Name = ""
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "name":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("name", s.Offset(), err)
			}
			if seenName {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"name"}}
			}
			seenName = true
			result.Name, err = s.String(true)
			if err != nil {
				return result, ggen.NewParseErr("name", s.Offset(), err)
			}
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			if result.Extra == nil {
				result.Extra = make(map[string]EmbedStruct)
			}
			var entry EmbedStruct
			entry, err = entry.DecodeFromStream(s)
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			result.Extra[ownKey] = entry
		}

		err = s.SkipSpace()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenName {
				result.Name = ""
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s EmbedStructsStruct) JSONSize() int {
	size := 11
	size += len(s.Name) * 2
	size += len(s.Extra) * 4
	for k, v := range s.Extra {
		size += len(k) * 2
		size += v.JSONSize()
	}
	return size
}

func (s EmbedStructsStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	start := len(dst)
	if len(dst) > start {
		dst = append(dst, ',')
	}
	dst = append(dst, "\"name\":\""...)
	dst = ggen.AppendStringNoHTML(dst, s.Name)
	for k, v := range s.Extra {
		if len(dst) > start {
			dst = append(dst, ',')
		}
		dst = append(dst, '"')
		dst = ggen.AppendStringNoHTML(dst, k)
		dst = append(dst, ':')
		if dst, err = v.AppendJSON(dst); err != nil {
			return dst, err
		}
	}
	return append(dst, '}'), nil
}

func (recv EmbedRawStruct) DecodeFrom(data []byte) (result EmbedRawStruct, i int, err error) {
	result = recv
	if result.Extra != nil {
		clear(result.Extra)
	}
	seenName := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenName {
			result.Name = ""
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "name":
			if seenName {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"name"}}
			}
			seenName = true
			if i >= len(data) || data[i] != '"' {
				return result, i, ggen.NewParseErr("name", i, ggen.ErrExpectString)
			}
			ke := i + 1
			kew := ke + 32
			if kew > len(data) {
				kew = len(data)
			}
			for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
				ke++
			}
			if ke < len(data) && data[ke] == '"' {
				result.Name = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Name, i, err = ggen.String(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("name", i, err)
				}
			}
		default:
			if result.Extra == nil {
				result.Extra = make(map[string]json.RawMessage)
			}
			spanStart := i
			i, err = ggen.SkipValue(data, i)
			if err != nil {
				return result, i, ggen.NewParseErr(key, i, err)
			}
			var entry json.RawMessage
			if err = json.Unmarshal(data[spanStart:i], &entry); err != nil {
				return result, i, ggen.NewParseErr(key, i, err)
			}
			result.Extra[key] = entry
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenName {
				result.Name = ""
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv EmbedRawStruct) DecodeFromStream(s *ggen.Stream) (result EmbedRawStruct, err error) {
	result = recv
	if result.Extra != nil {
		clear(result.Extra)
	}
	seenName := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenName {
			result.Name = ""
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "name":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("name", s.Offset(), err)
			}
			if seenName {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"name"}}
			}
			seenName = true
			result.Name, err = s.String(true)
			if err != nil {
				return result, ggen.NewParseErr("name", s.Offset(), err)
			}
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			if result.Extra == nil {
				result.Extra = make(map[string]json.RawMessage)
			}
			span, err := s.CaptureValue()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			var entry json.RawMessage
			if err = json.Unmarshal(span, &entry); err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			result.Extra[ownKey] = entry
		}

		err = s.SkipSpace()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenName {
				result.Name = ""
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s EmbedRawStruct) JSONSize() int {
	size := 11
	size += len(s.Name) * 2
	size += len(s.Extra) * 4
	for k, v := range s.Extra {
		size += len(k) * 2
		if n := len(v); n > 0 {
			size += n
		} else {
			size += 4
		}
	}
	return size
}

func (s EmbedRawStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	start := len(dst)
	if len(dst) > start {
		dst = append(dst, ',')
	}
	dst = append(dst, "\"name\":\""...)
	dst = ggen.AppendStringNoHTML(dst, s.Name)
	for k, v := range s.Extra {
		if len(dst) > start {
			dst = append(dst, ',')
		}
		dst = append(dst, '"')
		dst = ggen.AppendStringNoHTML(dst, k)
		dst = append(dst, ':')
		if len(v) == 0 {
			dst = append(dst, "null"...)
		} else {
			dst = append(dst, v...)
		}
	}
	return append(dst, '}'), nil
}
