// Code generated by ggen; DO NOT EDIT.

package integrationtests

import (
	"math"
	"strconv"
	"strings"
	"unsafe"

	"github.com/sirkostya009/ggen"
)

func (recv PrimStruct) DecodeFrom(data []byte) (result PrimStruct, i int, err error) {
	result = recv
	seenB := false
	seenF32 := false
	seenF64 := false
	seenI := false
	seenI16 := false
	seenI32 := false
	seenI64 := false
	seenI8 := false
	seenStr := false
	seenU := false
	seenU16 := false
	seenU32 := false
	seenU64 := false
	seenU8 := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenB {
			result.B = false
		}
		if !seenF32 {
			result.F32 = 0
		}
		if !seenF64 {
			result.F64 = 0
		}
		if !seenI {
			result.I = 0
		}
		if !seenI16 {
			result.I16 = 0
		}
		if !seenI32 {
			result.I32 = 0
		}
		if !seenI64 {
			result.I64 = 0
		}
		if !seenI8 {
			result.I8 = 0
		}
		if !seenStr {
			result.Str = ""
		}
		if !seenU {
			result.U = 0
		}
		if !seenU16 {
			result.U16 = 0
		}
		if !seenU32 {
			result.U32 = 0
		}
		if !seenU64 {
			result.U64 = 0
		}
		if !seenU8 {
			result.U8 = 0
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "b":
			if seenB {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"b"}}
			}
			seenB = true
			result.B, i, err = ggen.Bool(data, i)
			if err != nil {
				return result, i, ggen.NewParseErr("b", i, err)
			}
		case "f32":
			if seenF32 {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"f32"}}
			}
			seenF32 = true
			var fv float64
			fv, i, err = ggen.Float64(data, i)
			if err != nil {
				return result, i, ggen.NewParseErr("f32", i, err)
			}
			if math.IsInf(float64(float32(fv)), 0) {
				return result, i, ggen.NewParseErr("f32", i, ggen.ErrNumberOverflow)
			}
			result.F32 = float32(fv)
		case "f64":
			if seenF64 {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"f64"}}
			}
			seenF64 = true
			result.F64, i, err = ggen.Float64(data, i)
			if err != nil {
				return result, i, ggen.NewParseErr("f64", i, err)
			}
		case "i":
			if seenI {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"i"}}
			}
			seenI = true
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("i", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("i", i, ggen.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = ggen.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, ggen.NewParseErr("i", i, ggen.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("i", i, ggen.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == ggen.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			result.I = int(n)
		case "i16":
			if seenI16 {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"i16"}}
			}
			seenI16 = true
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("i16", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("i16", i, ggen.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = ggen.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, ggen.NewParseErr("i16", i, ggen.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("i16", i, ggen.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == ggen.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			if n < math.MinInt16 || n > math.MaxInt16 {
				return result, i, ggen.NewParseErr("i16", i, ggen.ErrNumberOverflow)
			}
			result.I16 = int16(n)
		case "i32":
			if seenI32 {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"i32"}}
			}
			seenI32 = true
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("i32", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("i32", i, ggen.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = ggen.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, ggen.NewParseErr("i32", i, ggen.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("i32", i, ggen.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == ggen.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			if n < math.MinInt32 || n > math.MaxInt32 {
				return result, i, ggen.NewParseErr("i32", i, ggen.ErrNumberOverflow)
			}
			result.I32 = int32(n)
		case "i64":
			if seenI64 {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"i64"}}
			}
			seenI64 = true
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("i64", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("i64", i, ggen.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = ggen.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, ggen.NewParseErr("i64", i, ggen.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("i64", i, ggen.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == ggen.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			result.I64 = n
		case "i8":
			if seenI8 {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"i8"}}
			}
			seenI8 = true
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("i8", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("i8", i, ggen.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = ggen.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, ggen.NewParseErr("i8", i, ggen.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("i8", i, ggen.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == ggen.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			if n < math.MinInt8 || n > math.MaxInt8 {
				return result, i, ggen.NewParseErr("i8", i, ggen.ErrNumberOverflow)
			}
			result.I8 = int8(n)
		case "str":
			if seenStr {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"str"}}
			}
			seenStr = true
			if i >= len(data) || data[i] != '"' {
				return result, i, ggen.NewParseErr("str", i, ggen.ErrExpectString)
			}
			ke := i + 1
			kew := ke + 32
			if kew > len(data) {
				kew = len(data)
			}
			for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
				ke++
			}
			if ke < len(data) && data[ke] == '"' {
				result.Str = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Str, i, err = ggen.String(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("str", i, err)
				}
			}
		case "u":
			if seenU {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"u"}}
			}
			seenU = true
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("u", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("u", i, ggen.ErrBadNumber)
			}
			var n uint64
			de := i + 19
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				n = n*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if n > ggen.Uint64Limit/10 || (n == ggen.Uint64Limit/10 && d > ggen.Uint64Limit%10) {
					return result, i, ggen.NewParseErr("u", i, ggen.ErrNumberOverflow)
				}
				n = n*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("u", i, ggen.ErrBadNumber)
				}
			}
			result.U = uint(n)
		case "u16":
			if seenU16 {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"u16"}}
			}
			seenU16 = true
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("u16", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("u16", i, ggen.ErrBadNumber)
			}
			var n uint64
			de := i + 19
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				n = n*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if n > ggen.Uint64Limit/10 || (n == ggen.Uint64Limit/10 && d > ggen.Uint64Limit%10) {
					return result, i, ggen.NewParseErr("u16", i, ggen.ErrNumberOverflow)
				}
				n = n*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("u16", i, ggen.ErrBadNumber)
				}
			}
			if n > math.MaxUint16 {
				return result, i, ggen.NewParseErr("u16", i, ggen.ErrNumberOverflow)
			}
			result.U16 = uint16(n)
		case "u32":
			if seenU32 {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"u32"}}
			}
			seenU32 = true
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("u32", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("u32", i, ggen.ErrBadNumber)
			}
			var n uint64
			de := i + 19
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				n = n*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if n > ggen.Uint64Limit/10 || (n == ggen.Uint64Limit/10 && d > ggen.Uint64Limit%10) {
					return result, i, ggen.NewParseErr("u32", i, ggen.ErrNumberOverflow)
				}
				n = n*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("u32", i, ggen.ErrBadNumber)
				}
			}
			if n > math.MaxUint32 {
				return result, i, ggen.NewParseErr("u32", i, ggen.ErrNumberOverflow)
			}
			result.U32 = uint32(n)
		case "u64":
			if seenU64 {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"u64"}}
			}
			seenU64 = true
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("u64", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("u64", i, ggen.ErrBadNumber)
			}
			var n uint64
			de := i + 19
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				n = n*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if n > ggen.Uint64Limit/10 || (n == ggen.Uint64Limit/10 && d > ggen.Uint64Limit%10) {
					return result, i, ggen.NewParseErr("u64", i, ggen.ErrNumberOverflow)
				}
				n = n*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("u64", i, ggen.ErrBadNumber)
				}
			}
			result.U64 = n
		case "u8":
			if seenU8 {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"u8"}}
			}
			seenU8 = true
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("u8", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("u8", i, ggen.ErrBadNumber)
			}
			var n uint64
			de := i + 19
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				n = n*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if n > ggen.Uint64Limit/10 || (n == ggen.Uint64Limit/10 && d > ggen.Uint64Limit%10) {
					return result, i, ggen.NewParseErr("u8", i, ggen.ErrNumberOverflow)
				}
				n = n*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("u8", i, ggen.ErrBadNumber)
				}
			}
			if n > math.MaxUint8 {
				return result, i, ggen.NewParseErr("u8", i, ggen.ErrNumberOverflow)
			}
			result.U8 = uint8(n)
		default:
			return result, i, &ggen.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenB {
				result.B = false
			}
			if !seenF32 {
				result.F32 = 0
			}
			if !seenF64 {
				result.F64 = 0
			}
			if !seenI {
				result.I = 0
			}
			if !seenI16 {
				result.I16 = 0
			}
			if !seenI32 {
				result.I32 = 0
			}
			if !seenI64 {
				result.I64 = 0
			}
			if !seenI8 {
				result.I8 = 0
			}
			if !seenStr {
				result.Str = ""
			}
			if !seenU {
				result.U = 0
			}
			if !seenU16 {
				result.U16 = 0
			}
			if !seenU32 {
				result.U32 = 0
			}
			if !seenU64 {
				result.U64 = 0
			}
			if !seenU8 {
				result.U8 = 0
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv PrimStruct) DecodeFromStream(s *ggen.Stream) (result PrimStruct, err error) {
	result = recv
	seenB := false
	seenF32 := false
	seenF64 := false
	seenI := false
	seenI16 := false
	seenI32 := false
	seenI64 := false
	seenI8 := false
	seenStr := false
	seenU := false
	seenU16 := false
	seenU32 := false
	seenU64 := false
	seenU8 := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenB {
			result.B = false
		}
		if !seenF32 {
			result.F32 = 0
		}
		if !seenF64 {
			result.F64 = 0
		}
		if !seenI {
			result.I = 0
		}
		if !seenI16 {
			result.I16 = 0
		}
		if !seenI32 {
			result.I32 = 0
		}
		if !seenI64 {
			result.I64 = 0
		}
		if !seenI8 {
			result.I8 = 0
		}
		if !seenStr {
			result.Str = ""
		}
		if !seenU {
			result.U = 0
		}
		if !seenU16 {
			result.U16 = 0
		}
		if !seenU32 {
			result.U32 = 0
		}
		if !seenU64 {
			result.U64 = 0
		}
		if !seenU8 {
			result.U8 = 0
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "b":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("b", s.Offset(), err)
			}
			if seenB {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"b"}}
			}
			seenB = true
			result.B, err = s.Bool()
			if err != nil {
				return result, ggen.NewParseErr("b", s.Offset(), err)
			}
		case "f32":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("f32", s.Offset(), err)
			}
			if seenF32 {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"f32"}}
			}
			seenF32 = true
			var fv float64
			fv, err = s.Float64()
			if err != nil {
				return result, ggen.NewParseErr("f32", s.Offset(), err)
			}
			if math.IsInf(float64(float32(fv)), 0) {
				return result, ggen.NewParseErr("f32", s.Offset(), ggen.ErrNumberOverflow)
			}
			result.F32 = float32(fv)
		case "f64":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("f64", s.Offset(), err)
			}
			if seenF64 {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"f64"}}
			}
			seenF64 = true
			result.F64, err = s.Float64()
			if err != nil {
				return result, ggen.NewParseErr("f64", s.Offset(), err)
			}
		case "i":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("i", s.Offset(), err)
			}
			if seenI {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"i"}}
			}
			seenI = true
			var iv int64
			iv, err = s.Int64()
			if err != nil {
				return result, ggen.NewParseErr("i", s.Offset(), err)
			}
			result.I = int(iv)
		case "i16":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("i16", s.Offset(), err)
			}
			if seenI16 {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"i16"}}
			}
			seenI16 = true
			var iv int64
			iv, err = s.Int64()
			if err != nil {
				return result, ggen.NewParseErr("i16", s.Offset(), err)
			}
			if iv < math.MinInt16 || iv > math.MaxInt16 {
				return result, ggen.NewParseErr("i16", s.Offset(), ggen.ErrNumberOverflow)
			}
			result.I16 = int16(iv)
		case "i32":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("i32", s.Offset(), err)
			}
			if seenI32 {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"i32"}}
			}
			seenI32 = true
			var iv int64
			iv, err = s.Int64()
			if err != nil {
				return result, ggen.NewParseErr("i32", s.Offset(), err)
			}
			if iv < math.MinInt32 || iv > math.MaxInt32 {
				return result, ggen.NewParseErr("i32", s.Offset(), ggen.ErrNumberOverflow)
			}
			result.I32 = int32(iv)
		case "i64":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("i64", s.Offset(), err)
			}
			if seenI64 {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"i64"}}
			}
			seenI64 = true
			result.I64, err = s.Int64()
			if err != nil {
				return result, ggen.NewParseErr("i64", s.Offset(), err)
			}
		case "i8":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("i8", s.Offset(), err)
			}
			if seenI8 {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"i8"}}
			}
			seenI8 = true
			var iv int64
			iv, err = s.Int64()
			if err != nil {
				return result, ggen.NewParseErr("i8", s.Offset(), err)
			}
			if iv < math.MinInt8 || iv > math.MaxInt8 {
				return result, ggen.NewParseErr("i8", s.Offset(), ggen.ErrNumberOverflow)
			}
			result.I8 = int8(iv)
		case "str":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("str", s.Offset(), err)
			}
			if seenStr {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"str"}}
			}
			seenStr = true
			result.Str, err = s.String(true)
			if err != nil {
				return result, ggen.NewParseErr("str", s.Offset(), err)
			}
		case "u":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("u", s.Offset(), err)
			}
			if seenU {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"u"}}
			}
			seenU = true
			var uv uint64
			uv, err = s.Uint64()
			if err != nil {
				return result, ggen.NewParseErr("u", s.Offset(), err)
			}
			result.U = uint(uv)
		case "u16":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("u16", s.Offset(), err)
			}
			if seenU16 {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"u16"}}
			}
			seenU16 = true
			var uv uint64
			uv, err = s.Uint64()
			if err != nil {
				return result, ggen.NewParseErr("u16", s.Offset(), err)
			}
			if uv > math.MaxUint16 {
				return result, ggen.NewParseErr("u16", s.Offset(), ggen.ErrNumberOverflow)
			}
			result.U16 = uint16(uv)
		case "u32":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("u32", s.Offset(), err)
			}
			if seenU32 {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"u32"}}
			}
			seenU32 = true
			var uv uint64
			uv, err = s.Uint64()
			if err != nil {
				return result, ggen.NewParseErr("u32", s.Offset(), err)
			}
			if uv > math.MaxUint32 {
				return result, ggen.NewParseErr("u32", s.Offset(), ggen.ErrNumberOverflow)
			}
			result.U32 = uint32(uv)
		case "u64":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("u64", s.Offset(), err)
			}
			if seenU64 {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"u64"}}
			}
			seenU64 = true
			result.U64, err = s.Uint64()
			if err != nil {
				return result, ggen.NewParseErr("u64", s.Offset(), err)
			}
		case "u8":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("u8", s.Offset(), err)
			}
			if seenU8 {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"u8"}}
			}
			seenU8 = true
			var uv uint64
			uv, err = s.Uint64()
			if err != nil {
				return result, ggen.NewParseErr("u8", s.Offset(), err)
			}
			if uv > math.MaxUint8 {
				return result, ggen.NewParseErr("u8", s.Offset(), ggen.ErrNumberOverflow)
			}
			result.U8 = uint8(uv)
		default:
			return result, &ggen.UnknownKeyError{Pos: s.Offset(), Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenB {
				result.B = false
			}
			if !seenF32 {
				result.F32 = 0
			}
			if !seenF64 {
				result.F64 = 0
			}
			if !seenI {
				result.I = 0
			}
			if !seenI16 {
				result.I16 = 0
			}
			if !seenI32 {
				result.I32 = 0
			}
			if !seenI64 {
				result.I64 = 0
			}
			if !seenI8 {
				result.I8 = 0
			}
			if !seenStr {
				result.Str = ""
			}
			if !seenU {
				result.U = 0
			}
			if !seenU16 {
				result.U16 = 0
			}
			if !seenU32 {
				result.U32 = 0
			}
			if !seenU64 {
				result.U64 = 0
			}
			if !seenU8 {
				result.U8 = 0
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s PrimStruct) JSONSize() int {
	size := 348
	size += len(s.Str) * 2
	return size
}

func (s PrimStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"b\":"...)
	dst = strconv.AppendBool(dst, s.B)
	dst = append(dst, ",\"f32\":"...)
	if dst, err = ggen.AppendFloat(dst, float64(s.F32), 32); err != nil {
		return dst, err
	}
	dst = append(dst, ",\"f64\":"...)
	if dst, err = ggen.AppendFloat(dst, s.F64, 64); err != nil {
		return dst, err
	}
	dst = append(dst, ",\"i\":"...)
	dst = strconv.AppendInt(dst, int64(s.I), 10)
	dst = append(dst, ",\"i16\":"...)
	dst = strconv.AppendInt(dst, int64(s.I16), 10)
	dst = append(dst, ",\"i32\":"...)
	dst = strconv.AppendInt(dst, int64(s.I32), 10)
	dst = append(dst, ",\"i64\":"...)
	dst = strconv.AppendInt(dst, s.I64, 10)
	dst = append(dst, ",\"i8\":"...)
	dst = strconv.AppendInt(dst, int64(s.I8), 10)
	dst = append(dst, ",\"str\":\""...)
	dst = ggen.AppendStringNoHTML(dst, s.Str)
	dst = append(dst, ",\"u\":"...)
	dst = strconv.AppendUint(dst, uint64(s.U), 10)
	dst = append(dst, ",\"u16\":"...)
	dst = strconv.AppendUint(dst, uint64(s.U16), 10)
	dst = append(dst, ",\"u32\":"...)
	dst = strconv.AppendUint(dst, uint64(s.U32), 10)
	dst = append(dst, ",\"u64\":"...)
	dst = strconv.AppendUint(dst, s.U64, 10)
	dst = append(dst, ",\"u8\":"...)
	dst = strconv.AppendUint(dst, uint64(s.U8), 10)
	return append(dst, '}'), nil
}
