// Code generated by ggen; DO NOT EDIT.

package integrationtests

import (
	"unsafe"

	"github.com/sirkostya009/ggen/decode/validation"
	"github.com/sirkostya009/ggen/encode"
	"github.com/sirkostya009/ggen/scan"
)

func (result IgnoreUnknownStruct) DecodeFrom(data []byte) (IgnoreUnknownStruct, int, error) {
	i := 0
	var err error
	_ = err
	seenName := false
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, scan.ErrBadObject
	}
	i++
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		return result, i + 1, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, scan.ErrExpectString
		}
		{
			ke := i + 1
			for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
				ke++
			}
			if ke >= len(data) {
				return result, i, scan.ErrUnterminated
			}
			if data[ke] < 0x20 {
				return result, i, scan.ErrBadString
			}
			if data[ke] == '"' {
				key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				key, i, err = scan.String(data, i)
				if err != nil {
					return result, i, err
				}
			}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, scan.ErrBadObject
		}
		i++
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch len(key) {
		case 4:
			if key == "name" {
				if seenName {
					return result, i, &validation.DuplicateKeyError{Field: "name"}
				}
				seenName = true
				if i >= len(data) || data[i] != '"' {
					return result, i, scan.ErrExpectString
				}
				{
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, scan.ErrUnterminated
					}
					if data[ke] < 0x20 {
						return result, i, scan.ErrBadString
					}
					if data[ke] == '"' {
						result.Name = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.Name, i, err = scan.String(data, i)
						if err != nil {
							return result, i, err
						}
					}
				}
			} else {
				i, err = scan.SkipValue(data, i)
				if err != nil {
					return result, i, err
				}
			}
		default:
			i, err = scan.SkipValue(data, i)
			if err != nil {
				return result, i, err
			}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, scan.ErrBadObject
		}
		if data[i] == ',' {
			i++
			for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			return result, i + 1, nil
		}
		return result, i, scan.ErrBadObject
	}
}

func (result IgnoreUnknownStruct) DecodeStreamFrom(s *scan.Stream) (IgnoreUnknownStruct, error) {
	seenName := false
	err := s.ObjectOpen()
	if err != nil {
		return result, err
	}
	err = s.SkipSpace()
	if err != nil {
		return result, err
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, err
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, err
		}
		switch len(key) {
		case 4:
			if key == "name" {
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				if seenName {
					return result, &validation.DuplicateKeyError{Field: "name"}
				}
				seenName = true
				result.Name, err = s.String()
				if err != nil {
					return result, err
				}
			} else {
				err = s.ConsumeColon()
				if err != nil {
					return result, err
				}
				err = s.SkipValue()
				if err != nil {
					return result, err
				}
			}
		default:
			err = s.ConsumeColon()
			if err != nil {
				return result, err
			}
			err = s.SkipValue()
			if err != nil {
				return result, err
			}
		}
		err = s.SkipSpace()
		if err != nil {
			return result, err
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, err
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, err
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, scan.ErrBadObject
	}
}

func (s IgnoreUnknownStruct) JSONSize() int {
	size := 11
	size += len(s.Name) * 2
	return size
}

func (s IgnoreUnknownStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"name\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Name)
	return append(dst, '}'), nil
}
