// Code generated by ggen; DO NOT EDIT.

//go:build goexperiment.jsonv2

package integrationtests

import (
	"strings"
	"unsafe"

	"github.com/sirkostya009/ggen/decode"
	"github.com/sirkostya009/ggen/decode/validation"
	"github.com/sirkostya009/ggen/encode"
	"github.com/sirkostya009/ggen/scan"
)

func (result HugeStringStruct) DecodeFrom(data []byte) (HugeStringStruct, int, error) {
	i := 0
	var err error
	_ = err
	seenBig := false
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		{
			ke := i + 1
			for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
				ke++
			}
			if ke >= len(data) {
				return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
			}
			if data[ke] < 0x20 {
				return result, i, decode.NewParseErr("", i, scan.ErrBadString)
			}
			if data[ke] == '"' {
				key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				key, i, err = scan.String(data, i)
				if err != nil {
					return result, i, decode.NewParseErr("", i, err)
				}
			}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch len(key) {
		case 3:
			if key == "big" {
				if seenBig {
					return result, i, &validation.DuplicateKeyError{Path: []string{"big"}}
				}
				seenBig = true
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("big", i, scan.ErrExpectString)
				}
				{
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("big", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("big", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						result.Big = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.Big, i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("big", i, err)
						}
					}
				}
			} else {
				return result, i, &validation.UnknownKeyError{Path: []string{key}}
			}
		default:
			return result, i, &validation.UnknownKeyError{Path: []string{key}}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (result HugeStringStruct) DecodeFromStream(s *scan.Stream) (HugeStringStruct, error) {
	seenBig := false
	err := s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch len(key) {
		case 3:
			if key == "big" {
				err = s.ConsumeColon()
				if err != nil {
					return result, decode.NewParseErr("big", s.Pos, err)
				}
				if seenBig {
					return result, &validation.DuplicateKeyError{Path: []string{"big"}}
				}
				seenBig = true
				result.Big, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("big", s.Pos, err)
				}
			} else {
				return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
			}
		default:
			return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s HugeStringStruct) JSONSize() int {
	size := 10
	size += len(s.Big) * 2
	return size
}

func (s HugeStringStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"big\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Big)
	return append(dst, '}'), nil
}

func (result SequentialStringsStruct) DecodeFrom(data []byte) (SequentialStringsStruct, int, error) {
	i := 0
	var err error
	_ = err
	seenA := false
	seenB := false
	seenC := false
	seenD := false
	seenE := false
	seenF := false
	seenG := false
	seenH := false
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		{
			ke := i + 1
			for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
				ke++
			}
			if ke >= len(data) {
				return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
			}
			if data[ke] < 0x20 {
				return result, i, decode.NewParseErr("", i, scan.ErrBadString)
			}
			if data[ke] == '"' {
				key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				key, i, err = scan.String(data, i)
				if err != nil {
					return result, i, decode.NewParseErr("", i, err)
				}
			}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch len(key) {
		case 1:
			switch key {
			case "a":
				if seenA {
					return result, i, &validation.DuplicateKeyError{Path: []string{"a"}}
				}
				seenA = true
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("a", i, scan.ErrExpectString)
				}
				{
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("a", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("a", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						result.A = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.A, i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("a", i, err)
						}
					}
				}
			case "b":
				if seenB {
					return result, i, &validation.DuplicateKeyError{Path: []string{"b"}}
				}
				seenB = true
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("b", i, scan.ErrExpectString)
				}
				{
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("b", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("b", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						result.B = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.B, i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("b", i, err)
						}
					}
				}
			case "c":
				if seenC {
					return result, i, &validation.DuplicateKeyError{Path: []string{"c"}}
				}
				seenC = true
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("c", i, scan.ErrExpectString)
				}
				{
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("c", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("c", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						result.C = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.C, i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("c", i, err)
						}
					}
				}
			case "d":
				if seenD {
					return result, i, &validation.DuplicateKeyError{Path: []string{"d"}}
				}
				seenD = true
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("d", i, scan.ErrExpectString)
				}
				{
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("d", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("d", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						result.D = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.D, i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("d", i, err)
						}
					}
				}
			case "e":
				if seenE {
					return result, i, &validation.DuplicateKeyError{Path: []string{"e"}}
				}
				seenE = true
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("e", i, scan.ErrExpectString)
				}
				{
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("e", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("e", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						result.E = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.E, i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("e", i, err)
						}
					}
				}
			case "f":
				if seenF {
					return result, i, &validation.DuplicateKeyError{Path: []string{"f"}}
				}
				seenF = true
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("f", i, scan.ErrExpectString)
				}
				{
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("f", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("f", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						result.F = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.F, i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("f", i, err)
						}
					}
				}
			case "g":
				if seenG {
					return result, i, &validation.DuplicateKeyError{Path: []string{"g"}}
				}
				seenG = true
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("g", i, scan.ErrExpectString)
				}
				{
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("g", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("g", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						result.G = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.G, i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("g", i, err)
						}
					}
				}
			case "h":
				if seenH {
					return result, i, &validation.DuplicateKeyError{Path: []string{"h"}}
				}
				seenH = true
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("h", i, scan.ErrExpectString)
				}
				{
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("h", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("h", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						result.H = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.H, i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("h", i, err)
						}
					}
				}
			default:
				return result, i, &validation.UnknownKeyError{Path: []string{key}}
			}
		default:
			return result, i, &validation.UnknownKeyError{Path: []string{key}}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (result SequentialStringsStruct) DecodeFromStream(s *scan.Stream) (SequentialStringsStruct, error) {
	seenA := false
	seenB := false
	seenC := false
	seenD := false
	seenE := false
	seenF := false
	seenG := false
	seenH := false
	err := s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch len(key) {
		case 1:
			switch key {
			case "a":
				err = s.ConsumeColon()
				if err != nil {
					return result, decode.NewParseErr("a", s.Pos, err)
				}
				if seenA {
					return result, &validation.DuplicateKeyError{Path: []string{"a"}}
				}
				seenA = true
				result.A, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("a", s.Pos, err)
				}
			case "b":
				err = s.ConsumeColon()
				if err != nil {
					return result, decode.NewParseErr("b", s.Pos, err)
				}
				if seenB {
					return result, &validation.DuplicateKeyError{Path: []string{"b"}}
				}
				seenB = true
				result.B, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("b", s.Pos, err)
				}
			case "c":
				err = s.ConsumeColon()
				if err != nil {
					return result, decode.NewParseErr("c", s.Pos, err)
				}
				if seenC {
					return result, &validation.DuplicateKeyError{Path: []string{"c"}}
				}
				seenC = true
				result.C, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("c", s.Pos, err)
				}
			case "d":
				err = s.ConsumeColon()
				if err != nil {
					return result, decode.NewParseErr("d", s.Pos, err)
				}
				if seenD {
					return result, &validation.DuplicateKeyError{Path: []string{"d"}}
				}
				seenD = true
				result.D, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("d", s.Pos, err)
				}
			case "e":
				err = s.ConsumeColon()
				if err != nil {
					return result, decode.NewParseErr("e", s.Pos, err)
				}
				if seenE {
					return result, &validation.DuplicateKeyError{Path: []string{"e"}}
				}
				seenE = true
				result.E, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("e", s.Pos, err)
				}
			case "f":
				err = s.ConsumeColon()
				if err != nil {
					return result, decode.NewParseErr("f", s.Pos, err)
				}
				if seenF {
					return result, &validation.DuplicateKeyError{Path: []string{"f"}}
				}
				seenF = true
				result.F, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("f", s.Pos, err)
				}
			case "g":
				err = s.ConsumeColon()
				if err != nil {
					return result, decode.NewParseErr("g", s.Pos, err)
				}
				if seenG {
					return result, &validation.DuplicateKeyError{Path: []string{"g"}}
				}
				seenG = true
				result.G, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("g", s.Pos, err)
				}
			case "h":
				err = s.ConsumeColon()
				if err != nil {
					return result, decode.NewParseErr("h", s.Pos, err)
				}
				if seenH {
					return result, &validation.DuplicateKeyError{Path: []string{"h"}}
				}
				seenH = true
				result.H, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("h", s.Pos, err)
				}
			default:
				return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
			}
		default:
			return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s SequentialStringsStruct) JSONSize() int {
	size := 57
	size += len(s.A) * 2
	size += len(s.B) * 2
	size += len(s.C) * 2
	size += len(s.D) * 2
	size += len(s.E) * 2
	size += len(s.F) * 2
	size += len(s.G) * 2
	size += len(s.H) * 2
	return size
}

func (s SequentialStringsStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"a\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.A)
	dst = append(dst, ",\"b\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.B)
	dst = append(dst, ",\"c\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.C)
	dst = append(dst, ",\"d\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.D)
	dst = append(dst, ",\"e\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.E)
	dst = append(dst, ",\"f\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.F)
	dst = append(dst, ",\"g\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.G)
	dst = append(dst, ",\"h\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.H)
	return append(dst, '}'), nil
}

func (result UnknownErrorStruct) DecodeFrom(data []byte) (UnknownErrorStruct, int, error) {
	i := 0
	var err error
	_ = err
	seenName := false
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		{
			ke := i + 1
			for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
				ke++
			}
			if ke >= len(data) {
				return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
			}
			if data[ke] < 0x20 {
				return result, i, decode.NewParseErr("", i, scan.ErrBadString)
			}
			if data[ke] == '"' {
				key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				key, i, err = scan.String(data, i)
				if err != nil {
					return result, i, decode.NewParseErr("", i, err)
				}
			}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch len(key) {
		case 4:
			if key == "name" {
				if seenName {
					return result, i, &validation.DuplicateKeyError{Path: []string{"name"}}
				}
				seenName = true
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("name", i, scan.ErrExpectString)
				}
				{
					ke := i + 1
					for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
						ke++
					}
					if ke >= len(data) {
						return result, i, decode.NewParseErr("name", i, scan.ErrUnterminated)
					}
					if data[ke] < 0x20 {
						return result, i, decode.NewParseErr("name", i, scan.ErrBadString)
					}
					if data[ke] == '"' {
						result.Name = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.Name, i, err = scan.String(data, i)
						if err != nil {
							return result, i, decode.NewParseErr("name", i, err)
						}
					}
				}
			} else {
				return result, i, &validation.UnknownKeyError{Path: []string{key}}
			}
		default:
			return result, i, &validation.UnknownKeyError{Path: []string{key}}
		}
		for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (result UnknownErrorStruct) DecodeFromStream(s *scan.Stream) (UnknownErrorStruct, error) {
	seenName := false
	err := s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch len(key) {
		case 4:
			if key == "name" {
				err = s.ConsumeColon()
				if err != nil {
					return result, decode.NewParseErr("name", s.Pos, err)
				}
				if seenName {
					return result, &validation.DuplicateKeyError{Path: []string{"name"}}
				}
				seenName = true
				result.Name, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("name", s.Pos, err)
				}
			} else {
				return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
			}
		default:
			return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s UnknownErrorStruct) JSONSize() int {
	size := 11
	size += len(s.Name) * 2
	return size
}

func (s UnknownErrorStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"name\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Name)
	return append(dst, '}'), nil
}
