// Code generated by ggen; DO NOT EDIT.

package integrationtests

import (
	"database/sql"
	"math"
	"strconv"
	"strings"
	"time"
	"unsafe"

	"github.com/sirkostya009/ggen/decode"
	"github.com/sirkostya009/ggen/decode/validation"
	"github.com/sirkostya009/ggen/encode"
	"github.com/sirkostya009/ggen/scan"
)

func (recv SQLNullStringStruct) DecodeFrom(data []byte) (result SQLNullStringStruct, i int, err error) {
	result = recv
	seenS := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "s":
			if seenS {
				return result, i, &validation.DuplicateKeyError{Path: []string{"s"}}
			}
			seenS = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.S = sql.NullString{}
				i += 4
			} else {
				var nv string
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("s", i, scan.ErrExpectString)
				}
				ke := i + 1
				for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
					ke++
				}
				if ke >= len(data) {
					return result, i, decode.NewParseErr("s", i, scan.ErrUnterminated)
				}
				if data[ke] < 0x20 {
					return result, i, decode.NewParseErr("s", i, scan.ErrBadString)
				}
				if data[ke] == '"' {
					nv = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
					i = ke + 1
				} else {
					nv, i, err = scan.String(data, i)
					if err != nil {
						return result, i, decode.NewParseErr("s", i, err)
					}
				}

				result.S = sql.NullString{String: nv, Valid: true}
			}
		default:
			return result, i, &validation.UnknownKeyError{Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv SQLNullStringStruct) DecodeFromStream(s *scan.Stream) (result SQLNullStringStruct, err error) {
	result = recv
	seenS := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "s":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("s", s.Pos, err)
			}
			if seenS {
				return result, &validation.DuplicateKeyError{Path: []string{"s"}}
			}
			seenS = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("s", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("s", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("s", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.S = sql.NullString{}
				s.Pos += 4
			} else {
				var nv string
				nv, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("s", s.Pos, err)
				}

				result.S = sql.NullString{String: nv, Valid: true}
			}
		default:
			return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s SQLNullStringStruct) JSONSize() int {
	size := 10
	size += len(s.S.String) * 2
	return size
}

func (s SQLNullStringStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"s\":"...)
	if !s.S.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '"')
		dst = encode.AppendStringNoHTML(dst, s.S.String)
	}
	return append(dst, '}'), nil
}

func (recv SQLNullInt64Struct) DecodeFrom(data []byte) (result SQLNullInt64Struct, i int, err error) {
	result = recv
	seenI := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "i":
			if seenI {
				return result, i, &validation.DuplicateKeyError{Path: []string{"i"}}
			}
			seenI = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.I = sql.NullInt64{}
				i += 4
			} else {
				var nv int64
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, decode.NewParseErr("i", i, scan.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = scan.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, decode.NewParseErr("i", i, scan.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, decode.NewParseErr("i", i, scan.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == scan.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				nv = n

				result.I = sql.NullInt64{Int64: nv, Valid: true}
			}
		default:
			return result, i, &validation.UnknownKeyError{Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv SQLNullInt64Struct) DecodeFromStream(s *scan.Stream) (result SQLNullInt64Struct, err error) {
	result = recv
	seenI := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "i":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("i", s.Pos, err)
			}
			if seenI {
				return result, &validation.DuplicateKeyError{Path: []string{"i"}}
			}
			seenI = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("i", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("i", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("i", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.I = sql.NullInt64{}
				s.Pos += 4
			} else {
				var nv int64
				nv, err = s.Int64()
				if err != nil {
					return result, decode.NewParseErr("i", s.Pos, err)
				}

				result.I = sql.NullInt64{Int64: nv, Valid: true}
			}
		default:
			return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s SQLNullInt64Struct) JSONSize() int {
	size := 26
	return size
}

func (s SQLNullInt64Struct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"i\":"...)
	if !s.I.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = strconv.AppendInt(dst, s.I.Int64, 10)
	}
	return append(dst, '}'), nil
}

func (recv SQLNullInt32Struct) DecodeFrom(data []byte) (result SQLNullInt32Struct, i int, err error) {
	result = recv
	seenI32 := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "i32":
			if seenI32 {
				return result, i, &validation.DuplicateKeyError{Path: []string{"i32"}}
			}
			seenI32 = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.I32 = sql.NullInt32{}
				i += 4
			} else {
				var nv int32
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, decode.NewParseErr("i32", i, scan.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = scan.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, decode.NewParseErr("i32", i, scan.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, decode.NewParseErr("i32", i, scan.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == scan.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				nv = int32(n)

				result.I32 = sql.NullInt32{Int32: nv, Valid: true}
			}
		default:
			return result, i, &validation.UnknownKeyError{Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv SQLNullInt32Struct) DecodeFromStream(s *scan.Stream) (result SQLNullInt32Struct, err error) {
	result = recv
	seenI32 := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "i32":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("i32", s.Pos, err)
			}
			if seenI32 {
				return result, &validation.DuplicateKeyError{Path: []string{"i32"}}
			}
			seenI32 = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("i32", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("i32", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("i32", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.I32 = sql.NullInt32{}
				s.Pos += 4
			} else {
				var nv int64
				nv, err = s.Int64()
				if err != nil {
					return result, decode.NewParseErr("i32", s.Pos, err)
				}

				result.I32 = sql.NullInt32{Int32: int32(nv), Valid: true}
			}
		default:
			return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s SQLNullInt32Struct) JSONSize() int {
	size := 28
	return size
}

func (s SQLNullInt32Struct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"i32\":"...)
	if !s.I32.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = strconv.AppendInt(dst, int64(s.I32.Int32), 10)
	}
	return append(dst, '}'), nil
}

func (recv SQLNullInt16Struct) DecodeFrom(data []byte) (result SQLNullInt16Struct, i int, err error) {
	result = recv
	seenI16 := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "i16":
			if seenI16 {
				return result, i, &validation.DuplicateKeyError{Path: []string{"i16"}}
			}
			seenI16 = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.I16 = sql.NullInt16{}
				i += 4
			} else {
				var nv int16
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, decode.NewParseErr("i16", i, scan.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = scan.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, decode.NewParseErr("i16", i, scan.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, decode.NewParseErr("i16", i, scan.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == scan.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				nv = int16(n)

				result.I16 = sql.NullInt16{Int16: nv, Valid: true}
			}
		default:
			return result, i, &validation.UnknownKeyError{Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv SQLNullInt16Struct) DecodeFromStream(s *scan.Stream) (result SQLNullInt16Struct, err error) {
	result = recv
	seenI16 := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "i16":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("i16", s.Pos, err)
			}
			if seenI16 {
				return result, &validation.DuplicateKeyError{Path: []string{"i16"}}
			}
			seenI16 = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("i16", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("i16", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("i16", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.I16 = sql.NullInt16{}
				s.Pos += 4
			} else {
				var nv int64
				nv, err = s.Int64()
				if err != nil {
					return result, decode.NewParseErr("i16", s.Pos, err)
				}

				result.I16 = sql.NullInt16{Int16: int16(nv), Valid: true}
			}
		default:
			return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s SQLNullInt16Struct) JSONSize() int {
	size := 28
	return size
}

func (s SQLNullInt16Struct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"i16\":"...)
	if !s.I16.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = strconv.AppendInt(dst, int64(s.I16.Int16), 10)
	}
	return append(dst, '}'), nil
}

func (recv SQLNullByteStruct) DecodeFrom(data []byte) (result SQLNullByteStruct, i int, err error) {
	result = recv
	seenB := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "b":
			if seenB {
				return result, i, &validation.DuplicateKeyError{Path: []string{"b"}}
			}
			seenB = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.B = sql.NullByte{}
				i += 4
			} else {
				var nv byte
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, decode.NewParseErr("b", i, scan.ErrBadNumber)
				}
				var n uint64
				de := i + 19
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					n = n*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if n > scan.Uint64Limit/10 || (n == scan.Uint64Limit/10 && d > scan.Uint64Limit%10) {
						return result, i, decode.NewParseErr("b", i, scan.ErrNumberOverflow)
					}
					n = n*10 + d
					i++
				}
				nv = byte(n)

				result.B = sql.NullByte{Byte: nv, Valid: true}
			}
		default:
			return result, i, &validation.UnknownKeyError{Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv SQLNullByteStruct) DecodeFromStream(s *scan.Stream) (result SQLNullByteStruct, err error) {
	result = recv
	seenB := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "b":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("b", s.Pos, err)
			}
			if seenB {
				return result, &validation.DuplicateKeyError{Path: []string{"b"}}
			}
			seenB = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("b", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("b", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("b", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.B = sql.NullByte{}
				s.Pos += 4
			} else {
				var nv uint64
				nv, err = s.Uint64()
				if err != nil {
					return result, decode.NewParseErr("b", s.Pos, err)
				}

				result.B = sql.NullByte{Byte: byte(nv), Valid: true}
			}
		default:
			return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s SQLNullByteStruct) JSONSize() int {
	size := 26
	return size
}

func (s SQLNullByteStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"b\":"...)
	if !s.B.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = strconv.AppendUint(dst, uint64(s.B.Byte), 10)
	}
	return append(dst, '}'), nil
}

func (recv SQLNullBoolStruct) DecodeFrom(data []byte) (result SQLNullBoolStruct, i int, err error) {
	result = recv
	seenBL := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "bl":
			if seenBL {
				return result, i, &validation.DuplicateKeyError{Path: []string{"bl"}}
			}
			seenBL = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.BL = sql.NullBool{}
				i += 4
			} else {
				var nv bool
				nv, i, err = scan.Bool(data, i)
				if err != nil {
					return result, i, decode.NewParseErr("bl", i, err)
				}

				result.BL = sql.NullBool{Bool: nv, Valid: true}
			}
		default:
			return result, i, &validation.UnknownKeyError{Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv SQLNullBoolStruct) DecodeFromStream(s *scan.Stream) (result SQLNullBoolStruct, err error) {
	result = recv
	seenBL := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "bl":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("bl", s.Pos, err)
			}
			if seenBL {
				return result, &validation.DuplicateKeyError{Path: []string{"bl"}}
			}
			seenBL = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("bl", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("bl", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("bl", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.BL = sql.NullBool{}
				s.Pos += 4
			} else {
				var nv bool
				nv, err = s.Bool()
				if err != nil {
					return result, decode.NewParseErr("bl", s.Pos, err)
				}

				result.BL = sql.NullBool{Bool: nv, Valid: true}
			}
		default:
			return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s SQLNullBoolStruct) JSONSize() int {
	size := 12
	return size
}

func (s SQLNullBoolStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"bl\":"...)
	if !s.BL.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = strconv.AppendBool(dst, s.BL.Bool)
	}
	return append(dst, '}'), nil
}

func (recv SQLNullFloat64Struct) DecodeFrom(data []byte) (result SQLNullFloat64Struct, i int, err error) {
	result = recv
	seenF := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "f":
			if seenF {
				return result, i, &validation.DuplicateKeyError{Path: []string{"f"}}
			}
			seenF = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.F = sql.NullFloat64{}
				i += 4
			} else {
				var nv float64
				nv, i, err = scan.Float64(data, i)
				if err != nil {
					return result, i, decode.NewParseErr("f", i, err)
				}

				result.F = sql.NullFloat64{Float64: nv, Valid: true}
			}
		default:
			return result, i, &validation.UnknownKeyError{Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv SQLNullFloat64Struct) DecodeFromStream(s *scan.Stream) (result SQLNullFloat64Struct, err error) {
	result = recv
	seenF := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "f":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("f", s.Pos, err)
			}
			if seenF {
				return result, &validation.DuplicateKeyError{Path: []string{"f"}}
			}
			seenF = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("f", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("f", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("f", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.F = sql.NullFloat64{}
				s.Pos += 4
			} else {
				var nv float64
				nv, err = s.Float64()
				if err != nil {
					return result, decode.NewParseErr("f", s.Pos, err)
				}

				result.F = sql.NullFloat64{Float64: nv, Valid: true}
			}
		default:
			return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s SQLNullFloat64Struct) JSONSize() int {
	size := 31
	return size
}

func (s SQLNullFloat64Struct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"f\":"...)
	if !s.F.Valid {
		dst = append(dst, "null"...)
	} else {
		if dst, err = encode.AppendFloat(dst, s.F.Float64, 64); err != nil {
			return dst, err
		}
	}
	return append(dst, '}'), nil
}

func (recv SQLNullTimeStruct) DecodeFrom(data []byte) (result SQLNullTimeStruct, i int, err error) {
	result = recv
	seenT := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "t":
			if seenT {
				return result, i, &validation.DuplicateKeyError{Path: []string{"t"}}
			}
			seenT = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.T = sql.NullTime{}
				i += 4
			} else {
				var nv time.Time
				var s string
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("t", i, scan.ErrExpectString)
				}
				ke := i + 1
				for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
					ke++
				}
				if ke >= len(data) {
					return result, i, decode.NewParseErr("t", i, scan.ErrUnterminated)
				}
				if data[ke] < 0x20 {
					return result, i, decode.NewParseErr("t", i, scan.ErrBadString)
				}
				if data[ke] == '"' {
					s = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
					i = ke + 1
				} else {
					s, i, err = scan.String(data, i)
					if err != nil {
						return result, i, decode.NewParseErr("t", i, err)
					}
				}
				nv, err = time.Parse(time.RFC3339Nano, s)
				if err != nil {
					return result, i, decode.NewParseErr("t", i, err)
				}

				result.T = sql.NullTime{Time: nv, Valid: true}
			}
		default:
			return result, i, &validation.UnknownKeyError{Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv SQLNullTimeStruct) DecodeFromStream(s *scan.Stream) (result SQLNullTimeStruct, err error) {
	result = recv
	seenT := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "t":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("t", s.Pos, err)
			}
			if seenT {
				return result, &validation.DuplicateKeyError{Path: []string{"t"}}
			}
			seenT = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("t", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("t", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("t", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.T = sql.NullTime{}
				s.Pos += 4
			} else {
				var nv time.Time
				var sv string
				sv, err = s.StringView()
				if err != nil {
					return result, decode.NewParseErr("t", s.Pos, err)
				}
				nv, err = time.Parse(time.RFC3339Nano, sv)
				if err != nil {
					return result, decode.NewParseErr("t", s.Pos, err)
				}

				result.T = sql.NullTime{Time: nv, Valid: true}
			}
		default:
			return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s SQLNullTimeStruct) JSONSize() int {
	size := 43
	return size
}

func (s SQLNullTimeStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"t\":"...)
	if !s.T.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '"')
		dst = s.T.Time.AppendFormat(dst, time.RFC3339Nano)
		dst = append(dst, '"')
	}
	return append(dst, '}'), nil
}

func (recv SQLNullStruct) DecodeFrom(data []byte) (result SQLNullStruct, i int, err error) {
	result = recv
	seenB := false
	seenBL := false
	seenF := false
	seenI := false
	seenI16 := false
	seenI32 := false
	seenS := false
	seenT := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "b":
			if seenB {
				return result, i, &validation.DuplicateKeyError{Path: []string{"b"}}
			}
			seenB = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.B = sql.NullByte{}
				i += 4
			} else {
				var nv byte
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, decode.NewParseErr("b", i, scan.ErrBadNumber)
				}
				var n uint64
				de := i + 19
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					n = n*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if n > scan.Uint64Limit/10 || (n == scan.Uint64Limit/10 && d > scan.Uint64Limit%10) {
						return result, i, decode.NewParseErr("b", i, scan.ErrNumberOverflow)
					}
					n = n*10 + d
					i++
				}
				nv = byte(n)

				result.B = sql.NullByte{Byte: nv, Valid: true}
			}
		case "bl":
			if seenBL {
				return result, i, &validation.DuplicateKeyError{Path: []string{"bl"}}
			}
			seenBL = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.BL = sql.NullBool{}
				i += 4
			} else {
				var nv bool
				nv, i, err = scan.Bool(data, i)
				if err != nil {
					return result, i, decode.NewParseErr("bl", i, err)
				}

				result.BL = sql.NullBool{Bool: nv, Valid: true}
			}
		case "f":
			if seenF {
				return result, i, &validation.DuplicateKeyError{Path: []string{"f"}}
			}
			seenF = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.F = sql.NullFloat64{}
				i += 4
			} else {
				var nv float64
				nv, i, err = scan.Float64(data, i)
				if err != nil {
					return result, i, decode.NewParseErr("f", i, err)
				}

				result.F = sql.NullFloat64{Float64: nv, Valid: true}
			}
		case "i":
			if seenI {
				return result, i, &validation.DuplicateKeyError{Path: []string{"i"}}
			}
			seenI = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.I = sql.NullInt64{}
				i += 4
			} else {
				var nv int64
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, decode.NewParseErr("i", i, scan.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = scan.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, decode.NewParseErr("i", i, scan.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, decode.NewParseErr("i", i, scan.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == scan.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				nv = n

				result.I = sql.NullInt64{Int64: nv, Valid: true}
			}
		case "i16":
			if seenI16 {
				return result, i, &validation.DuplicateKeyError{Path: []string{"i16"}}
			}
			seenI16 = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.I16 = sql.NullInt16{}
				i += 4
			} else {
				var nv int16
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, decode.NewParseErr("i16", i, scan.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = scan.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, decode.NewParseErr("i16", i, scan.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, decode.NewParseErr("i16", i, scan.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == scan.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				nv = int16(n)

				result.I16 = sql.NullInt16{Int16: nv, Valid: true}
			}
		case "i32":
			if seenI32 {
				return result, i, &validation.DuplicateKeyError{Path: []string{"i32"}}
			}
			seenI32 = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.I32 = sql.NullInt32{}
				i += 4
			} else {
				var nv int32
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, decode.NewParseErr("i32", i, scan.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = scan.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, decode.NewParseErr("i32", i, scan.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, decode.NewParseErr("i32", i, scan.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == scan.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				nv = int32(n)

				result.I32 = sql.NullInt32{Int32: nv, Valid: true}
			}
		case "s":
			if seenS {
				return result, i, &validation.DuplicateKeyError{Path: []string{"s"}}
			}
			seenS = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.S = sql.NullString{}
				i += 4
			} else {
				var nv string
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("s", i, scan.ErrExpectString)
				}
				ke := i + 1
				for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
					ke++
				}
				if ke >= len(data) {
					return result, i, decode.NewParseErr("s", i, scan.ErrUnterminated)
				}
				if data[ke] < 0x20 {
					return result, i, decode.NewParseErr("s", i, scan.ErrBadString)
				}
				if data[ke] == '"' {
					nv = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
					i = ke + 1
				} else {
					nv, i, err = scan.String(data, i)
					if err != nil {
						return result, i, decode.NewParseErr("s", i, err)
					}
				}

				result.S = sql.NullString{String: nv, Valid: true}
			}
		case "t":
			if seenT {
				return result, i, &validation.DuplicateKeyError{Path: []string{"t"}}
			}
			seenT = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				result.T = sql.NullTime{}
				i += 4
			} else {
				var nv time.Time
				var s string
				if i >= len(data) || data[i] != '"' {
					return result, i, decode.NewParseErr("t", i, scan.ErrExpectString)
				}
				ke := i + 1
				for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 {
					ke++
				}
				if ke >= len(data) {
					return result, i, decode.NewParseErr("t", i, scan.ErrUnterminated)
				}
				if data[ke] < 0x20 {
					return result, i, decode.NewParseErr("t", i, scan.ErrBadString)
				}
				if data[ke] == '"' {
					s = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
					i = ke + 1
				} else {
					s, i, err = scan.String(data, i)
					if err != nil {
						return result, i, decode.NewParseErr("t", i, err)
					}
				}
				nv, err = time.Parse(time.RFC3339Nano, s)
				if err != nil {
					return result, i, decode.NewParseErr("t", i, err)
				}

				result.T = sql.NullTime{Time: nv, Valid: true}
			}
		default:
			return result, i, &validation.UnknownKeyError{Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv SQLNullStruct) DecodeFromStream(s *scan.Stream) (result SQLNullStruct, err error) {
	result = recv
	seenB := false
	seenBL := false
	seenF := false
	seenI := false
	seenI16 := false
	seenI32 := false
	seenS := false
	seenT := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "b":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("b", s.Pos, err)
			}
			if seenB {
				return result, &validation.DuplicateKeyError{Path: []string{"b"}}
			}
			seenB = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("b", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("b", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("b", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.B = sql.NullByte{}
				s.Pos += 4
			} else {
				var nv uint64
				nv, err = s.Uint64()
				if err != nil {
					return result, decode.NewParseErr("b", s.Pos, err)
				}

				result.B = sql.NullByte{Byte: byte(nv), Valid: true}
			}
		case "bl":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("bl", s.Pos, err)
			}
			if seenBL {
				return result, &validation.DuplicateKeyError{Path: []string{"bl"}}
			}
			seenBL = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("bl", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("bl", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("bl", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.BL = sql.NullBool{}
				s.Pos += 4
			} else {
				var nv bool
				nv, err = s.Bool()
				if err != nil {
					return result, decode.NewParseErr("bl", s.Pos, err)
				}

				result.BL = sql.NullBool{Bool: nv, Valid: true}
			}
		case "f":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("f", s.Pos, err)
			}
			if seenF {
				return result, &validation.DuplicateKeyError{Path: []string{"f"}}
			}
			seenF = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("f", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("f", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("f", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.F = sql.NullFloat64{}
				s.Pos += 4
			} else {
				var nv float64
				nv, err = s.Float64()
				if err != nil {
					return result, decode.NewParseErr("f", s.Pos, err)
				}

				result.F = sql.NullFloat64{Float64: nv, Valid: true}
			}
		case "i":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("i", s.Pos, err)
			}
			if seenI {
				return result, &validation.DuplicateKeyError{Path: []string{"i"}}
			}
			seenI = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("i", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("i", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("i", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.I = sql.NullInt64{}
				s.Pos += 4
			} else {
				var nv int64
				nv, err = s.Int64()
				if err != nil {
					return result, decode.NewParseErr("i", s.Pos, err)
				}

				result.I = sql.NullInt64{Int64: nv, Valid: true}
			}
		case "i16":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("i16", s.Pos, err)
			}
			if seenI16 {
				return result, &validation.DuplicateKeyError{Path: []string{"i16"}}
			}
			seenI16 = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("i16", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("i16", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("i16", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.I16 = sql.NullInt16{}
				s.Pos += 4
			} else {
				var nv int64
				nv, err = s.Int64()
				if err != nil {
					return result, decode.NewParseErr("i16", s.Pos, err)
				}

				result.I16 = sql.NullInt16{Int16: int16(nv), Valid: true}
			}
		case "i32":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("i32", s.Pos, err)
			}
			if seenI32 {
				return result, &validation.DuplicateKeyError{Path: []string{"i32"}}
			}
			seenI32 = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("i32", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("i32", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("i32", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.I32 = sql.NullInt32{}
				s.Pos += 4
			} else {
				var nv int64
				nv, err = s.Int64()
				if err != nil {
					return result, decode.NewParseErr("i32", s.Pos, err)
				}

				result.I32 = sql.NullInt32{Int32: int32(nv), Valid: true}
			}
		case "s":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("s", s.Pos, err)
			}
			if seenS {
				return result, &validation.DuplicateKeyError{Path: []string{"s"}}
			}
			seenS = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("s", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("s", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("s", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.S = sql.NullString{}
				s.Pos += 4
			} else {
				var nv string
				nv, err = s.String()
				if err != nil {
					return result, decode.NewParseErr("s", s.Pos, err)
				}

				result.S = sql.NullString{String: nv, Valid: true}
			}
		case "t":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("t", s.Pos, err)
			}
			if seenT {
				return result, &validation.DuplicateKeyError{Path: []string{"t"}}
			}
			seenT = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("t", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("t", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("t", s.Pos, scan.ErrBadLiteral)
					}
				}
				result.T = sql.NullTime{}
				s.Pos += 4
			} else {
				var nv time.Time
				var sv string
				sv, err = s.StringView()
				if err != nil {
					return result, decode.NewParseErr("t", s.Pos, err)
				}
				nv, err = time.Parse(time.RFC3339Nano, sv)
				if err != nil {
					return result, decode.NewParseErr("t", s.Pos, err)
				}

				result.T = sql.NullTime{Time: nv, Valid: true}
			}
		default:
			return result, &validation.UnknownKeyError{Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s SQLNullStruct) JSONSize() int {
	size := 197
	size += len(s.S.String) * 2
	return size
}

func (s SQLNullStruct) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"b\":"...)
	if !s.B.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = strconv.AppendUint(dst, uint64(s.B.Byte), 10)
	}
	dst = append(dst, ",\"bl\":"...)
	if !s.BL.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = strconv.AppendBool(dst, s.BL.Bool)
	}
	dst = append(dst, ",\"f\":"...)
	if !s.F.Valid {
		dst = append(dst, "null"...)
	} else {
		if dst, err = encode.AppendFloat(dst, s.F.Float64, 64); err != nil {
			return dst, err
		}
	}
	dst = append(dst, ",\"i\":"...)
	if !s.I.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = strconv.AppendInt(dst, s.I.Int64, 10)
	}
	dst = append(dst, ",\"i16\":"...)
	if !s.I16.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = strconv.AppendInt(dst, int64(s.I16.Int16), 10)
	}
	dst = append(dst, ",\"i32\":"...)
	if !s.I32.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = strconv.AppendInt(dst, int64(s.I32.Int32), 10)
	}
	dst = append(dst, ",\"s\":"...)
	if !s.S.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '"')
		dst = encode.AppendStringNoHTML(dst, s.S.String)
	}
	dst = append(dst, ",\"t\":"...)
	if !s.T.Valid {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '"')
		dst = s.T.Time.AppendFormat(dst, time.RFC3339Nano)
		dst = append(dst, '"')
	}
	return append(dst, '}'), nil
}
