// Code generated by ggen; DO NOT EDIT.

package integrationtests

import (
	"bytes"
	"math"
	"strconv"
	"strings"
	"unsafe"

	"github.com/sirkostya009/ggen"
)

// Tries to fit >2 elements in 80 bytes, then 512 bytes - never goes above that.
const ggenCap_ElemInterleave_Nums_int = (min((80/max(int(unsafe.Sizeof(*new(int))), 1)), 2)/2)*(80/max(int(unsafe.Sizeof(*new(int))), 1)) + (1-(min((80/max(int(unsafe.Sizeof(*new(int))), 1)), 2)/2))*max(((8*int(unsafe.Sizeof(uintptr(0)))*int(unsafe.Sizeof(uintptr(0))))/max(int(unsafe.Sizeof(*new(int))), 1)), 1)

func (recv Money) DecodeFrom(data []byte) (result Money, i int, err error) {
	result = recv
	seenAmount := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenAmount {
			result.Amount = 0
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "amount":
			if seenAmount {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"amount"}}
			}
			seenAmount = true
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("amount", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("amount", i, ggen.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = ggen.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, ggen.NewParseErr("amount", i, ggen.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("amount", i, ggen.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == ggen.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			result.Amount = int(n)
		default:
			return result, i, &ggen.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenAmount {
				result.Amount = 0
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv Money) DecodeFromStream(s *ggen.Stream) (result Money, err error) {
	result = recv
	seenAmount := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenAmount {
			result.Amount = 0
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "amount":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("amount", s.Offset(), err)
			}
			if seenAmount {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"amount"}}
			}
			seenAmount = true
			var iv int64
			iv, err = s.Int64()
			if err != nil {
				return result, ggen.NewParseErr("amount", s.Offset(), err)
			}
			result.Amount = int(iv)
		default:
			return result, &ggen.UnknownKeyError{Pos: s.Offset(), Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenAmount {
				result.Amount = 0
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s Money) JSONSize() int {
	size := 31
	return size
}

func (s Money) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"amount\":"...)
	dst = strconv.AppendInt(dst, int64(s.Amount), 10)
	return append(dst, '}'), nil
}

func (recv LooseThing) DecodeFrom(data []byte) (result LooseThing, i int, err error) {
	result = recv
	seenCount := false
	seenOpt := false
	seenPrice := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenCount {
			result.Count = 0
		}
		if !seenOpt {
			result.Opt = 0
		}
		if !seenPrice {
			result.Price = 0
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "count":
			if seenCount {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"count"}}
			}
			seenCount = true
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			if i >= len(data) {
				return result, i, ggen.NewParseErr("count", i, ggen.ErrUnexpectedEnd)
			}
			switch data[i] {
			case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, ggen.NewParseErr("count", i, ggen.ErrBadNumber)
				}
				if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
					return result, i, ggen.NewParseErr("count", i, ggen.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = ggen.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, ggen.NewParseErr("count", i, ggen.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, ggen.NewParseErr("count", i, ggen.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == ggen.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				result.Count = int(n)
			case '"':
				var _cv1 string
				if i >= len(data) || data[i] != '"' {
					return result, i, ggen.NewParseErr("count", i, ggen.ErrExpectString)
				}
				ke := i + 1
				kew := ke + 32
				if kew > len(data) {
					kew = len(data)
				}
				for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
				if ke < len(data) && data[ke] == '"' {
					_cv1 = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
					i = ke + 1
				} else {
					_cv1, i, err = ggen.String(data, i, true)
					if err != nil {
						return result, i, ggen.NewParseErr("count", i, err)
					}
				}
				if cv, err := AtoiStrict(_cv1); err != nil {
					return result, i, ggen.NewParseErr("count", i, err)
				} else {
					result.Count = cv
				}
			default:
				return result, i, ggen.NewParseErr("count", i, ggen.ErrBadValue)
			}
			if result.Count < 0 {
				return result, i, &ggen.GTEError{Pos: i, Path: []string{"count"}, Limit: 0, Value: result.Count}
			}
		case "opt":
			if seenOpt {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"opt"}}
			}
			seenOpt = true
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			if i >= len(data) {
				return result, i, ggen.NewParseErr("opt", i, ggen.ErrUnexpectedEnd)
			}
			switch data[i] {
			case 'n':
				if i+4 > len(data) || data[i+1] != 'u' || data[i+2] != 'l' || data[i+3] != 'l' {
					return result, i, ggen.NewParseErr("opt", i, ggen.ErrBadLiteral)
				}
				i += 4
				result.Opt = 0
			case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, ggen.NewParseErr("opt", i, ggen.ErrBadNumber)
				}
				if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
					return result, i, ggen.NewParseErr("opt", i, ggen.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = ggen.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, ggen.NewParseErr("opt", i, ggen.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, ggen.NewParseErr("opt", i, ggen.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == ggen.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				result.Opt = int(n)
			case '"':
				var _cv2 string
				if i >= len(data) || data[i] != '"' {
					return result, i, ggen.NewParseErr("opt", i, ggen.ErrExpectString)
				}
				ke := i + 1
				kew := ke + 32
				if kew > len(data) {
					kew = len(data)
				}
				for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
				if ke < len(data) && data[ke] == '"' {
					_cv2 = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
					i = ke + 1
				} else {
					_cv2, i, err = ggen.String(data, i, true)
					if err != nil {
						return result, i, ggen.NewParseErr("opt", i, err)
					}
				}
				if cv, err := AtoiStrict(_cv2); err != nil {
					return result, i, ggen.NewParseErr("opt", i, err)
				} else {
					result.Opt = cv
				}
			default:
				return result, i, ggen.NewParseErr("opt", i, ggen.ErrBadValue)
			}
		case "price":
			if seenPrice {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"price"}}
			}
			seenPrice = true
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			if i >= len(data) {
				return result, i, ggen.NewParseErr("price", i, ggen.ErrUnexpectedEnd)
			}
			switch data[i] {
			case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, ggen.NewParseErr("price", i, ggen.ErrBadNumber)
				}
				if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
					return result, i, ggen.NewParseErr("price", i, ggen.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = ggen.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, ggen.NewParseErr("price", i, ggen.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, ggen.NewParseErr("price", i, ggen.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == ggen.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				result.Price = int(n)
			case '{':
				var _cv1 Money
				var _n int
				_cv1, _n, err = _cv1.DecodeFrom(data[i:])
				i += _n
				if err != nil {
					return result, i, ggen.NewParseErrShift("price", i, _n, err)
				}
				result.Price = FromMoney(_cv1)
			default:
				return result, i, ggen.NewParseErr("price", i, ggen.ErrBadValue)
			}
		default:
			return result, i, &ggen.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenCount {
				result.Count = 0
			}
			if !seenOpt {
				result.Opt = 0
			}
			if !seenPrice {
				result.Price = 0
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv LooseThing) DecodeFromStream(s *ggen.Stream) (result LooseThing, err error) {
	result = recv
	seenCount := false
	seenOpt := false
	seenPrice := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenCount {
			result.Count = 0
		}
		if !seenOpt {
			result.Opt = 0
		}
		if !seenPrice {
			result.Price = 0
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "count":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("count", s.Offset(), err)
			}
			if seenCount {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"count"}}
			}
			seenCount = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, ggen.NewParseErr("count", s.Offset(), ggen.NotEOF(err, ggen.ErrUnexpectedEnd))
				}
			}
			switch s.Bytes()[s.Pos] {
			case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				var iv int64
				iv, err = s.Int64()
				if err != nil {
					return result, ggen.NewParseErr("count", s.Offset(), err)
				}
				result.Count = int(iv)
			case '"':
				var _cv1 string
				_cv1, err = s.String(true)
				if err != nil {
					return result, ggen.NewParseErr("count", s.Offset(), err)
				}
				if cv, err := AtoiStrict(_cv1); err != nil {
					return result, ggen.NewParseErr("count", s.Offset(), err)
				} else {
					result.Count = cv
				}
			default:
				return result, ggen.NewParseErr("count", s.Offset(), ggen.ErrBadValue)
			}
			if result.Count < 0 {
				return result, &ggen.GTEError{Pos: s.Offset(), Path: []string{"count"}, Limit: 0, Value: result.Count}
			}
		case "opt":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("opt", s.Offset(), err)
			}
			if seenOpt {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"opt"}}
			}
			seenOpt = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, ggen.NewParseErr("opt", s.Offset(), ggen.NotEOF(err, ggen.ErrUnexpectedEnd))
				}
			}
			switch s.Bytes()[s.Pos] {
			case 'n':
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, ggen.NewParseErr("opt", s.Offset(), ggen.NotEOF(err, ggen.ErrBadLiteral))
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, ggen.NewParseErr("opt", s.Offset(), ggen.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.Opt = 0
			case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				var iv int64
				iv, err = s.Int64()
				if err != nil {
					return result, ggen.NewParseErr("opt", s.Offset(), err)
				}
				result.Opt = int(iv)
			case '"':
				var _cv2 string
				_cv2, err = s.String(true)
				if err != nil {
					return result, ggen.NewParseErr("opt", s.Offset(), err)
				}
				if cv, err := AtoiStrict(_cv2); err != nil {
					return result, ggen.NewParseErr("opt", s.Offset(), err)
				} else {
					result.Opt = cv
				}
			default:
				return result, ggen.NewParseErr("opt", s.Offset(), ggen.ErrBadValue)
			}
		case "price":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("price", s.Offset(), err)
			}
			if seenPrice {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"price"}}
			}
			seenPrice = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, ggen.NewParseErr("price", s.Offset(), ggen.NotEOF(err, ggen.ErrUnexpectedEnd))
				}
			}
			switch s.Bytes()[s.Pos] {
			case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				var iv int64
				iv, err = s.Int64()
				if err != nil {
					return result, ggen.NewParseErr("price", s.Offset(), err)
				}
				result.Price = int(iv)
			case '{':
				var _cv1 Money
				_cv1, err = _cv1.DecodeFromStream(s)
				if err != nil {
					return result, ggen.NewParseErr("price", s.Offset(), err)
				}
				result.Price = FromMoney(_cv1)
			default:
				return result, ggen.NewParseErr("price", s.Offset(), ggen.ErrBadValue)
			}
		default:
			return result, &ggen.UnknownKeyError{Pos: s.Offset(), Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenCount {
				result.Count = 0
			}
			if !seenOpt {
				result.Opt = 0
			}
			if !seenPrice {
				result.Price = 0
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s LooseThing) JSONSize() int {
	size := 86
	return size
}

func (s LooseThing) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"count\":"...)
	dst = strconv.AppendInt(dst, int64(s.Count), 10)
	dst = append(dst, ",\"opt\":"...)
	dst = strconv.AppendInt(dst, int64(s.Opt), 10)
	dst = append(dst, ",\"price\":"...)
	dst = strconv.AppendInt(dst, int64(s.Price), 10)
	return append(dst, '}'), nil
}

func (recv ElemInterleave) DecodeFrom(data []byte) (result ElemInterleave, i int, err error) {
	result = recv
	if result.Nums != nil {
		result.Nums = result.Nums[:0]
	}
	seenNums := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "nums":
			if seenNums {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"nums"}}
			}
			seenNums = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				i += 4
				result.Nums = nil
				break
			}
			if i >= len(data) || data[i] != '[' {
				return result, i, ggen.NewParseErr("nums", i, ggen.ErrBadArray)
			}
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			if i < len(data) && data[i] == ']' {
				if result.Nums == nil {
					result.Nums = []int{}
				}
			} else {
				if result.Nums == nil {
					cnt0 := 1
					if e := bytes.IndexByte(data[i:], ']'); e >= 0 {
						cnt0 = bytes.Count(data[i:i+e], []byte{','}) + 1
					}
					result.Nums = make([]int, 0, cnt0)
				}
			}
			if i < len(data) && data[i] != ']' {
				for {
					result.Nums = append(result.Nums, 0)
					neg := false
					if i < len(data) && data[i] == '-' {
						neg = true
						i++
					}
					if i >= len(data) || data[i] < '0' || data[i] > '9' {
						return result, i, ggen.NewParseErr("nums", i, ggen.ErrBadNumber)
					}
					if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
						return result, i, ggen.NewParseErr("nums", i, ggen.ErrBadNumber)
					}
					limit := uint64(math.MaxInt64)
					if neg {
						limit = ggen.SignedNeg
					}
					var u uint64
					de := i + 18
					if de > len(data) {
						de = len(data)
					}
					for i < de && data[i] >= '0' && data[i] <= '9' {
						u = u*10 + uint64(data[i]-'0')
						i++
					}
					for i < len(data) && data[i] >= '0' && data[i] <= '9' {
						d := uint64(data[i] - '0')
						if u > limit/10 || (u == limit/10 && d > limit%10) {
							return result, i, ggen.NewParseErr("nums", i, ggen.ErrNumberOverflow)
						}
						u = u*10 + d
						i++
					}
					if i < len(data) {
						c := data[i]
						if c == '.' || c == 'e' || c == 'E' {
							return result, i, ggen.NewParseErr("nums", i, ggen.ErrBadNumber)
						}
					}
					var n int64
					if neg {
						if u == ggen.SignedNeg {
							n = math.MinInt64
						} else {
							n = -int64(u)
						}
					} else {
						n = int64(u)
					}
					result.Nums[len(result.Nums)-1] = int(n)
					if result.Nums[len(result.Nums)-1] > 10 {
						return result, i, &ggen.LTEError{Pos: i, Path: []string{"nums[]"}, Limit: 10, Value: result.Nums[len(result.Nums)-1]}
					}
					result.Nums[len(result.Nums)-1] = DoubleInt(result.Nums[len(result.Nums)-1])
					for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i < len(data) && data[i] == ',' {
						i++
						for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i >= len(data) || data[i] == ']' {
							return result, i, ggen.NewParseErr("nums", i, ggen.ErrBadArray)
						}
						continue
					}
					break
				}
			}
			if i >= len(data) || data[i] != ']' {
				return result, i, ggen.NewParseErr("nums", i, ggen.ErrBadArray)
			}
			i++
		default:
			return result, i, &ggen.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv ElemInterleave) DecodeFromStream(s *ggen.Stream) (result ElemInterleave, err error) {
	result = recv
	if result.Nums != nil {
		result.Nums = result.Nums[:0]
	}
	seenNums := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "nums":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("nums", s.Offset(), err)
			}
			if seenNums {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"nums"}}
			}
			seenNums = true
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("nums", s.Offset(), err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, ggen.NewParseErr("nums", s.Offset(), ggen.NotEOF(err, ggen.ErrBadArray))
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, ggen.NewParseErr("nums", s.Offset(), ggen.NotEOF(err, ggen.ErrBadLiteral))
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, ggen.NewParseErr("nums", s.Offset(), ggen.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.Nums = nil
				break
			}
			err = s.ArrayOpen()
			if err != nil {
				return result, ggen.NewParseErr("nums", s.Offset(), err)
			}
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("nums", s.Offset(), err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, ggen.NewParseErr("nums", s.Offset(), ggen.NotEOF(err, ggen.ErrBadArray))
				}
			}
			if s.Bytes()[s.Pos] == ']' {
				if result.Nums == nil {
					result.Nums = []int{}
				}
			} else {
				if result.Nums == nil {
					result.Nums = make([]int, 0, ggenCap_ElemInterleave_Nums_int)
				}
			}
			for s.Bytes()[s.Pos] != ']' {
				result.Nums = append(result.Nums, 0)
				var iv int64
				iv, err = s.Int64()
				if err != nil {
					return result, ggen.NewParseErr("nums", s.Offset(), err)
				}
				result.Nums[len(result.Nums)-1] = int(iv)
				if result.Nums[len(result.Nums)-1] > 10 {
					return result, &ggen.LTEError{Pos: s.Offset(), Path: []string{"nums[]"}, Limit: 10, Value: result.Nums[len(result.Nums)-1]}
				}
				result.Nums[len(result.Nums)-1] = DoubleInt(result.Nums[len(result.Nums)-1])
				err = s.SkipSpace()
				if err != nil {
					return result, ggen.NewParseErr("nums", s.Offset(), err)
				}
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, ggen.NewParseErr("nums", s.Offset(), ggen.NotEOF(err, ggen.ErrBadArray))
					}
				}
				if s.Bytes()[s.Pos] == ',' {
					s.Pos++
					err = s.SkipSpace()
					if err != nil {
						return result, ggen.NewParseErr("nums", s.Offset(), err)
					}
					if s.Pos >= len(s.Bytes()) || s.Bytes()[s.Pos] == ']' {
						return result, ggen.NewParseErr("nums", s.Offset(), ggen.ErrBadArray)
					}
					continue
				}
				break
			}
			if s.Bytes()[s.Pos] != ']' {
				return result, ggen.NewParseErr("nums", s.Offset(), ggen.ErrBadArray)
			}
			s.Pos++
		default:
			return result, &ggen.UnknownKeyError{Pos: s.Offset(), Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s ElemInterleave) JSONSize() int {
	size := 13
	if n := len(s.Nums); n > 0 {
		size += n - 1
	}
	size += len(s.Nums) * 20
	return size
}

func (s ElemInterleave) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"nums\":"...)
	if s.Nums == nil {
		dst = append(dst, "null"...)
	} else {
		dst = append(dst, '[')
		if len(s.Nums) > 0 {
			dst = strconv.AppendInt(dst, int64(s.Nums[0]), 10)
			for _, v0 := range s.Nums[1:] {
				dst = append(dst, ',')
				dst = strconv.AppendInt(dst, int64(v0), 10)
			}
		}
		dst = append(dst, ']')
	}
	return append(dst, '}'), nil
}

func (recv ConvNamed) DecodeFrom(data []byte) (result ConvNamed, i int, err error) {
	result = recv
	seenN := false
	seenS := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenN {
			result.N = nil
		}
		if !seenS {
			result.S = Score(0)
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "n":
			if seenN {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"n"}}
			}
			seenN = true
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			if i >= len(data) {
				return result, i, ggen.NewParseErr("n", i, ggen.ErrUnexpectedEnd)
			}
			switch data[i] {
			case 'n':
				if i+4 > len(data) || data[i+1] != 'u' || data[i+2] != 'l' || data[i+3] != 'l' {
					return result, i, ggen.NewParseErr("n", i, ggen.ErrBadLiteral)
				}
				i += 4
				result.N = nil
			case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
					i += 4
					result.N = nil
					break
				}
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, ggen.NewParseErr("n", i, ggen.ErrBadNumber)
				}
				if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
					return result, i, ggen.NewParseErr("n", i, ggen.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = ggen.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, ggen.NewParseErr("n", i, ggen.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, ggen.NewParseErr("n", i, ggen.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == ggen.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				if result.N == nil {
					result.N = new(int(n))
				} else {
					(*result.N) = int(n)
				}
			case '"':
				var _cv2 string
				if i >= len(data) || data[i] != '"' {
					return result, i, ggen.NewParseErr("n", i, ggen.ErrExpectString)
				}
				ke := i + 1
				kew := ke + 32
				if kew > len(data) {
					kew = len(data)
				}
				for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
				if ke < len(data) && data[ke] == '"' {
					_cv2 = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
					i = ke + 1
				} else {
					_cv2, i, err = ggen.String(data, i, true)
					if err != nil {
						return result, i, ggen.NewParseErr("n", i, err)
					}
				}
				if cv, err := PtrFromString(_cv2); err != nil {
					return result, i, ggen.NewParseErr("n", i, err)
				} else {
					result.N = cv
				}
			default:
				return result, i, ggen.NewParseErr("n", i, ggen.ErrBadValue)
			}
		case "s":
			if seenS {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"s"}}
			}
			seenS = true
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			if i >= len(data) {
				return result, i, ggen.NewParseErr("s", i, ggen.ErrUnexpectedEnd)
			}
			switch data[i] {
			case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				neg := false
				if i < len(data) && data[i] == '-' {
					neg = true
					i++
				}
				if i >= len(data) || data[i] < '0' || data[i] > '9' {
					return result, i, ggen.NewParseErr("s", i, ggen.ErrBadNumber)
				}
				if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
					return result, i, ggen.NewParseErr("s", i, ggen.ErrBadNumber)
				}
				limit := uint64(math.MaxInt64)
				if neg {
					limit = ggen.SignedNeg
				}
				var u uint64
				de := i + 18
				if de > len(data) {
					de = len(data)
				}
				for i < de && data[i] >= '0' && data[i] <= '9' {
					u = u*10 + uint64(data[i]-'0')
					i++
				}
				for i < len(data) && data[i] >= '0' && data[i] <= '9' {
					d := uint64(data[i] - '0')
					if u > limit/10 || (u == limit/10 && d > limit%10) {
						return result, i, ggen.NewParseErr("s", i, ggen.ErrNumberOverflow)
					}
					u = u*10 + d
					i++
				}
				if i < len(data) {
					c := data[i]
					if c == '.' || c == 'e' || c == 'E' {
						return result, i, ggen.NewParseErr("s", i, ggen.ErrBadNumber)
					}
				}
				var n int64
				if neg {
					if u == ggen.SignedNeg {
						n = math.MinInt64
					} else {
						n = -int64(u)
					}
				} else {
					n = int64(u)
				}
				result.S = Score(int(n))
			case '"':
				var _cv1 string
				if i >= len(data) || data[i] != '"' {
					return result, i, ggen.NewParseErr("s", i, ggen.ErrExpectString)
				}
				ke := i + 1
				kew := ke + 32
				if kew > len(data) {
					kew = len(data)
				}
				for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
					ke++
				}
				if ke < len(data) && data[ke] == '"' {
					_cv1 = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
					i = ke + 1
				} else {
					_cv1, i, err = ggen.String(data, i, true)
					if err != nil {
						return result, i, ggen.NewParseErr("s", i, err)
					}
				}
				if cv, err := ScoreFromString(_cv1); err != nil {
					return result, i, ggen.NewParseErr("s", i, err)
				} else {
					result.S = cv
				}
			default:
				return result, i, ggen.NewParseErr("s", i, ggen.ErrBadValue)
			}
		default:
			return result, i, &ggen.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenN {
				result.N = nil
			}
			if !seenS {
				result.S = Score(0)
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv ConvNamed) DecodeFromStream(s *ggen.Stream) (result ConvNamed, err error) {
	result = recv
	seenN := false
	seenS := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenN {
			result.N = nil
		}
		if !seenS {
			result.S = Score(0)
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "n":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("n", s.Offset(), err)
			}
			if seenN {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"n"}}
			}
			seenN = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, ggen.NewParseErr("n", s.Offset(), ggen.NotEOF(err, ggen.ErrUnexpectedEnd))
				}
			}
			switch s.Bytes()[s.Pos] {
			case 'n':
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, ggen.NewParseErr("n", s.Offset(), ggen.NotEOF(err, ggen.ErrBadLiteral))
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, ggen.NewParseErr("n", s.Offset(), ggen.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.N = nil
			case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, ggen.NewParseErr("n", s.Offset(), ggen.NotEOF(err, ggen.ErrBadNumber))
					}
				}
				if s.Bytes()[s.Pos] == 'n' {
					for ki := 1; ki < 4; ki++ {
						if s.Pos+ki >= len(s.Bytes()) {
							if err = s.ReadMore(0); err != nil {
								return result, ggen.NewParseErr("n", s.Offset(), ggen.NotEOF(err, ggen.ErrBadLiteral))
							}
						}
						if s.Bytes()[s.Pos+ki] != "null"[ki] {
							return result, ggen.NewParseErr("n", s.Offset(), ggen.ErrBadLiteral)
						}
					}
					s.Pos += 4
					result.N = nil
					break
				}
				var v int64
				v, err = s.Int64()
				if err != nil {
					return result, ggen.NewParseErr("n", s.Offset(), err)
				}
				if result.N == nil {
					result.N = new(int(v))
				} else {
					(*result.N) = int(v)
				}
			case '"':
				var _cv2 string
				_cv2, err = s.String(true)
				if err != nil {
					return result, ggen.NewParseErr("n", s.Offset(), err)
				}
				if cv, err := PtrFromString(_cv2); err != nil {
					return result, ggen.NewParseErr("n", s.Offset(), err)
				} else {
					result.N = cv
				}
			default:
				return result, ggen.NewParseErr("n", s.Offset(), ggen.ErrBadValue)
			}
		case "s":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("s", s.Offset(), err)
			}
			if seenS {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"s"}}
			}
			seenS = true
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, ggen.NewParseErr("s", s.Offset(), ggen.NotEOF(err, ggen.ErrUnexpectedEnd))
				}
			}
			switch s.Bytes()[s.Pos] {
			case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				var iv int64
				iv, err = s.Int64()
				if err != nil {
					return result, ggen.NewParseErr("s", s.Offset(), err)
				}
				result.S = Score(int(iv))
			case '"':
				var _cv1 string
				_cv1, err = s.String(true)
				if err != nil {
					return result, ggen.NewParseErr("s", s.Offset(), err)
				}
				if cv, err := ScoreFromString(_cv1); err != nil {
					return result, ggen.NewParseErr("s", s.Offset(), err)
				} else {
					result.S = cv
				}
			default:
				return result, ggen.NewParseErr("s", s.Offset(), ggen.ErrBadValue)
			}
		default:
			return result, &ggen.UnknownKeyError{Pos: s.Offset(), Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenN {
				result.N = nil
			}
			if !seenS {
				result.S = Score(0)
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s ConvNamed) JSONSize() int {
	size := 31
	if s.N == nil {
		size += 4
	} else {
		size += 20
	}
	return size
}

func (s ConvNamed) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"n\":"...)
	if s.N == nil {
		dst = append(dst, "null"...)
	} else {
		dst = strconv.AppendInt(dst, int64((*s.N)), 10)
	}
	dst = append(dst, ",\"s\":"...)
	dst = strconv.AppendInt(dst, int64(int(s.S)), 10)
	return append(dst, '}'), nil
}
