package main

// Loader / declaration-walk regressions: which package variants a directory
// yields, what a file's NAME constrains, which declarations are rejected,
// how a package's error batch is reported, and how foreign packages are
// spelled. Fixtures are real modules (replace → repo root) so the generated
// output is compiled where the assertion needs it.

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// writeGgenModule drops a go.mod into dir that resolves the ggen runtime to
// this checkout, so `go build` / `go test` work on the generated output.
func writeGgenModule(t *testing.T, dir, module string) {
	t.Helper()
	root, err := filepath.Abs("..")
	if err != nil {
		t.Fatal(err)
	}
	writeFixture(t, filepath.Join(dir, "go.mod"), "module "+module+"\n\ngo 1.27\n\nrequire github.com/sirkostya009/ggen v0.0.0\n\nreplace github.com/sirkostya009/ggen => "+root+"\n")
}

// runGo runs the go tool inside dir with the module fixture isolated from the
// workspace, returning combined output.
func runGo(t *testing.T, dir string, env []string, args ...string) (string, error) {
	t.Helper()
	cmd := exec.Command("go", args...)
	cmd.Dir = dir
	cmd.Env = append(append(os.Environ(), "GOWORK=off", "GOFLAGS=-mod=mod", "GOTOOLCHAIN=local"), env...)
	var buf bytes.Buffer
	cmd.Stdout = &buf
	cmd.Stderr = &buf
	err := cmd.Run()
	return buf.String(), err
}

func TestParseLoad(t *testing.T) {
	t.Parallel()
	bin := buildCLI(t)

	t.Run("ExternalTestPackage_BothVariantsGenerated", func(t *testing.T) {
		t.Parallel()
		base := t.TempDir()
		writeGgenModule(t, base, "xtestmod")
		pkg := filepath.Join(base, "pkg")
		writeFixture(t, filepath.Join(pkg, "a.go"), "package pkg\n\n//ggen:generate\ntype A struct {\n\tX int `json:\"x\"`\n}\n")
		writeFixture(t, filepath.Join(pkg, "i_test.go"), "package pkg\n\n//ggen:generate\ntype I struct {\n\tX int `json:\"x\"`\n}\n")
		writeFixture(t, filepath.Join(pkg, "x_test.go"), "package pkg_test\n\nimport \"xtestmod/pkg\"\n\n//ggen:generate\ntype E1 struct {\n\tY int   `json:\"y\"`\n\tA pkg.A `json:\"a\"`\n}\n")
		writeFixture(t, filepath.Join(pkg, "y_test.go"), "package pkg_test\n\n//ggen:generate\ntype E2 struct {\n\tZ int `json:\"z\"`\n}\n")

		check := func(t *testing.T) {
			t.Helper()
			if out, err := runCLI(t, bin, base, "./pkg"); err != nil {
				t.Fatalf("ggen ./pkg: %v\n%s", err, out)
			}
			lib := mustReadOutput(t, filepath.Join(pkg, "pkg_ggen.go"))
			if !strings.Contains(lib, "func (recv A) DecodeFrom(") {
				t.Errorf("A missing from pkg_ggen.go:\n%s", lib)
			}
			internal := mustReadOutput(t, filepath.Join(pkg, "pkg_ggen_test.go"))
			if !strings.HasPrefix(strings.TrimPrefix(internal, "// Code generated by ggen; DO NOT EDIT.\n\n"), "package pkg\n") ||
				!strings.Contains(internal, "func (recv I) DecodeFrom(") {
				t.Errorf("internal test struct I misrouted:\n%s", internal)
			}
			ext := mustReadOutput(t, filepath.Join(pkg, "pkg_xtest_ggen_test.go"))
			if !strings.Contains(ext, "\npackage pkg_test\n") {
				t.Errorf("external test output must carry the pkg_test clause:\n%s", ext)
			}
			if !strings.Contains(ext, "func (recv E1) DecodeFrom(") {
				t.Errorf("E1 missing from pkg_xtest_ggen_test.go:\n%s", ext)
			}
			if strings.Contains(ext, "recv A) DecodeFrom") || strings.Contains(lib, "recv E1) DecodeFrom") {
				t.Errorf("structs leaked across the package boundary")
			}
			if out, err := runGo(t, base, nil, "vet", "./pkg"); err != nil {
				t.Errorf("go vet ./pkg: %v\n%s", err, out)
			}
		}
		// The external package has more files than the base one, then fewer;
		// each variant keeps its own set either way.
		check(t)
		if err := os.Remove(filepath.Join(pkg, "y_test.go")); err != nil {
			t.Fatal(err)
		}
		if err := os.Remove(filepath.Join(pkg, "pkg_xtest_ggen_test.go")); err != nil {
			t.Fatal(err)
		}
		writeFixture(t, filepath.Join(pkg, "b.go"), "package pkg\n\ntype B struct{ V int }\n")
		writeFixture(t, filepath.Join(pkg, "c.go"), "package pkg\n\ntype C struct{ V int }\n")
		check(t)

		// Single-file mode on an external test file finds its annotation and
		// names the output after the file, under the external package clause.
		if out, err := runCLI(t, bin, base, "pkg/x_test.go"); err != nil {
			t.Fatalf("ggen pkg/x_test.go: %v\n%s", err, out)
		}
		single := mustReadOutput(t, filepath.Join(pkg, "x_ggen_test.go"))
		if !strings.Contains(single, "\npackage pkg_test\n") || !strings.Contains(single, "func (recv E1) DecodeFrom(") {
			t.Errorf("single-file external test output wrong:\n%s", single)
		}
	})

	t.Run("ExternalTestPackage_FirstRunIsFixedPoint", func(t *testing.T) {
		t.Parallel()
		base := t.TempDir()
		writeGgenModule(t, base, "xtestfp")
		pkg := filepath.Join(base, "pkg")
		writeFixture(t, filepath.Join(pkg, "a.go"), "package pkg\n\n//ggen:generate\ntype A struct {\n\tV int `json:\"v\"`\n}\n")
		writeFixture(t, filepath.Join(pkg, "x_test.go"), "package pkg_test\n\nimport \"xtestfp/pkg\"\n\n//ggen:generate\ntype E struct {\n\tA pkg.A  `json:\"a\"`\n\tS string `json:\"s\"`\n}\n")

		out := filepath.Join(pkg, "pkg_xtest_ggen_test.go")
		if o, err := runCLI(t, bin, base, "./pkg"); err != nil {
			t.Fatalf("ggen ./pkg: %v\n%s", err, o)
		}
		first := mustReadOutput(t, out)
		// One invocation writes both packages, so the base type's methods
		// are already the truth for the external test package.
		for _, want := range []string{"result.A.DecodeFrom(", "result.A.DecodeFromStream(", "s.A.AppendJSON(", "s.A.JSONSize()"} {
			if !strings.Contains(first, want) {
				t.Errorf("first run missing %q:\n%s", want, first)
			}
		}
		if strings.Contains(first, "encoding/json") {
			t.Errorf("first run fell back to the reflect codec:\n%s", first)
		}
		if o, err := runCLI(t, bin, base, "./pkg"); err != nil {
			t.Fatalf("ggen ./pkg (2nd): %v\n%s", err, o)
		}
		if second := mustReadOutput(t, out); second != first {
			t.Errorf("second run differs from the first:\n%s", second)
		}
		if o, err := runGo(t, base, nil, "vet", "./pkg"); err != nil {
			t.Errorf("go vet ./pkg: %v\n%s", err, o)
		}

		// A base type this run does NOT generate must not be called
		// directly, whatever a previous run left in the base output.
		writeFixture(t, filepath.Join(pkg, "a.go"), "package pkg\n\ntype A struct {\n\tV int `json:\"v\"`\n}\n\n//ggen:generate\ntype B struct {\n\tW int `json:\"w\"`\n}\n")
		if o, err := runCLI(t, bin, base, "./pkg"); err != nil {
			t.Fatalf("ggen ./pkg (3rd): %v\n%s", err, o)
		}
		if third := mustReadOutput(t, out); strings.Contains(third, "result.A.DecodeFrom(") {
			t.Errorf("direct call to a type the base pass no longer generates:\n%s", third)
		}
		if o, err := runGo(t, base, nil, "vet", "./pkg"); err != nil {
			t.Errorf("go vet ./pkg after dropping A: %v\n%s", err, o)
		}
	})

	t.Run("ParenthesizedTypes_SpelledWithoutParens", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		writeGgenModule(t, dir, "parens")
		// Go keeps these parentheses through gofmt, so the walk has to.
		writeFixture(t, filepath.Join(dir, "msg.go"), "package parens\n\n//ggen:generate\ntype Msg struct {\n"+
			"\tA []([]bool)        `json:\"a\"`\n"+
			"\tB *(int)            `json:\"b\"`\n"+
			"\tC map[string](*int) `json:\"c\"`\n"+
			"\tD ([]byte)          `json:\"d\"`\n"+
			"\tE ([]int)           `json:\"e\"`\n}\n")
		if out, err := runCLI(t, bin, dir, "msg.go"); err != nil {
			t.Fatalf("ggen msg.go: %v\n%s", err, out)
		}
		body := mustReadOutput(t, filepath.Join(dir, "msg_ggen.go"))
		if strings.Contains(body, "ast.") {
			t.Errorf("AST node type leaked into the output:\n%s", body)
		}
		// Each field takes the shape its unparenthesized type asks for.
		for _, want := range []string{"[][]bool{}", "map[string]*int", "base64.StdEncoding", "[]int{}"} {
			if !strings.Contains(body, want) {
				t.Errorf("missing %q in:\n%s", want, body)
			}
		}
		if out, err := runGo(t, dir, nil, "vet", "."); err != nil {
			t.Errorf("go vet: %v\n%s", err, out)
		}
	})

	t.Run("ShapelessFieldTypes", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		writeGgenModule(t, dir, "hatches")
		writeFixture(t, filepath.Join(dir, "tp", "t.go"), "package tp\n\ntype T struct {\n\tX  int    `json:\"x\"`\n\tFn func() `json:\"-\"`\n}\n")
		// json:"-" drops the field before its type is judged, on the AST
		// path and the go/types one (Local's fields come from the latter).
		// An interface keeps its shape: it is spelled, and it marshals and
		// unmarshals exactly as encoding/json does.
		writeFixture(t, filepath.Join(dir, "msg.go"), "package hatches\n\nimport (\n\t\"hatches/tp\"\n\t\"io\"\n)\n\n//ggen:generate\ntype Msg struct {\n"+
			"\tX  int              `json:\"x\"`\n"+
			"\tFn func()           `json:\"-\"`\n"+
			"\tCh chan int         `json:\"-\"`\n"+
			"\tAn struct{ Q int }  `json:\"-\"`\n"+
			"\tIn interface{ M() } `json:\"in\"`\n"+
			"\tR  io.Reader        `json:\"r\"`\n}\n\n//ggen:generate\ntype Local tp.T\n")
		if out, err := runCLI(t, bin, dir, "msg.go"); err != nil {
			t.Fatalf("ggen msg.go: %v\n%s", err, out)
		}
		if out, err := runGo(t, dir, nil, "vet", "."); err != nil {
			t.Errorf("go vet: %v\n%s", err, out)
		}

		// On the wire a func has no shape, so it is a generate-time
		// rejection carrying the way out.
		writeFixture(t, filepath.Join(dir, "bad.go"), "package hatches\n\n//ggen:generate\ntype Bad struct {\n\tFn func() `json:\"fn\"`\n}\n")
		out, err := runCLI(t, bin, dir, "bad.go")
		if err == nil {
			t.Fatalf("untagged func field accepted:\n%s", out)
		}
		for _, want := range []string{"bad.go:5:2:", "func field types are not supported"} {
			if !strings.Contains(out, want) {
				t.Errorf("want %q in:\n%s", want, out)
			}
		}
		mustNotHaveFile(t, filepath.Join(dir, "bad_ggen.go"))
	})

	t.Run("EmbedRejection_NamesThePointerCaseOnly", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		writeGgenModule(t, dir, "embedmsg")
		writeFixture(t, filepath.Join(dir, "msg.go"), "package embedmsg\n\ntype M map[string]any\n\n//ggen:generate\ntype Msg struct {\n\tExtra M `json:\",embed\"`\n}\n")
		out, err := runCLI(t, bin, dir, "msg.go")
		if err == nil {
			t.Fatalf("named map accepted for embed:\n%s", out)
		}
		if !strings.Contains(out, "requires a map[string]T field, got M") {
			t.Errorf("want the plain requirement, got:\n%s", out)
		}
		if strings.Contains(out, "not a pointer to one") {
			t.Errorf("pointer clause on a field that is not a pointer:\n%s", out)
		}

		writeFixture(t, filepath.Join(dir, "ptr.go"), "package embedmsg\n\n//ggen:generate\ntype Ptr struct {\n\tExtra *map[string]any `json:\",embed\"`\n}\n")
		out, err = runCLI(t, bin, dir, "ptr.go")
		if err == nil {
			t.Fatalf("pointer map accepted for embed:\n%s", out)
		}
		if !strings.Contains(out, "not a pointer to one") {
			t.Errorf("want the pointer clause, got:\n%s", out)
		}
	})

	t.Run("FilenameConstraint_FoldedIntoBucket", func(t *testing.T) {
		t.Parallel()
		base := t.TempDir()
		writeGgenModule(t, base, "osconstraint")
		pkg := filepath.Join(base, "pkg")
		writeFixture(t, filepath.Join(pkg, "os_linux.go"), "//go:build !nope\n\npackage pkg\n\n//ggen:generate\ntype OnlyLinux struct {\n\tX int `json:\"x\"`\n}\n")
		writeFixture(t, filepath.Join(pkg, "arch_amd64_test.go"), "package pkg\n\n//ggen:generate\ntype OnlyAMD64 struct {\n\tX int `json:\"x\"`\n}\n")
		writeFixture(t, filepath.Join(pkg, "common.go"), "package pkg\n\n//ggen:generate\ntype Common struct {\n\tY int `json:\"y\"`\n}\n")
		if out, err := runCLI(t, bin, base, "./pkg"); err != nil {
			t.Fatalf("ggen ./pkg: %v\n%s", err, out)
		}
		linux := mustReadOutput(t, filepath.Join(pkg, "pkg_nope_linux_ggen.go"))
		if !strings.Contains(linux, "//go:build !nope && linux\n") || !strings.Contains(linux, "recv OnlyLinux) DecodeFrom") {
			t.Errorf("os_linux.go bucket lacks its constraint:\n%s", linux)
		}
		amd := mustReadOutput(t, filepath.Join(pkg, "pkg_amd64_ggen_test.go"))
		if !strings.Contains(amd, "//go:build amd64\n") {
			t.Errorf("arch_amd64_test.go bucket lacks its constraint:\n%s", amd)
		}
		common := mustReadOutput(t, filepath.Join(pkg, "pkg_ggen.go"))
		if strings.Contains(common, "//go:build") || strings.Contains(common, "OnlyLinux") {
			t.Errorf("unconstrained bucket polluted:\n%s", common)
		}
		for _, goos := range []string{"linux", "windows"} {
			if out, err := runGo(t, base, []string{"GOOS=" + goos}, "vet", "./pkg"); err != nil {
				t.Errorf("GOOS=%s go vet ./pkg: %v\n%s", goos, err, out)
			}
		}

		// Single-file mode: `_ggen` masks the suffix for Go's own rule, so
		// the header has to carry it.
		if out, err := runCLI(t, bin, base, "pkg/os_linux.go"); err != nil {
			t.Fatalf("ggen pkg/os_linux.go: %v\n%s", err, out)
		}
		single := mustReadOutput(t, filepath.Join(pkg, "os_linux_ggen.go"))
		if !strings.Contains(single, "//go:build !nope && linux\n") {
			t.Errorf("single-file output lacks the filename constraint:\n%s", single)
		}
		if err := os.Remove(filepath.Join(pkg, "pkg_nope_linux_ggen.go")); err != nil {
			t.Fatal(err)
		}
		if out, err := runGo(t, base, []string{"GOOS=darwin"}, "build", "./pkg"); err != nil {
			t.Errorf("GOOS=darwin go build ./pkg: %v\n%s", err, out)
		}
	})

	t.Run("GenericType_Rejected", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		writeGgenModule(t, dir, "fixture")
		writeFixture(t, filepath.Join(dir, "msg.go"), "package fixture\n\n//ggen:generate\ntype Box[T any] struct {\n\tV T `json:\"v\"`\n}\n\n//ggen:generate\ntype IntBox Box[int]\n")
		out, err := runCLI(t, bin, dir, "msg.go")
		if err == nil {
			t.Fatalf("generic struct accepted:\n%s", out)
		}
		if !strings.Contains(out, "msg.go:4:6: type Box: generic types are not supported") {
			t.Errorf("want positioned rejection, got:\n%s", out)
		}
		mustNotHaveFile(t, filepath.Join(dir, "msg_ggen.go"))

		// The hinted escape hatch: a defined type over an instantiation.
		if out, err := runCLI(t, bin, dir, "msg.go", "IntBox"); err != nil {
			t.Fatalf("ggen msg.go IntBox: %v\n%s", err, out)
		}
		if out, err := runGo(t, dir, nil, "vet", "."); err != nil {
			t.Errorf("go vet: %v\n%s", err, out)
		}
	})

	t.Run("AliasDeclaration_Rejected", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		writeGgenModule(t, dir, "fixture")
		writeFixture(t, filepath.Join(dir, "msg.go"), `package fixture

import "time"

//ggen:generate
type Foo = time.Time

//ggen:generate
type Bar = string

//ggen:generate
type Local struct {
	A int `+"`json:\"a\"`"+`
}

//ggen:generate
type Baz = Local
`)
		out, err := runCLI(t, bin, dir, "msg.go")
		if err == nil {
			t.Fatalf("alias declarations accepted:\n%s", out)
		}
		for _, want := range []string{
			"msg.go:6:6: type Foo = time.Time: alias declarations cannot carry methods",
			"msg.go:9:6: type Bar = string: alias declarations cannot carry methods",
			"msg.go:17:6: type Baz = Local: alias declarations cannot carry methods",
		} {
			if !strings.Contains(out, want) {
				t.Errorf("missing %q in:\n%s", want, out)
			}
		}
		mustNotHaveFile(t, filepath.Join(dir, "msg_ggen.go"))
	})

	t.Run("UnknownAnnotationToken_Rejected", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		writeGgenModule(t, dir, "fixture")
		writeFixture(t, filepath.Join(dir, "msg.go"), "package fixture\n\n//ggen:generate marshl\ntype Typo struct {\n\tA int `json:\"a\"`\n}\n\n//ggen:generate marshal ignore-unknown\ntype Two struct {\n\tA int `json:\"a\"`\n}\n")
		out, err := runCLI(t, bin, dir, "msg.go")
		if err == nil {
			t.Fatalf("typo'd annotation accepted:\n%s", out)
		}
		for _, want := range []string{
			`msg.go:3:1: unknown //ggen:generate token "marshl"`,
			`msg.go:8:1: unknown //ggen:generate token "ignore-unknown"`,
		} {
			if !strings.Contains(out, want) {
				t.Errorf("missing %q in:\n%s", want, out)
			}
		}
		mustNotHaveFile(t, filepath.Join(dir, "msg_ggen.go"))
		if out, err := runCLI(t, bin, dir, "-dry", "msg.go"); err == nil || !strings.Contains(out, `"marshl"`) {
			t.Errorf("-dry must report the token too, got err=%v:\n%s", err, out)
		}
	})

	t.Run("PackageMode_ReportsEveryStructError", func(t *testing.T) {
		t.Parallel()
		base := t.TempDir()
		writeGgenModule(t, base, "twoerrs")
		pkg := filepath.Join(base, "pkg")
		writeFixture(t, filepath.Join(pkg, "pkg.go"), "package pkg\n\n//ggen:generate\ntype First struct {\n\tA string `json:\"a\" pipe:\"maxlen=abc\"`\n}\n\n//ggen:generate\ntype Second struct {\n\tB int `json:\"b\" pipe:\"trim\"`\n}\n")
		for _, args := range [][]string{{"./pkg"}, {"-dry", "./pkg"}, {"./..."}, {"-dry", "./..."}, {"pkg/pkg.go"}} {
			out, err := runCLI(t, bin, base, args...)
			if err == nil {
				t.Fatalf("ggen %v: expected failure:\n%s", args, out)
			}
			for _, want := range []string{"First.A: `maxlen=abc`", "Second.B: `trim` is inapplicable"} {
				if !strings.Contains(out, want) {
					t.Errorf("ggen %v dropped %q:\n%s", args, want, out)
				}
			}
		}
	})

	t.Run("AliasOfAnnotatedStruct_FixedPoint", func(t *testing.T) {
		t.Parallel()
		base := t.TempDir()
		writeGgenModule(t, base, "idem")
		pkg := filepath.Join(base, "pkg")
		writeFixture(t, filepath.Join(pkg, "pkg.go"), "package pkg\n\n//ggen:generate\ntype Inner struct {\n\tX int `json:\"x\"`\n}\n\n//ggen:generate\ntype Local Inner\n\n// Reached only as a dependency, still generated in the pass.\ntype Dep struct {\n\tX int `json:\"x\"`\n}\n\n//ggen:generate\ntype Root struct {\n\tD Dep `json:\"d\"`\n}\n\n//ggen:generate\ntype LocalDep Dep\n")
		var runs [2]string
		for i := range runs {
			if out, err := runCLI(t, bin, base, "./pkg"); err != nil {
				t.Fatalf("run %d: %v\n%s", i+1, err, out)
			}
			runs[i] = mustReadOutput(t, filepath.Join(pkg, "pkg_ggen.go"))
		}
		if runs[0] != runs[1] {
			t.Errorf("output differs between run 1 (%d bytes) and run 2 (%d bytes)", len(runs[0]), len(runs[1]))
		}
		for _, want := range []string{"return Inner(s).JSONSize()", "return Dep(s).JSONSize()"} {
			if !strings.Contains(runs[0], want) {
				t.Errorf("first run must already delegate (%q missing):\n%s", want, runs[0])
			}
		}
		if out, err := runGo(t, base, nil, "vet", "./pkg"); err != nil {
			t.Errorf("go vet: %v\n%s", err, out)
		}
	})

	t.Run("EmbeddedOnly_DependencyGenerated", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		writeGgenModule(t, dir, "fixture")
		writeFixture(t, filepath.Join(dir, "msg.go"), `package fixture

// Outer reaches Inner only through the promoted fields of embedded Base.
//
//ggen:generate
type Outer struct {
	Base
	Own int `+"`json:\"own\"`"+`
}

type Base struct {
	Mid
	In Inner `+"`json:\"in\"`"+`
}

type Mid struct {
	Deep []Leaf `+"`json:\"deep\"`"+`
}

type Leaf struct {
	N int `+"`json:\"n\" pipe:\"lte=5\"`"+`
}

type Inner struct {
	X int `+"`json:\"x\" pipe:\"required gte=10\"`"+`
}
`)
		writeFixture(t, filepath.Join(dir, "msg_test.go"), `package fixture

import (
	"errors"
	"testing"

	"github.com/sirkostya009/ggen"
)

func TestReach(t *testing.T) {
	var gte *ggen.GTEError
	var lte *ggen.LTEError
	var rq *ggen.RequiredError
	var uk *ggen.UnknownKeyError
	_, _, err := Outer{}.DecodeFrom([]byte(`+"`"+`{"own":1,"in":{"x":1}}`+"`"+`))
	if !errors.As(err, &gte) {
		t.Errorf("want GTEError, got %v", err)
	}
	_, _, err = Outer{}.DecodeFrom([]byte(`+"`"+`{"own":1,"in":{}}`+"`"+`))
	if !errors.As(err, &rq) {
		t.Errorf("want RequiredError, got %v", err)
	}
	_, _, err = Outer{}.DecodeFrom([]byte(`+"`"+`{"own":1,"in":{"x":10,"bogus":1}}`+"`"+`))
	if !errors.As(err, &uk) {
		t.Errorf("want UnknownKeyError, got %v", err)
	}
	_, _, err = Outer{}.DecodeFrom([]byte(`+"`"+`{"own":1,"in":{"x":10},"deep":[{"n":9}]}`+"`"+`))
	if !errors.As(err, &lte) {
		t.Errorf("want LTEError through two embedding levels, got %v", err)
	}
}
`)
		if out, err := runCLI(t, bin, dir, "msg.go"); err != nil {
			t.Fatalf("ggen: %v\n%s", err, out)
		}
		body := mustReadOutput(t, filepath.Join(dir, "msg_ggen.go"))
		if strings.Contains(body, "json.Unmarshal") {
			t.Errorf("embedded-only dependency fell to the reflective fallback:\n%s", body)
		}
		if out, err := runGo(t, dir, nil, "test", "."); err != nil {
			t.Fatalf("go test: %v\n%s", err, out)
		}
	})

	t.Run("SamePkgCodec_NotAutoGenerated", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		writeGgenModule(t, dir, "fixture")
		writeFixture(t, filepath.Join(dir, "msg.go"), `package fixture

import "github.com/sirkostya009/ggen"

// Hand is a same-package struct with a hand-written ggen method set; the
// pass must call it, not regenerate it on top.
type Hand struct{ V int }

func (h Hand) DecodeFrom(data []byte) (Hand, int, error)     { return Hand{V: 7}, len(data), nil }
func (h Hand) DecodeFromStream(s *ggen.Stream) (Hand, error) { return Hand{V: 7}, nil }
func (h Hand) JSONSize() int                                 { return 4 }
func (h Hand) AppendJSON(dst []byte) ([]byte, error)         { return append(dst, "true"...), nil }

//ggen:generate
type Host struct {
	H Hand `+"`json:\"h\"`"+`
}
`)
		if out, err := runCLI(t, bin, dir, "msg.go"); err != nil {
			t.Fatalf("ggen: %v\n%s", err, out)
		}
		body := mustReadOutput(t, filepath.Join(dir, "msg_ggen.go"))
		if strings.Contains(body, "func (recv Hand) DecodeFrom(") {
			t.Errorf("hand-written codec regenerated:\n%s", body)
		}
		if !strings.Contains(body, "result.H.DecodeFrom(data[i:])") {
			t.Errorf("hand-written DecodeFrom not called:\n%s", body)
		}
		if out, err := runGo(t, dir, nil, "vet", "."); err != nil {
			t.Errorf("go vet: %v\n%s", err, out)
		}
	})

	t.Run("AliasedImport_SpelledByQualifier", func(t *testing.T) {
		t.Parallel()
		base := t.TempDir()
		writeGgenModule(t, base, "example.com/imp")
		writeFixture(t, filepath.Join(base, "aleaf", "leaf.go"), "package leaf\n\ntype Name string\n\ntype Pt struct {\n\tX int `json:\"x\"`\n}\n")
		writeFixture(t, filepath.Join(base, "bleaf", "leaf.go"), "package leaf\n\ntype Other string\n")
		pkg := filepath.Join(base, "doc")
		writeFixture(t, filepath.Join(pkg, "doc.go"), `package doc

import (
	lf "example.com/imp/aleaf"
	other "example.com/imp/bleaf"
)

//ggen:generate
type Doc struct {
	Names  []lf.Name             `+"`json:\"names\" pipe:\"inner:minlen=1\"`"+`
	One    lf.Name               `+"`json:\"one\" pipe:\"minlen=1\"`"+`
	Pts    map[string]*lf.Pt     `+"`json:\"pts\"`"+`
	Others []other.Other         `+"`json:\"others\"`"+`
}
`)
		if out, err := runCLI(t, bin, base, "./doc"); err != nil {
			t.Fatalf("ggen ./doc: %v\n%s", err, out)
		}
		body := mustReadOutput(t, filepath.Join(pkg, "doc_ggen.go"))
		// aleaf keeps its declared name; bleaf, the second `leaf`, is bound
		// explicitly. Both named strings take the inline cast path.
		for _, want := range []string{
			"\t\"example.com/imp/aleaf\"\n", "\tleaf2 \"example.com/imp/bleaf\"\n",
			"[]leaf.Name{}", `leaf.Name("")`, `leaf2.Other("")`, "*leaf.Pt",
		} {
			if !strings.Contains(body, want) {
				t.Errorf("missing %q in:\n%s", want, body)
			}
		}
		if strings.Contains(body, "lf.") || strings.Contains(body, "other.") {
			t.Errorf("source import alias leaked into the output:\n%s", body)
		}
		if out, err := runGo(t, base, nil, "vet", "./doc"); err != nil {
			t.Errorf("go vet ./doc: %v\n%s", err, out)
		}
	})
}
