package scan

import (
	"io"
	"testing"
)

// sizedChunkReader delivers at most n bytes per Read, then a stable io.EOF.
type sizedChunkReader struct {
	data []byte
	n    int
}

func (r *sizedChunkReader) Read(p []byte) (int, error) {
	if len(r.data) == 0 {
		return 0, io.EOF
	}
	n := min(r.n, len(r.data), len(p))
	copy(p, r.data[:n])
	r.data = r.data[n:]
	return n, nil
}

// TestBytesStreamTruncationErrorParity pins the drained-truncation error
// identity of the stream walkers to the bytes path: for every truncated
// input, SkipValue / Any / AnyNumber must surface the SAME sentinel on both
// paths, at every chunk size (each refill site is a potential divergence).
func TestBytesStreamTruncationErrorParity(t *testing.T) {
	t.Parallel()
	inputs := []string{
		"", "nul", "n", "nu", "tru", "t", "fals", "f",
		"[", "[1,", "[1", "[[", "[ ",
		"{", `{"a"`, `{"a":`, `{"a":1`, `{"a":1,`,
		`"ab`, `"a\`, "-", "1.", "12.", "1e",
	}
	chunks := []int{1, 3, 64}
	for _, in := range inputs {
		_, wantSkip := SkipValue([]byte(in), 0)
		_, _, wantAny := Any([]byte(in), 0)
		_, _, wantAnyNum := AnyNumber([]byte(in), 0)
		for _, cs := range chunks {
			var s Stream
			s.Reset(&sizedChunkReader{data: []byte(in), n: cs}, nil)
			if got := s.SkipValue(); got != wantSkip {
				t.Errorf("SkipValue(%q) chunk=%d: stream %v, bytes %v", in, cs, got, wantSkip)
			}
			s.Reset(&sizedChunkReader{data: []byte(in), n: cs}, nil)
			if _, got := s.Any(); got != wantAny {
				t.Errorf("Any(%q) chunk=%d: stream %v, bytes %v", in, cs, got, wantAny)
			}
			s.Reset(&sizedChunkReader{data: []byte(in), n: cs}, nil)
			if _, got := s.AnyNumber(); got != wantAnyNum {
				t.Errorf("AnyNumber(%q) chunk=%d: stream %v, bytes %v", in, cs, got, wantAnyNum)
			}
		}
	}
	// Value primitives called with the window already drained: every head
	// used to return the raw ReadMore error where the bytes twin reports a
	// grammar sentinel ("-" additionally covers Int64's sign arm).
	heads := []struct {
		name   string
		in     string
		bytes  func([]byte) error
		stream func(*Stream) error
	}{
		{"Int64", "", func(d []byte) error { _, _, e := Int64(d, 0); return e }, func(s *Stream) error { _, e := s.Int64(); return e }},
		{"Int64-sign", "-", func(d []byte) error { _, _, e := Int64(d, 0); return e }, func(s *Stream) error { _, e := s.Int64(); return e }},
		{"Uint64", "", func(d []byte) error { _, _, e := Uint64(d, 0); return e }, func(s *Stream) error { _, e := s.Uint64(); return e }},
		{"Float64", "", func(d []byte) error { _, _, e := Float64(d, 0); return e }, func(s *Stream) error { _, e := s.Float64(); return e }},
		{"Number", "", func(d []byte) error { _, _, e := Number(d, 0); return e }, func(s *Stream) error { _, e := s.Number(); return e }},
		{"Bool", "", func(d []byte) error { _, _, e := Bool(d, 0); return e }, func(s *Stream) error { _, e := s.Bool(); return e }},
		{"String", "", func(d []byte) error { _, _, e := String(d, 0, true); return e }, func(s *Stream) error { _, e := s.String(true); return e }},
	}
	for _, h := range heads {
		want := h.bytes([]byte(h.in))
		for _, cs := range chunks {
			var s Stream
			s.Reset(&sizedChunkReader{data: []byte(h.in), n: cs}, nil)
			if got := h.stream(&s); got != want {
				t.Errorf("%s(%q) chunk=%d: stream %v, bytes %v", h.name, h.in, cs, got, want)
			}
		}
	}
	// ConsumeColon has no bytes twin — generated bytes code reports
	// ErrBadObject for a missing ':', so a drained head must too.
	var s Stream
	s.Reset(&sizedChunkReader{data: nil, n: 1}, nil)
	if got := s.ConsumeColon(); got != ErrBadObject {
		t.Errorf("ConsumeColon(drained): got %v, want %v", got, ErrBadObject)
	}
}
