// Code generated by ggen; DO NOT EDIT.

package thirdparty2

import (
	"github.com/sirkostya009/ggen/decode"
	"github.com/sirkostya009/ggen/decode/validation"
	"github.com/sirkostya009/ggen/encode"
	"github.com/sirkostya009/ggen/scan"
	"strconv"
	"unsafe"
)

// DecodeFrom decodes one External2 out of data starting at i and returns
// the decoded value, the position past the last consumed byte, and any
// error. Strings inside the returned value alias data via unsafe.String —
// callers MUST NOT mutate data while the value is in use.
//
// For top-level use, prefer decode.Unmarshal[External2](data) (or
// decode.UnmarshalSlice / Read / UnmarshalStream variants from the
// decode package) — those are convenience wrappers around DecodeFrom.
func (External2) DecodeFrom(data []byte, i int) (External2, int, error) {
	var result External2
	seenKey := false
	seenValue := false
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, 0, scan.ErrBadObject
	}
	i++
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		if !seenKey {
			return result, 0, &validation.RequiredError{Field: "key"}
		}
		return result, i + 1, nil
	}
	for {
		var key string
		j := i
		if i >= len(data) || data[i] != '"' {
			return result, 0, scan.ErrExpectString
		}
		{
			_ks := i + 1
			_ke := _ks
			for _ke < len(data) && data[_ke] != '"' && data[_ke] != '\\' {
				_ke++
			}
			if _ke >= len(data) {
				return result, 0, scan.ErrUnterminated
			}
			if data[_ke] == '"' {
				key = unsafe.String(unsafe.SliceData(data[_ks:]), _ke-_ks)
				j = _ke + 1
			} else {
				_isv, _isj, _iserr := scan.String(data, i)
				if _iserr != nil {
					return result, 0, _iserr
				}
				key = _isv
				j = _isj
			}
		}
		for j < len(data) && (data[j] == ' ' || data[j] == '\t' || data[j] == '\n' || data[j] == '\r') {
			j++
		}
		if j >= len(data) || data[j] != ':' {
			return result, 0, scan.ErrBadObject
		}
		j++
		for j < len(data) && (data[j] == ' ' || data[j] == '\t' || data[j] == '\n' || data[j] == '\r') {
			j++
		}
		switch len(key) {
		case 3:
			if key == "key" {
				if seenKey {
					return result, 0, &validation.DuplicateKeyError{Field: "key"}
				}
				seenKey = true
				if j >= len(data) || data[j] != '"' {
					return result, 0, scan.ErrExpectString
				}
				{
					_ks := j + 1
					_ke := _ks
					for _ke < len(data) && data[_ke] != '"' && data[_ke] != '\\' {
						_ke++
					}
					if _ke >= len(data) {
						return result, 0, scan.ErrUnterminated
					}
					if data[_ke] == '"' {
						result.Key = unsafe.String(unsafe.SliceData(data[_ks:]), _ke-_ks)
						j = _ke + 1
					} else {
						_isv, _isj, _iserr := scan.String(data, j)
						if _iserr != nil {
							return result, 0, _iserr
						}
						result.Key = _isv
						j = _isj
					}
				}
				if len(result.Key) < 1 {
					return result, 0, &validation.MinLenError{Field: "key", Limit: 1, Got: len(result.Key)}
				}
			} else {
				return result, 0, &validation.UnknownKeyError{Field: key}
			}
		case 5:
			if key == "value" {
				if seenValue {
					return result, 0, &validation.DuplicateKeyError{Field: "value"}
				}
				seenValue = true
				{
					_neg := false
					if j < len(data) && data[j] == '-' {
						_neg = true
						j++
					}
					if j >= len(data) || data[j] < '0' || data[j] > '9' {
						return result, 0, scan.ErrBadNumber
					}
					var _n int64
					for j < len(data) && data[j] >= '0' && data[j] <= '9' {
						_n = _n*10 + int64(data[j]-'0')
						j++
					}
					if j < len(data) {
						_c := data[j]
						if _c == '.' || _c == 'e' || _c == 'E' {
							return result, 0, scan.ErrBadNumber
						}
					}
					if _neg {
						_n = -_n
					}
					result.Value = int(_n)
				}
				if result.Value < 0 {
					return result, 0, &validation.GTEError{Field: "value", Limit: 0, Value: result.Value}
				}
			} else {
				return result, 0, &validation.UnknownKeyError{Field: key}
			}
		default:
			return result, 0, &validation.UnknownKeyError{Field: key}
		}
		for j < len(data) && (data[j] == ' ' || data[j] == '\t' || data[j] == '\n' || data[j] == '\r') {
			j++
		}
		if j >= len(data) {
			return result, 0, scan.ErrBadObject
		}
		if data[j] == ',' {
			j++
			i = j
			for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[j] == '}' {
			if !seenKey {
				return result, 0, &validation.RequiredError{Field: "key"}
			}
			return result, j + 1, nil
		}
		return result, 0, scan.ErrBadObject
	}

}

// DecodeStreamFrom is the io.Reader-backed counterpart of DecodeFrom,
// pulling bytes from a *scan.Stream. Use decode.UnmarshalStream to drive
// it from the top level.
func (External2) DecodeStreamFrom(_s *scan.Stream, i int) (External2, int, error) {
	var result External2
	seenKey := false
	seenValue := false
	i, err := _s.ObjectOpen(i)
	if err != nil {
		return result, 0, err
	}
	i, err = _s.SkipSpace(i)
	if err != nil {
		return result, 0, err
	}
	if i >= len(_s.Bytes()) {
		if err = _s.ReadMore(); err != nil {
			return result, 0, err
		}
	}
	if _s.Bytes()[i] == '}' {
		if !seenKey {
			return result, 0, &validation.RequiredError{Field: "key"}
		}
		return result, i + 1, nil
	}
	for {
		key, j, err := _s.String(i)
		if err != nil {
			return result, 0, err
		}
		j, err = _s.SkipSpace(j)
		if err != nil {
			return result, 0, err
		}
		if j >= len(_s.Bytes()) {
			if err = _s.ReadMore(); err != nil {
				return result, 0, err
			}
		}
		if _s.Bytes()[j] != ':' {
			return result, 0, scan.ErrBadObject
		}
		j, err = _s.SkipSpace(j + 1)
		if err != nil {
			return result, 0, err
		}
		switch len(key) {
		case 3:
			if key == "key" {
				if seenKey {
					return result, 0, &validation.DuplicateKeyError{Field: "key"}
				}
				seenKey = true
				v, k, err := _s.String(j)
				if err != nil {
					return result, 0, err
				}
				result.Key = v
				j = k
				if len(result.Key) < 1 {
					return result, 0, &validation.MinLenError{Field: "key", Limit: 1, Got: len(result.Key)}
				}
			} else {
				return result, 0, &validation.UnknownKeyError{Field: key}
			}
		case 5:
			if key == "value" {
				if seenValue {
					return result, 0, &validation.DuplicateKeyError{Field: "value"}
				}
				seenValue = true
				v, k, err := _s.Int64(j)
				if err != nil {
					return result, 0, err
				}
				result.Value = int(v)
				j = k
				if result.Value < 0 {
					return result, 0, &validation.GTEError{Field: "value", Limit: 0, Value: result.Value}
				}
			} else {
				return result, 0, &validation.UnknownKeyError{Field: key}
			}
		default:
			return result, 0, &validation.UnknownKeyError{Field: key}
		}
		j, err = _s.SkipSpace(j)
		if err != nil {
			return result, 0, err
		}
		if j >= len(_s.Bytes()) {
			if err = _s.ReadMore(); err != nil {
				return result, 0, err
			}
		}
		c := _s.Bytes()[j]
		if c == ',' {
			i = j + 1
			i, err = _s.SkipSpace(i)
			if err != nil {
				return result, 0, err
			}
			continue
		}
		if c == '}' {
			if !seenKey {
				return result, 0, &validation.RequiredError{Field: "key"}
			}
			return result, j + 1, nil
		}
		return result, 0, scan.ErrBadObject
	}

}

// JSONSize returns an upper bound on the marshaled size, used by
// encode.Marshal to pre-size the buffer in a single allocation.
func (s External2) JSONSize() int {
	size := 39
	size += len(s.Key) * 2
	return size
}

// AppendJSON appends the JSON encoding of s to dst. This is the core
// marshal primitive; for top-level use, prefer encode.Marshal(s) /
// encode.Write(w, s) / encode.MarshalSlice(items) from the encode package.
func (s External2) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"key\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Key)
	dst = append(dst, ",\"value\":"...)
	dst = strconv.AppendInt(dst, int64(s.Value), 10)
	return append(dst, '}'), nil
}

// MarshalJSON implements json.Marshaler (encoding/json and encoding/json/v2).
func (s External2) MarshalJSON() ([]byte, error) {
	return encode.Marshal(s)
}

// UnmarshalJSON implements json.Unmarshaler (encoding/json and encoding/json/v2).
// Note: overwrites the receiver; does not implement merge semantics.
func (s *External2) UnmarshalJSON(data []byte) error {
	v, err := decode.Unmarshal[External2](data)
	if err != nil {
		return err
	}
	*s = v
	return nil
}
