package main

import (
	"bytes"
	"fmt"
	"go/format"
	"text/template"
)

var tmpl = template.Must(template.New("gen").Funcs(template.FuncMap{
	"tokenKind":    tokenKind,
	"tokenExtract": tokenExtract,
	"kindName":     kindName,
}).Parse(genTemplate))

func generate(pkg string, structs []StructInfo) ([]byte, error) {
	var buf bytes.Buffer
	err := tmpl.Execute(&buf, map[string]any{
		"Package": pkg,
		"Structs": structs,
	})
	if err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated code: %w\n\nraw output:\n%s", err, buf.String())
	}
	return src, nil
}

func tokenKind(k TypeKind) string {
	switch k {
	case KindString:
		return `'"'`
	case KindInt, KindInt64, KindUint64, KindFloat64:
		return `'0'`
	case KindBool:
		return "" // special case: 't' or 'f'
	case KindStruct:
		return `'{'`
	case KindSlice:
		return `'['`
	default:
		return `'"'`
	}
}

func tokenExtract(k TypeKind, tokVar string) string {
	switch k {
	case KindString:
		return tokVar + ".String()"
	case KindInt:
		return "int(" + tokVar + ".Int())"
	case KindInt64:
		return tokVar + ".Int()"
	case KindUint64:
		return tokVar + ".Uint()"
	case KindFloat64:
		return tokVar + ".Float()"
	case KindBool:
		return tokVar + ".Bool()"
	default:
		return tokVar + ".String()"
	}
}

func kindName(k TypeKind) string {
	switch k {
	case KindString:
		return "string"
	case KindInt, KindInt64, KindUint64, KindFloat64:
		return "number"
	case KindBool:
		return "bool"
	case KindStruct:
		return "object"
	case KindSlice:
		return "array"
	default:
		return "unknown"
	}
}

const genTemplate = `// Code generated by ggen; DO NOT EDIT.

//go:build goexperiment.jsonv2

package {{.Package}}

import (
	"encoding/json/jsontext"
	"fmt"
	"io"
)

{{range .Structs}}
func (s {{.Name}}) ParseFrom(r io.Reader) ({{.Name}}, error) {
	dec := jsontext.NewDecoder(r)
	return s.DecodeFrom(dec)
}

func (s {{.Name}}) DecodeFrom(dec *jsontext.Decoder) ({{.Name}}, error) {
	var result {{.Name}}

	tok, err := dec.ReadToken()
	if err != nil {
		return result, fmt.Errorf("expected '{': %w", err)
	}
	if tok.Kind() != '{' {
		return result, fmt.Errorf("expected '{', got %v", tok.Kind())
	}

	{{- range .Fields}}{{if .IsRequired}}
	seen{{.GoName}} := false
	{{- end}}{{end}}

	for dec.PeekKind() != '}' {
		keyTok, err := dec.ReadToken()
		if err != nil {
			return result, fmt.Errorf("reading key: %w", err)
		}

		switch keyTok.String() {
		{{- range .Fields}}
		case "{{.JSONName}}":
			{{- if eq .Kind 7}}{{/* KindStruct */}}
			nested, err := {{.GoType}}{}.DecodeFrom(dec)
			if err != nil {
				return result, fmt.Errorf("decoding \"{{.JSONName}}\": %w", err)
			}
			result.{{.GoName}} = nested
			{{- else if eq .Kind 6}}{{/* KindSlice */}}
			arrTok, err := dec.ReadToken()
			if err != nil {
				return result, fmt.Errorf("reading \"{{.JSONName}}\": %w", err)
			}
			if arrTok.Kind() != '[' {
				return result, fmt.Errorf("expected '[' for \"{{.JSONName}}\", got %v", arrTok.Kind())
			}
			for dec.PeekKind() != ']' {
				{{- if eq .ElemKind 7}}{{/* nested struct slice */}}
				elem, err := {{.ElemType}}{}.DecodeFrom(dec)
				if err != nil {
					return result, fmt.Errorf("decoding element of \"{{.JSONName}}\": %w", err)
				}
				result.{{.GoName}} = append(result.{{.GoName}}, elem)
				{{- else}}
				elemTok, err := dec.ReadToken()
				if err != nil {
					return result, fmt.Errorf("reading element of \"{{.JSONName}}\": %w", err)
				}
				{{- if eq .ElemKind 5}}{{/* bool */}}
				if elemTok.Kind() != 't' && elemTok.Kind() != 'f' {
					return result, fmt.Errorf("expected bool in \"{{.JSONName}}\", got %v", elemTok.Kind())
				}
				{{- else}}
				if elemTok.Kind() != {{tokenKind .ElemKind}} {
					return result, fmt.Errorf("expected {{kindName .ElemKind}} in \"{{.JSONName}}\", got %v", elemTok.Kind())
				}
				{{- end}}
				result.{{.GoName}} = append(result.{{.GoName}}, {{tokenExtract .ElemKind "elemTok"}})
				{{- end}}
			}
			if _, err := dec.ReadToken(); err != nil {
				return result, fmt.Errorf("expected ']' for \"{{.JSONName}}\": %w", err)
			}
			{{- else if eq .Kind 5}}{{/* KindBool */}}
			valTok, err := dec.ReadToken()
			if err != nil {
				return result, fmt.Errorf("reading \"{{.JSONName}}\": %w", err)
			}
			if valTok.Kind() != 't' && valTok.Kind() != 'f' {
				return result, fmt.Errorf("expected bool for \"{{.JSONName}}\", got %v", valTok.Kind())
			}
			result.{{.GoName}} = valTok.Bool()
			{{- else}}
			valTok, err := dec.ReadToken()
			if err != nil {
				return result, fmt.Errorf("reading \"{{.JSONName}}\": %w", err)
			}
			if valTok.Kind() != {{tokenKind .Kind}} {
				return result, fmt.Errorf("expected {{kindName .Kind}} for \"{{.JSONName}}\", got %v", valTok.Kind())
			}
			result.{{.GoName}} = {{tokenExtract .Kind "valTok"}}
			{{- end}}
			{{- if .IsRequired}}
			seen{{.GoName}} = true
			{{- end}}
			{{- $field := .}}
			{{- range .Validation}}
			{{- if eq .Name "minlen"}}
			if len(result.{{$field.GoName}}) < {{.Value}} {
				return result, fmt.Errorf("\"{{$field.JSONName}}\": length %d below minimum {{.Value}}", len(result.{{$field.GoName}}))
			}
			{{- end}}
			{{- if eq .Name "maxlen"}}
			if len(result.{{$field.GoName}}) > {{.Value}} {
				return result, fmt.Errorf("\"{{$field.JSONName}}\": length %d exceeds maximum {{.Value}}", len(result.{{$field.GoName}}))
			}
			{{- end}}
			{{- if eq .Name "min"}}
			if result.{{$field.GoName}} < {{.Value}} {
				return result, fmt.Errorf("\"{{$field.JSONName}}\": value %v below minimum {{.Value}}", result.{{$field.GoName}})
			}
			{{- end}}
			{{- if eq .Name "max"}}
			if result.{{$field.GoName}} > {{.Value}} {
				return result, fmt.Errorf("\"{{$field.JSONName}}\": value %v exceeds maximum {{.Value}}", result.{{$field.GoName}})
			}
			{{- end}}
			{{- end}}
		{{- end}}
		default:
			if _, err := dec.ReadValue(); err != nil {
				return result, fmt.Errorf("skipping unknown field %q: %w", keyTok.String(), err)
			}
		}
	}

	if _, err := dec.ReadToken(); err != nil {
		return result, fmt.Errorf("expected '}': %w", err)
	}

	{{- range .Fields}}{{if .IsRequired}}
	if !seen{{.GoName}} {
		return result, fmt.Errorf("missing required field \"{{.JSONName}}\"")
	}
	{{- end}}{{end}}

	return result, nil
}
{{end}}
`
